<?php $title = 'Luigi Amara - El acceso a las fuentes o un nuevo enciclopedismo digital | Revista Fractal'; ?>

<?php include 'header.php' ?>
<section class="titulo">
	<article class="">
		<h3>Número 57</h3>
		<h1>El acceso a las fuentes o un nuevo enciclopedismo digital
</h1>
		<h2>Luigi Amara</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
<h4>El conflicto </h4>
<p>Vivimos una tensión, un tremendo conflicto, entre lo que se ha dado en llamar la &ldquo;propiedad intelectual&rdquo; y los derechos y libertades de los lectores o usuarios. A raíz de que los avances técnicos permitieron que los medios para reproducir y copiar los bienes culturales estén al alcance de la mayoría y no sean un privilegio de unos cuantos, esa tensión se ha agudizado y, por lo menos, ha mostrado la necesidad de una legislación diferente, sino es que de un cambio completo de paradigma. De un lado, las fotocopiadoras, el quemador de cds, los archivos compartidos en la red, el software de código abierto, las descargas de música, texto o video y su circulación relativamente libre de mano en mano o de computadora a computadora; de otro, el endurecimiento de las leyes del copyright, el lucro como valor rector, las multas millonarias a los internautas que descargan archivos protegidos, el fenómeno de la piratería criminal como una sombra que acompaña la avidez de los consorcios. De un lado las restricciones y, del otro, las retículas de intercambio. De un lado los altos precios de los bienes culturales y, del otro, el derecho a la cultura. <br><br>
  El problema es que mientras más fácil sea publicar y difundir libros y discos en los medios electrónicos, mientras baste oprimir un botón para copiar una canción o una película, por encima o por debajo de los candados de seguridad y de los parches a las legislaciones internacionales, la red de intercambios, downloads y archivos compartidos se extenderá y conseguirá lo que quiere, pues como escribe el colectivo italiano Wu Ming, pionero en muchos sentidos en la libre circulación de los bienes culturales, se trata ya a estas alturas de un auténtico maremoto. </p>
  
  <h4>Una legislación obsoleta</h4> <br>
  <p>
  Las leyes del copyright se originaron en el siglo xvi en Inglaterra, por lo que no es de extrañar que a pesar de las múltiples enmiendas y actualizaciones, del convenio de Berna y de la Ley del Copyright del Milenio Digital, sea una legislación vetusta, poco flexible para adaptarse a los tiempos que corren. Dicho de manera muy sucinta, el copyright nació como una forma en la que el Estado brindaba en exclusiva a una casta profesional de editores (los stationers) el &ldquo;derecho de copia&rdquo; de toda impresión, con lo cual no sólo les concedía el monopolio de las imprentas, sino también la propiedad de las obras. En la actualidad, el copyright rige la explotación comercial de las obras y su fin es que sus titulares tengan derechos exclusivos para controlar su distribución y reproducción. <br><br>
  Enmascarados muchas veces bajo el término de copyright, en la mayoría de los países que siguen el derecho continental, se encuentran los derechos de autor, impulsados a fines del siglo XVIII por el dramaturgo Pierre-Augustin de Beaumarchais. Estos derechos reconocen que son los propios autores los dueños de sus obras (al menos hasta que caigan dentro del dominio público), a la vez que garantizan que el autor o sus herederos reciban algún beneficio por la comercialización de sus creaciones.<br><br>
  Visto desde esta perspectiva, los derechos de autor parecen no sólo intachables, sino del todo plausibles y su defensa necesaria. ¿Por qué quien construye una silla puede venderla o heredarla a sus hijos y no así el que ha escrito una novela o una sinfonía? El problema comienza cuando, bajo la categoría un tanto equívoca de &ldquo;propiedad intelectual&rdquo;, comparaciones como la anterior se llevan demasiado lejos y entonces se olvida que ni la novela ni la sinfonía son del todo equiparables a la silla, puesto que si bien tienen un perfil comercial y hasta cierto punto son también mercancías, al mismo tiempo son bienes culturales, que otros querrán leer o escuchar en una medida muy distinta de la que otros querrán sentarse en la silla. Desde luego hay todavía una discusión pendiente que debería dirigirse hacia el cuestionamiento de lo que se entiende por &ldquo;propiedad&rdquo; en los casos de autoría, pero está claro que al comercializar su obra, el autor no se queda sin ella (como sí sucede en el caso de la venta de una silla), e incluso podría decirse que en muchos sentidos se enriquece al sacarla del cajón y hacerla pública.<br><br>
  El sesgo restrictivo, es decir, eminentemente lucrativo, que en especial las agrupaciones y consorcios suelen imprimir al copyright y a los derechos de autor, que se han convertido en una gran fuente de ingresos corporativos gracias a que funcionan como instrumentos para impedir la libre reproducción y circulación de las obras, ha llevado a que en las últimas décadas surjan toda clase de movimientos críticos para contrarrestarlo y en algunos casos ponerlo de cabeza, bajo la premisa de que dichas restricciones no siempre son legítimas y con frecuencia entran en conflicto con las libertades y derechos de los lectores y los usuarios.</p>
  <h4>
  La otra cara de la moneda </h4>
  <br>
  Así como un autor tiene derecho a comercializar lo que un tanto pomposamente se ha denominado &ldquo;los frutos del espíritu&rdquo;, así el lector o usuario también tiene (o debería tener) ciertos derechos, que por lo general no son reconocidos o le son escamotados sistemáticamente. ¿Derecho a qué? Como una extensión natural del derecho a la cultura,<del>1</del> a gozar del arte y beneficiarse de los avances científicos, debería tener el derecho de leer lo que quiere leer, de ver, escuchar, reproducir y estudiar lo que le interesa. También debería tener la libertad de redistribuirlo y circularlo a quien crea que le pueda interesar y, desde luego, a nutrirse de aquello que ha leído o visto o estudiado para crear nuevas obras del espíritu, incluso si son meras parodias, pastiches o regurgitaciones. <br><br>
  Pero enunciado así, el derecho a la cultura<del>2</del> y las libertades de los lectores y usuarios, que a primera vista suenan razonables y defendibles, se topan con el derecho también legítimo del autor de beneficiarse económicamente de lo que ha producido. Es verdad que le gustaría que su novela circulara y fuera leída por el mayor número de personas posible, o que el disco lo escucharan tanto en las discotecas de Moscú como en los radios de pilas de Guatemala, pero también le gustaría vivir de lo que hace, obtener ganancias de sus obras y así estar en condiciones de seguir haciendo lo que le gusta, que es, según el caso, escribir o componer música. <br>
  <p>En términos generales, el lector o escucha puede acceder a un libro o a las canciones de un disco si paga por ello; una vez hecho esto puede, con ciertas restricciones, copiarlo para su propio disfrute o para el disfrute colectivo, si no persigue fines de lucro; también puede prestarlo, regalarlo, etc., o bien revender el libro o el disco (que no sus copias), por ejemplo en tiendas de segunda mano. Está claro que de estas copias ulteriores sin fines de lucro y de la reventa de materiales usados, el titular de los derechos de autor no obtiene un beneficio económico directo, pero sí consigue que su obra sea leída o escuchada por más gente (esto es, mayor difusión), lo que a la larga puede redundar en nuevas ventas, tanto de ésta como de sus demás obras. Desde luego el lector o escucha también puede ir a la biblioteca o encender la radio y no pagar un centavo, pero la codicia de quienes ostentan el copyright ha hecho que las restricciones se extiendan incluso a estos campos, como es el caso de muchas editoriales que en Estados Unidos y otros países han prohibido el préstamo público en bibliotecas o lo han condicionado al pago de una cuota. <br><br>
  <h4>Los aires levógiros del copyleft</h4>
  
  <p>El copyleft y otras licencias como Creative Commons surgieron como una alternativa a las tensiones generadas en los últimos tiempos por el endurecimiento de las leyes del copyright y los derechos de autor. El objetivo inicial era que, en lo que se refiere al software, el usuario tuviera la libertad de ejecutar, copiar, distribuir y desde luego enriquecer los programas. Uno de los principales defensores de este giro ha sido el programador y activista Richard Stallman y su movimiento a favor del Software Libre. La idea central que está detrás de todo ello es muy sencilla: sin renunciar a los derechos que posee el autor, que sea él mismo quien decida cómo difundir su software y hasta qué punto puede ser copiado, puesto en circulación y modificado. Gracias a una leyenda que hace las veces de licencia o de instrumento legal, otorga el derecho a utilizarla, modificarla y redistribuirla como mejor le parezca. De esta manera, tanto el software como las libertades asociadas a su uso y disfrute se convierten en elementos legalmente inseparables. <br><br>
  Los aires del copyleft no sólo soplan en el software, sino que se han adaptado a diversos medios, como la literatura, la fotografía o la música, y a la fecha son ya pocas las ramas de la cultura que no se han visto sacudidas y beneficiadas por él. Al reproducir un texto con licencia copyleft se deben acatar los deseos del autor siempre que sean legítimos, es decir, siempre que a su vez respeten las libertades fundamentales del lector o usuario para ese tipo de textos. Si el autor exige, por ejemplo, que cada lectura de ese libro le sea remunerada de cierta manera, estará contraviniendo la libertad del lector de, por ejemplo, prestarle el libro a quien quiera o de leerlo en voz alta a sus hijos, por lo que sus deseos dejan de ser legítimos. <br><br>
  <p>Más allá de su utilidad práctica, lo que el movimiento del software libre hizo ver con toda claridad fue que los derechos del autor debían tener también límites y estar acotados en función de las libertades y derechos de los usuarios, pues de otra forma se vuelven abusivos y francamente voraces.</p> 
  <h4>
  Libertades y derechos de los lectores </h4>
  <p>
  Una vez que se enfoca desde esta perspectiva la tensión actual entre la &ldquo;propiedad intelectual&rdquo; y las libertades de los lectores o usuarios, surge la pregunta de cuáles son los derechos y las libertades de cada cual y de ambos en consonancia, pues no tiene caso que la legislación en materia de copyright y derechos de autor siga modificándose y adaptándose a la revolución tecnológica sin tomar en cuenta el otro lado, el correspondiente a los que leerán, duplicarán, disfrutarán o pondrán en circulación esas obras. <br><br>
  Richard Stallman, en su caracterización del software libre, ha enumerado cuatro libertades básicas del usuario: 1) La libertad para ejecutar el programa sea cual sea su propósito. 2) La libertad para estudiar el funcionamiento del programa y adaptarlo a sus necesidades. 3) Libertad para redistribuir copias y ayudar así a los amigos. 4) Libertad para mejorar el programa y luego publicarlo para el bien de toda la comunidad. <br><br>
  ¿Pueden extenderse estas libertades básicas al lector o espectador de bienes culturales? ¿De qué manera garantizar las libertades del lector sin contravenir los derechos legítimos de los autores?<br>
  Dos de las libertades básicas de los usuarios que propone Stallman presuponen el acceso al código fuente del programa, lo cual permite hacer una analogía y sugerir que las libertades del lector o espectador (aunque habría que encontrar una palabra más abarcadora y sugerente) comienzan, precisamente, con un derecho fundamental, no reconocido hasta hoy: el de estar en condiciones de acceder a las fuentes. Los estudiantes de música se lamentan de que deben comprar partituras a un costo muy elevado, no importa si se trata de autores que han entrado en el domino público desde hace mucho, o bien, como suele ser el caso, recurrir a las fotocopias, cuando podrían estar a la disposición de quien las necesita en una base de datos. Otro tanto puede decirse de los libros fuera de circulación o los artículos especializados, que si uno no tiene acceso a la Biblioteca del Congreso en Washington dc mejor haría en suponer que nunca existieron, tan inencontrables y escurridizos resultan. Y ya ni se diga películas o cuadros… <br><br>
  Si se garantizara el acceso a las fuentes (es una discusión pendiente hasta qué punto podría ser gratuito), se rompería al menos con el apabullante elitismo que existe en el acceso a la cultura, que suele estar restringido a gente con recursos o a académicos, y al menos se daría un paso claro para darle cuerpo y contenido al hoy borroso y más bien olvidado derecho a la cultura. Aunque faltaría esclarecer qué se entiende en cada caso por acceso a las fuentes, la idea general sería que el músico interesado pudiera tener en sus manos la partitura de la obra que le interesa, el estudiante de arquitectura contemplar los planos de un edificio, un lector cualquiera descargar el archivo de texto del libro, etcétera. <br>
  
  <h4>Contra la idea de propiedad intelectual </h4>
  <p>
  La propuesta del libre acceso a las fuentes se enfrenta, como es obvio, al inmenso escollo de que la naturaleza de las obras culturales es problemática. Por un lado, tienen un perfil de mercancías, están sujetas a las leyes de la oferta y la demanda, y tanto los autores como, sobre todo, las corporaciones que las comercializan, se benefician de su venta. Pero, por otro lado, tienen también un perfil distinto que las emparienta con los bienes comunes, y pueden ser equiparadas a un regalo o una contribución que el autor hace a la tradición, a la humanidad, o más modestamente, a la lengua o a los amantes de la ópera, o de la historia de los cómics o del cine amateur, etcétera. </p>
  <p>Pese a que la mayoría de las legislaciones del mundo reconocen un derecho de propiedad a los autores o titulares de derechos sobre obras del intelecto humano, el concepto de propiedad intelectual es una generalización tan vasta y simplista que termina por ser confusa y a veces perniciosa, no sólo porque en aras de un núcleo común más bien exiguo entre legislaciones cercanas pero muy distintas, difumina la disparidad entre los derechos de autor, las patentes y las marcas, cuyas leyes se originaron de forma separada y con intereses diferentes, sino porque equipara la propiedad intelectual con cualquier otra forma de propiedad, por ejemplo, con la propiedad de objetos físicos o extensiones de tierra. ¿Es la creación artística o la producción de conocimiento del tipo de cosas que cabe comparar con la compra de un terreno o de una lámpara? </p>
 <p> Antes de que se reconocieran los derechos de autor, las obras artísticas no eran propiedad de nadie, sino que más bien eran patrimonio de todos. No tiene mucho caso repetir que la Ilíada y la Odisea no habrían llegado hasta nosotros si, en contra de su condición de bienes comunes, hubieran sido sometidas a restricciones tanto en lo referente a su circulación como a su transformación y perfeccionamiento. Tampoco tiene mucho caso insistir en que así procede la creación artística también en nuestros días, y que otro tanto puede decirse de la innovación científica y los inventos tecnológicos: a partir de un patrimonio común, de un entramado social complejo en el que por supuesto existe el mérito individual, pero siempre inscrito en una trama de prácticas y tradiciones que lo hacen posible y lo rebasan.<del>3</del> <br><br>
  ¿Lo que sugiero es desaparecer el copyright por consideraciones más bien hegelianizantes, en donde cada creación habría de ser considerada una voluta más del gran magma del espíritu? No exactamente, pero sí que el copyright se someta a examen y a una reforma concienzuda, pues, además de anticuado, está pervertido por la avaricia y el abuso, además de que en el mundo real, pese a la ampliación y el endurecimiento de sus restricciones, está perdiendo la batalla: día y noche en la mayoría de las computadoras caseras del mundo, en las papelerías de la esquina, en los café–Internet, se verifican violaciones a una legislación que no ha sabido reorientarse y ser sensible a las libertades y derechos de los lectores y los usuarios. <br><br>
  Las gigantescas y cambiantes retículas virtuales están haciendo saltar por los aires los demasiado anquilosados convenios internacionales en la materia, y parece que mientras más candados y códigos de acceso, más multas y amenazas se implementan, más rápido crecen, mutan y se adaptan los mecanismos para compartir información entre los amigos, una práctica a la que muchos denominan &ldquo;copia no autorizada&rdquo; y otros más insisten en tachar, con bastante confusión y mala leche, como &ldquo;piratería&rdquo;. <br><br>
  Vista con cierta distancia, esa carrera es por completo desigual: mientras que la legislación del copyright se actualiza y endurece cada cierto tiempo (cada tantos años que se reúnen los organismos internacionales), la retícula de intercambios y libre circulación se desplaza a la velocidad de los megabytes por segundo. Dueños hasta cierto punto de los medios de producción, pero sobre todo dueños de los medios de re–producción como nunca se habría imaginado Marx, los que tenemos la sartén por el mango somos los usuarios. Puesto que las leyes de copyright se enmiendan de espaldas a los lectores y sus derechos, nada más natural que nosotros le demos también la espalda al copyright.<br>
  <h4>
  Un nuevo enciclopedismo </h4>
  <p>
  Durante la Edad Media surgieron proto–enciclopedias (por ejemplo las de Marciano Capella o San Isidoro) que tenían la intención de rescatar la cultura clásica que corría el riesgo de desaparecer con la invasión de los bárbaros. Con intenciones didácticas, construyeron auténticas &ldquo;arcas de Noé del saber&rdquo; que se proponían salvar ¡y lo consiguieron! los restos de cultura de la quemazón bárbara, de los continuos autos de fe de los invasores. Por su parte, durante la Ilustración, la Enciclopedia de D&rsquo;Alambert y Diderot, de la que son herederos casi todos los proyectos enciclopédicos actuales (incluida la Wikipedia), tenía como cometido difundir el saber, propagarlo, de allí que lo que buscaran fuera en primer lugar el compendio, la síntesis y unificación del saber (en la tradición cartesiana, los artículos tenían como dos de sus valores centrales a la claridad y la concisión). <br><br>
  La invasión de los bárbaros hoy adopta otras formas no menos destructivas y terribles para la cultura, por lo que se antoja imprescindible un rescate del tipo que emprendieron Capella y San Isidoro. No es sólo que el imperio del mercado tienda a la homogenización y atente contra la diversidad cultural, sino que literalmente hay una serie de bienes culturales que se están perdiendo, ya sea porque no se reeditan, o porque no hay mercado suficiente, o bien porque los patrimonios son saqueados o están en ruinas, o porque los acervos se incendian, o las guerras a favor de la democracia en el mundo terminan por destruirlos. Con excepción de las novedades y los best–sellers, uno tiene que rascar un rato para encontrar la obra de un autor ni siquiera demasiado marginal u oscuro, y ya no se diga si lo que está buscando es el patrón de los mosaicos en las villas romanas o la trascripción literal de los evangelios apócrifos. <br><br>
  De modo que está, de una parte, la importancia de la conservación frente a la barbarie, por ejemplo frente a la de quienes quieren hacer de las pirámides de Teotihuacan la sede de un espectáculo de luz y sonido. Pero por otra parte, con los medios electrónicos actuales, es posible imaginar un nuevo tipo de enciclopedismo que, a diferencia del de D&rsquo;Alambert, no esté restringido al saber compendiado, a los artículos que difunden el conocimiento, sino que se expanda al acceso directo a las fuentes, entendiéndolas en sentido amplio, como se dice cuando se le pide a un estudiante que vaya a las fuentes, es decir, que lea a los autores directamente y no sólo a sus comentaristas. La idea más ambiciosa sería que se garantizara el acceso a las fuentes de todo lo que se ha producido gracias a una base común, a una tradición cultural viva: patentes de medicinas, partituras de compositores, planos de monumentos, código de software, yacimientos arqueológicos, secuencias de códigos genéticos, y, por supuesto, libros, fotos, videos, etcétera. <br><br>
  Dicho en pocas palabras, el objetivo sería: A) rescatar el espíritu de las proto–enciclopedias medievales, sin que se restrinja a una élite de eruditos y escolásticos, sino que tenga acceso cualquiera que tenga una computadora con Internet, y B) ampliar los postulados del iluminismo y del sapere aude a fin de que, en lugar de andarse por las ramas de la divulgación, se pueda ir directamente a la raíz, a las obras, por lo menos a su correlato virtual. 
  
  <h4>Final ilustrado: la librery(a) de Babel </h4>
 
  Quiero concluir con un breve análisis de la babélica iniciativa de Google Libros, que tiene algo de borgesiano e infinito en su raíz (es lo más cercano a la biblioteca universal de la humanidad), con la cual se pretende digitalizar y poner en línea todos los libros disponibles que ha publicado el hombre, ya sea en copia virtual íntegra o en vista parcial, y hasta hace unos meses con independencia de lo que opinaran los titulares de los derechos de autor. La iniciativa, que de algún modo podría estar en consonancia con esta propuesta de acceso a las fuentes, ha dado lugar a toda clase de interpretaciones sobre sus propósitos: que si en el fondo persiguen el lucro puro y duro, que si son los adalides de lo que se ha dado en llamar &ldquo;la democratización de la cultura&rdquo;, que si se trata de la infracción a los derechos de autor más descarada y sistemática… <br><br>
  El problema de fondo con la iniciativa de Google, más allá de cómo se resuelvan las demandas de derechos que ha recibido en cascada, es que sería una empresa privada trasnacional la que tendría en su poder todo el acervo libresco de la humanidad, con los peligros que ello conlleva en cuanto a su explotación comercial monopólica o, por qué no, la eventual bancarrota del hoy muy firme emporio. Al comienzo, no estaba claro si el proyecto de Google Libros apuntaba hacia una inmensa librería donde se gestionarían libros sobre demanda, o bien hacia una Biblioteca de Babel en el Ciberespacio, de allí que hubiera voces que no sin candidez lo consideraran un gran proyecto altruista. El hecho de que se descubriera que el consorcio de los motores de búsqueda ya tenía listas las imprentas de tirajes cortos para producir ejemplares en cuestión de minutos, y el reciente anuncio, en la Feria de Frankfurt, del lanzamiento de una librería digital en la naciente rama de Google Editions, han despejado el panorama: lo que se está construyendo es la librería (digital y en papel) más grande y variada que se haya conocido jamás. Será apetitosa, sin duda, pero eso no tiene mucho que ver con las expectativas un tanto románticas que había generado, según las cuales, por ejemplo, la literatura por fin circularía libremente en la red. (El caso es que entre biblioteca y librería hay una diferencia sustancial, no importa si creemos que &ldquo;library&rdquo; se traduce como librería.) <br><br>
  Pero una vez que Google ha esclarecido sus propósitos, la idea de esa biblioteca virtual sigue en el aire. La unesco, por ejemplo, ya ha lanzado al ciberespacio una Biblioteca Digital Mundial (www.wdl.org/es) con el objetivo de permitir al mayor número posible de personas acceder gratuitamente, mediante Internet, a los fondos de las grandes bibliotecas del mundo en varios idiomas. Proyectos de esta naturaleza, si fueran impulsados y sostenidos a largo plazo, sin duda crearían un contrapeso al ejército de escáneres codiciosos de Google. <br><br>
  Sin embargo, creo que la creación de una biblioteca de esas características colosales podría realizarse si se emprendiera colectivamente, por todos y para el beneficio de todos (un poco como funciona, desde sus comienzos, el Proyecto Gutenberg: www.gutenberg.org), un esquema en el que todo aquel que esté interesado podría subir a la red, cumpliendo ciertos requisitos en los que haya previo consenso sobre su digitalización, los libros, partituras o revistas que le apasionan y que no están incluidos en la base de datos, de forma que el proyecto se universalizara gracias al compromiso común y, a la vez, su incesante robustecimiento no dependiera de una empresa determinada. Quizá bajo una lógica de participación y mejora en el espíritu del procomún, la biblioteca atraería más y más obras, al alcance de más personas y con la garantía de que no se perdería su accesibilidad. <br><br>
  El acervo podría ser considerable aún si se limitara, por respeto a las legislaciones vigentes en materia de derechos de autor, a obras de dominio público, por un lado, y a obras con algún tipo de licencia copyleft, por el otro; pero ya entrados en materia, no estaría mal que bajo la presión de bibliotecas digitales gestionadas colectivamente, de una vez se sometiera a examen la vigencia del derecho patrimonial (que en México, según decreto de 2003, alcanza los cien años post mortem auctoris, uno de los más dilatados y quizá insensatos del mundo), así como la sospechosa tendencia a incrementar cada tanto ese plazo en beneficio de unos pocos. <br><br>
  El acceso a las fuentes (o lo que quizá se podría llamar &ldquo;el derecho a encontrar lo que buscas&rdquo;), para que sea mínimamente viable ha de construirse de la mano de una revisión de las leyes de derechos de autor y de copyright que no desatienda los derechos de los usuarios, procurando que se logre una conciliación armoniosa y no, como sucede en la actualidad, una fricción que termina en los tribunales. Gracias a Internet, el dominio público podría volverse efectivamente cada vez más público. </p><br><br>

 <p> <del>1 </del>El Artículo 27 de la Declaración Universal de Derechos Humanos (diciembre de 1948) reconoce este derecho, que figura justo antes de los derechos autorales: <br>
1. Toda persona tiene derecho a tomar parte libremente en la vida cultural de la comunidad, a gozar de las artes y a participar en el progreso científico y en los beneficios que de él resulten. <br>
2. Toda persona tiene derecho a la protección de los intereses morales y materiales que le correspondan por razón de las producciones científicas, literarias o artísticas de que sea autora.</p>

<p> <del>2</del>Si bien es uno de los derechos fundamentales del hombre según la ONU, el derecho a la cultura fue aprobado en México apenas el 30 de abril de 2009. La enmienda al artículo cuarto de la Constitución comienza así: &ldquo;Toda persona tiene derecho al acceso a la cultura…&rdquo; </p>

<p><del>3</del> Lawrence Lessing, el fundador de Creative Commons, ha descrito esta forma de producción cultural como &ldquo;remix&rdquo;, en oposición a la cultura del &ldquo;permiso&rdquo;, en la cual, por efectos del copyright, se debe pedir permiso antes de hacer la menor modificación o mejora en las obras. </p>
 
<p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Luigi Amara es un traductor, ensayista y poeta nacido en la Ciudad de México en 1971. Realizó estudios de Filosofía en la UNAM. Fundador y jefe de redacción de la revista <em>Paréntesis</em>. Actualmente se desempeña como jefe de redacción de <em>Pauta</em>. Desde 2005 es director editorial de <em>Tumbona Ediciones</em>. Colaborador de <em>Confabulario</em>, <em>Fahrenheit</em>, <em>Fractal</em>, <em>La Jornada Semanal</em>, <em>La Tempestad</em>, <em>Letras Libres</em>, entre otras. Ha publicado <em>El decir y la mancha</em> (Universidad Autónoma Metropolitana, 1994).
<div> </div>
</div>
</section>
<?php include 'footer.php' ?>