<?php include 'header.php' ?>

<section class="titulo">
	<article class="">
		<h3>Número 74</h3>
		<h1>Fractales quijotianos</h1>
		<h2>Carlos Miranda</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
    <p align="right" style="font-size:13px; margin-bottom:40px;"><em>Tú que cubriste con doble hoja forjada </em><br>
      <em>en el oro más fino el brazo manco </em><br>
      <em>y paupérrimo del viejo Cervantes.</em><br>
      Herman Melville</p>
      
    <p>El 28 de septiembre de 1605, llegó a San Juan de Ulúa una flota de diez navíos que transportaba numerosas mercancías desde Sevilla y Cádiz. Por disposición del rey, un comisario del Santo Oficio debía revisar, lista en mano, cada objeto que ingresaba al Nuevo Mundo, a la caza de libros prohibidos. <em>La Encarnación</em> (2), <em>Nuestra Señora de los Remedios</em> (2) y el <em>San Cristóbal</em> (1) transportaron los primeros cinco ejemplares de <em>El ingenioso hidalgo don Quijote de la Mancha</em> que recibieron el sol americano, todos propiedad de sendos marineros. En la lista del cargamento de libros descollaban cuatro ejemplares del <em>Guzmán de Alfarache</em> (el <em>best seller</em> del momento), dos de <em>La arcadia</em> de Lope de Vega, uno de <em>Las metamorfosis</em> de Ovidio y otro de <em>El </em><em>Çid</em><em> Rui Diaz</em>. El <em>Quijote</em> había sido publicado el 6 de enero de 1605, según documentos de la imprenta de Juan de la Cuesta, en Madrid, y fue editado por Francisco de Robles, con un tiraje de 500 ejemplares. Visto el éxito de la novela, De la Cuesta reimprimió 1,800 copias más.</p>
    <p>La primera novela moderna encontró en los americanos unos lectores naturales que vinieron a construir y habitar la Utopía. Y otro hecho la vincula con México, mencionado tres veces en ella: Cervantes solicitó ser trasladado al Nuevo Mundo en calidad de encomendero, cosa que no sucedió.</p>
    
    <h4 align="center">* * *</h4>
    
    <p>La historia de esta compilación se remonta a 1992, año en que la unam, el Colegio de México y Ediciones del Equilibrista coeditaron <em>La cervantiada</em>, libro compuesto por cuarenta textos de autores hispanoamericanos encargados por el crítico peruano Julio Ortega. Cuando cayó en mis manos, lo encontré muy decepcionante porque buena parte de los textos solicitados parecían responder más que a un proyecto de rigor literario crítico, a un criterio determinado por la conveniente amistad que imponía una laxitud condescendiente con tal de enrolar firmas de alto reconocimiento crítico. Es una obra sin la trascendencia que prometió y, en esa medida, la catalogué como una falta de respeto a la gran novela de don Miguel de Cervantes.<br><br>
      Hacia 2003, el entonces inminente aniversario 400 de la publicación de la primera parte de la novela fundacional en mi formación como lector me inspiró como obligación rendirle un tributo invitando a un grupo de lectores avezados de la obra, cuya fidelidad y devoción me constaban, escritores que se ganan la vida estirando y restirando el idioma, a intentar formar una asamblea conmemorativa y festiva que superase la fársica propuesta de Julio Ortega. Platiqué con varios de los quijoteros, los entusiasmé y a continuación le propuse la idea al director de una importante editorial privada, quien la acogió, y procedí a calcular qué tipo de textos quería para el libro.<br><br>
      La idea inicial fue conformar una colección de textos en donde cada colaborador a partir de su gusto ensayara sobre el que considerase su pasaje o capítulo favorito para ir a donde quisiera en el espíritu de libertad más absoluto del <em>Quijote</em>. Las circunstancias temporales determinaron que algunos se ciñeran a la idea original y otros no. El insospechado resultado fue que quienes hicieron lo primero, al contrastar con los segundos, marcaron una especie de contrapunto que produjo un equilibrio ciertamente extraño, difícil de sostener. Sólo hasta haber recibido el último texto se formaron tres grupos unidos por dos motivos diferentes, pero no lejanos. Sucedió luego que el editor me confirmó su interés en el libro en ¡marzo! de 2005 y, para julio, cuando ya era tarde para seguir esperando colaboraciones, retiró su respaldo. Busqué a otro editor que retomara el proyecto y lo tuviera listo a más tardar en octubre, sin éxito predecible. Todavía consideré y llegué a proponer que si se publicaba en 2006 no perdería oportunidad si el defecto de la impuntualidad se convertía en la virtud de desmarcarse del aluvión de obras conmemorativas de 2005, pero simplemente no fue posible. Tenía en mis manos una docena de textos magníficos sin posibilidades de publicarlos juntos. A finales de 2005 y durante 2006, tuve al tanto a los autores de lo no sucedido y, con una generosidad inaudita para mí, todos me &ldquo;donaron&rdquo; los textos hasta que consiguiera editor. Yo mismo les ofrecí que si deseaban publicarlos en alguna revista o suplemento, no dudaran en hacerlo para que obtuviesen una remuneración que me era imposible erogar.<br><br>
      El tiempo no era detenido por una oferta tangible de ningún editor y, como broma, empecé a decir que no iba a cejar hasta que el libro existiera, así tuviese que esperar a 2014, cuando se festejara el aniversario 400 de la segunda parte.<br>
      En 2013, para evitar que se repitieran las circunstancias de 2005, ofrecí el proyecto a una instancia estatal, la Dirección General de Publicaciones de Conaculta. A finales de ese año coincidí con Ignacio Padilla, notable estudioso de la obra cervantina, y le hablé de mi proyecto. Como editor de la Universidad Iberoamericana, ofreció coeditar con Conaculta y no había más que plasmar todo en un contrato. Volví a buscar a los editores del cnca y, con entusiasmo, me pidieron que les hiciera llegar el material para revisarlo. Sigo esperando su opinión, aunque aseguraron participar de entrada.<br><br>
      Llegado 2014, reparé en que mi última oportunidad se desvanecía y sólo me iba a quedar el recurso de publicar el libro, con más textos a encargar en un plazo no mayor a seis meses, y alrededor de marzo o abril conversé con Ilán Semo, director de la revista <em>Fractal</em>, quien ya me había publicado generosamente unas traducciones, y le conté, al acaso, la historia que llevo resumida. Ilán es un hombre entusiasta que hace <em>Fractal</em> para dar relevancia al agonizante género del ensayo y me propuso dos acciones a seguir: publicar el libro en 2016 con motivo del cuarto centenario de la muerte de Cervantes, y armar un <em>dossier</em> para la revista que anticipe el rescate del proyecto. Infortunadamente, el espacio disponible nos obligó a depurar; primero, dejamos afuera los textos que publicaron los autores en otros espacios; después, los textos fueron sometidos a la evaluación de un consejo editorial que no supo los nombres de los autores y, por último, la redacción de la revista hizo una selección final.<br><br>
      Vale decir, pues, que en esta entrega de <em>Fractal</em> no están todos los que son ni son todos los que hay. Es necesario enfatizar que el conjunto de textos que se presentan aquí constituyen un adelanto, una muestra variada del contenido del libro que habrá de publicar de forma íntegra <em>Fractal</em>, en sus colecciones de libros, en 2016.<br>
      En lo personal, considero el concepto de homenaje, igual que el de tolerancia, una ofensa. Es decir, el resultado final de nuestra convocatoria aspira a ser un festejo, primero, y una nueva invitación a repensar la trascendencia de <em>El ingenioso hidalgo don Quijote de la Mancha</em>, novela escrita y publicada hace más de cuatro siglos con enorme éxito y difusión, tanto que dio pie a que varios escritores de aquel Siglo de Oro, el segundo de la península ibérica, escribieran secuelas y replanteamientos. Ejemplos como el famoso de Avellaneda, tan inquietante para un Cervantes diez años más viejo que no pudo contener su propio ánimo de desfacer entuertos y volvió a salir al terruño editorial, como el Quijano o Quezada que se siente tan agraviado que cobra conciencia de que es un personaje ficticio instalado en la realidad, o viceversa, y pone en su lugar a la realidad y la ficción para ordenar un cosmos que puede ser alterado por los farsantes que, sin entender nada, sin capacidad de empatía, descomponen la ética, la estética y la cosmética del arte al que la irrealidad le confiere verosimilitud y viceversa de nuevo.<br><br>
      Como misterio ulterior del <em>Quijote</em>, no se me ocurre una duda mayor sobre la postura y visión de Cervantes respecto a su obra en el mo­mento en que determinó que debía escribir una segunda parte. Si hay un portento difícil de elucidar o apenas elucubrar, es de qué estaba hecho Cervantes para emprender la escritura de una segunda parte que iba a poner de cabeza la capacidad de invención propia de un genio que sabe lo que hace. Los mortales que admiramos ese trabajo tendemos a creer, sin atrevernos a afirmarlo, que la grandeza del <em>Quijote</em> no sería tal sin la segunda parte, sin implicar o siquiera insinuar que la primera bien basta para situarla entre las mayores escritas en lengua castellana.<br><br>
      La trascendencia del <em>Quijote</em>, nuevamente, es la idea de este libro subrayarlo, sucede primero en el espíritu del lector. Yo lo leí por primera ocasión a los quince años, por curiosidad. Tengo ese hecho en la misma valía que mi primera borrachera, a la misma edad. El <em>Quijote</em> produce una borrachera de por vida. Si la tradición entre los quijotistas implica leer la novela una vez al año, ¿cuántos cientos de miles o millones de borracheras ha suscitado el libro en más de 400 vueltas al Sol? Marea pensarlo.</p>
<p>&nbsp;</p>
      
<p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Carlos Miranda nació en la Ciudad de México en 1962. Realizó estudios de Ciencias Políticas y Periodismo en la UNAM. Ha sido editor de las revistas Casa del Tiempo, Tierra Adentro, Textual, El Periódico de Poesía y el Boletín del Archivo General de la Nación. Ha colaborado desde 1984, con ensayos, reseñas, cuentos, entrevistas y traducciones, en los principales suplementos y revistas del país. Es autor de los libros de cuentos Noches de paz (Ediciones del Equilibrista, col. Tramp Steamer, 1997) y Siempre es peor en noches de paz (DGP Conaculta, 2013). cmiranda1962@gmail.com
</div>
</section>
	
<?php include 'footer.php' ?>
