<?php $title = 'Gerardo de la Torre - El puente y el río | Revista Fractal'; ?>

<?php include 'header.php' ?>

<section class="titulo">
	<article class="">
		<h3>Número 74</h3>
		<h1>El puente y el río</h1>
		<h2>Gerardo de la Torre</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
<p></p>
    <p>Muy temprano, antes siquiera de aprender a leer, entré en relación con Cervantes y don Quijote de la Mancha, aunque no con Sancho, a quien conocí cuando terminaba yo la primaria y me encantó por su peculiar locuacidad. Aquel primer contacto se dio por mediación de mi padre (que no era hombre de letras ni criatura semejante). Huérfano por el lado paterno, desde 1910, cuando cumplió seis años comenzó a encargarse de su educación el ilustrado sacerdote Daniel Somohano, párroco en algún rincón del sur de Veracruz.<br><br>
      Gracias a las lecciones del cura, mi padre aprendió a leer, escribir, hacer cuentas y tocar el violín; más tarde estudió una carrera comercial que incluía contabilidad, inglés y artes taquigráficas y mecanográficas. Como una de sus obligaciones era ayudar en misa, aprendió latines que revivía en su vejez (murió a los 91 años). Y algo que aún recordaba al final de sus días —aunque había olvidado el nombre de sus hijos e incluso este parentesco—, era el primer capítulo de <em>El ingenioso hidalgo</em>, que el padre Somohano le había hecho aprender de memoria. Anciano ya, de pronto mi padre clavaba la mirada en el techo y se ponía a recitar algo como &ldquo;se le pasaban las noches leyendo de claro en claro, y los días de turbio en turbio; y así, del poco dormir y del mucho leer se le secó el celebro, de manera que vino a perder el juicio&rdquo;.<br><br>
      Comencé a leer el <em>Quijote</em> allá por el año 1948, en un ejemplar que pertenecía a mi madre. Era un volumen pesadísimo, de unas 800-900 páginas, pasta dura, papel grueso y satinado, de un tamaño que hoy se denominaría cuarto marquilla. No hice en aquellas aproximaciones una lectura íntegra sino parcial, pues sólo tragaba enteras las partes que me entretenían, que me provocaban risa, sobre todo las efusiones de refranes de Sancho que tanta cólera provocaban al principio en el hidalgo.<br><br>
      La primera lectura formal de la novela entera la hice una década después, cuando ya me había nacido una imprecisa vocación narrativa. De entonces a esta parte he leído en su totalidad el <em>Quijote</em> lo menos unas quince veces; en la década de 1990, por ejemplo, me jactaba de leerlo una vez por año. Llegué así a conocer con cierta profundidad los valores de la novela y a retener aceptablemente buena parte de los incidentes de casi todas las andanzas del Caballero de la Triste Figura.<br><br>
      Resulta impresionante que una novela vieja de cuatrocientos años suene tan fresca como si hubiese sido escrita hace unos cuantos lustros. La fuente de tal frescura, me parece, se halla por una parte en la sólida y natural relación que logra establecer Cervantes entre dos personajes de características tan opuestas; por otra parte, en una comicidad que se apoya lo mismo en las situaciones —producto de la transitoria obnubi­lación de don Quijote y la ingenuidad y la socarronería de Sancho— que en el humor verbal resultante las más de las veces de la confrontación de la ignorancia del escudero con la erudición del hidalgo.<br><br>
      Una vez publicada la primera parte del <em>Quijote</em> en 1605 por Juan de la Cuesta, no demoraron los críticos en señalar como imperfección grave (al margen de buen número de olvidos y descuidos) la intercalación de relatos ajenos a los personajes y su trayectoria —&ldquo;El curioso impertinente&rdquo; en primer término—, que sólo interrumpían el flujo narrativo; aun así cabe defender ese recurso como un artificio usado para ejemplificar maneras de contar distintas de las empleadas por el autor, quien, como es evidente, gozaba de amplios conocimientos en materia narrativa; para probarlo basta con atender a los juicios vertidos en el escrutinio realizado por el cura y el barbero. De otra parte, Alonso Fernández de Avellaneda, nombre que encubre al enigmático autor del <em>Segundo tomo de don Quijote de La Mancha</em> (edición conocida como &ldquo;Quijote apócrifo&rdquo;), arremetió también contra Cervantes al mencionar los yerros presentes en la primera parte.<br>
      Nada tarde, Cervantes, a partir de la dedicatoria de la segunda parte al conde de Lemos, no perdió ocasión de ridiculizar el falso Quijote y de insistir en que los únicos auténticos eran el caballero y el escudero de su invención. Esta segunda parte apareció en 1615 (impresa también por Juan de la Cuesta) con el título de <em>El ingenioso caballero don Quijote de la Mancha </em>(caballero, y no hidalgo, seguramente para que no se confundiera con la edición apócrifa de Fernández de Avellaneda publicada un año antes con el título <em>Segundo tomo del ingenioso hidalgo don Quijote de la Mancha</em>) y en 1617 las dos partes se publicaron juntas en Barcelona.<br><br>
      Por encima de aquellas lamentables inquinas, hay que destacar la resonancia de esta obra mayor de Cervantes. El año mismo de su publicación se hicieron dos ediciones más en Madrid, otras dos en Lisboa (piratas ambas) y dos autorizadas en Valencia. Siguieron dos ediciones en Bruselas (1607 y 1611), una más en Madrid (1608) y una en Milán (1610); de la segunda parte se hicieron reimpresiones en Bruselas y en Valencia en 1616 y en Lisboa en 1617. La traducción al inglés de la primera parte, realizada por Thomas Shelton, apareció en 1612, y en 1620 vio la luz la continuación. En el mismo siglo xvii hubo traducciones al italiano, el alemán y el holandés; en el xviii se conocieron las versiones danesa, polaca, portuguesa y rusa, y durante los siglos xix y xx el<em> Quijote</em> fue traducido a prácticamente todas las lenguas que gozan del privilegio de la impresión.<br><br>
      La segunda parte del <em>Quijote</em> comienza justamente donde dejó al personaje la primera (si bien no respeta el itinerario previsto, pues el hidalgo no se dirige, como el apócrifo, a Zaragoza sino a Barcelona) y sin embargo parecería que en el todo, si se atiende a la técnica y los recursos narrativos, hay dos novelas o cuando menos dos autores (resulta curioso, pero la segunda parte tramada por Avellaneda se parece más en tono y estilo a la primera que la segunda de Cervantes).<br><br>
      En efecto, la primera parte, de principio a fin, se propone ser una parodia devastadora de los libros de caballerías: así lo afirma, drástico, el autor en el prólogo. En ella quiere Cervantes, nada más, contar la historia de un hidalgo a quien de tanto leer novelas de caballerías se le secó el cerebro —esto es, enloqueció— y en su delirio logra arrastrar a un simplón y lo lleva a correr descabelladas aventuras. El genio de Cervantes, por fortuna, no se limitó a contar la historia sino que supo crear dos personajes de rotunda fortaleza: el idealista dispuesto a deshacer entuertos y capaz de descubrirlos en la más inocente circunstancia cotidiana (el paso de un rebaño, los giros de un molino de viento), y el zafio y crédulo campesino —cuyo sentido práctico no parece chocar seriamente con los delirios del amo— que se deja seducir por las fantasías del instruido hidalgo.<br><br>
      En la segunda parte, al lector ya no le interesa el desenlace de la historia planteada y a medias resuelta en la primera mitad. Lo que quiere es acompañar en su trayecto a esos dos personajes cada vez más definidos y cargados de gracia y complejidad, y admirarse y deslumbrarse con cada nueva aventura que se les presente y con los razonamientos que de ella se deriven.<br><br>
      En esta tercera y última salida de don Quijote, optó Cervantes, para no despeñarse de nuevo en los defectos señalados por sus críticos, por prescindir de la inclusión de historias ajenas a los personajes, que sólo conseguían interrumpir el flujo narrativo. Sin embargo la novedad, lo que hace al <em>Quijote</em> verdaderamente peculiar —y según algunos le otorga la distinción de inaugurar la modernidad— es el hecho de que los personajes, asumiéndose como seres de la realidad, co­mentan su presencia en un libro de corte biográfico escrito por el moro Cide Hamete Benengeli y traducido por un cristiano; se trata de la primera parte del <em>Quijote</em>, de la cual les ha llevado noticia el bachiller Sansón Carrasco (personaje que más tarde tendrá dos intervenciones importantes). Sancho muestra espanto de que el autor de la historia sepa tanto de ellos y don Quijote lo tranquiliza afirmando que debe tratarse de cosa de algún encantador. Más tarde, Cervantes, en voz del caballero andante, asume de manera magistral el yerro de incluir relatos forasteros cuando pone al hidalgo a decir: &ldquo;…y no sé yo qué le movió al autor a valerse de novelas y cuentos ajenos, habiendo tanto que escribir en los míos&rdquo;.<br><br>
      En cuanto a la calificación de primera novela moderna, habría que echar la de Cervantes a disputar con el anónimo relato <em>La vida del l­azarillo de Tormes</em>, que cincuenta años antes de la aparición del <em>Quijote</em> se atrevió a desafiar el canon de la literatura de su tiempo y a presentar —en modernísima primera persona, enviando al desván al narrador omnisciente con toda su omnisciencia y sepultando de paso el artificio del polvoriento manuscrito hallado en un arcón— un retrato certero de los malvivientes de su tiempo, los pícaros. Pero esto, finalmente, no le resta méritos a la novela de Cervantes, y lo que me corresponde es enaltecer, a título de antojo personal y sin menoscabo de otros, cierto episodio o ciertos episodios de <em>El ingenioso hidalgo</em>.<br><br>
      Señalé al principio que muy temprano me sedujo el habla de S­ancho, su locuacidad disparatada. Y aún hoy, cada vez que abro la novela busco un diálogo de Sancho para disfrutar de esa poderosa relación entre el personaje y su expresión oral. El <em>Quijote</em> es esencialmente una narración humorística —aunque rebase con mucho la mera idea de entretener—, y buen número de los mejores pasajes cómicos se deben a la verborrea de Sancho (&ldquo;Señor, ¿quiere vuestra merced darme licencia que departa un poco con él? Que después que me puso aquel áspero mandamiento del silencio, se me han podrido más de cuatro cosas en el estómago…&rdquo;, suplica el escudero, ávido de hablar, en el capítulo xxi de la primera parte, luego de la aventura de los batanes, en que fue castigado por hacer burla de su amo), si bien la mayor parte proviene de la estirpe de la comedia de situaciones, creados casi todos estos trozos por la alucinosis de don Quijote.<br><br>
      Las digamos cerca de mil páginas de <em>El ingenioso hidalgo</em> se hallan colmadas de acaecimientos novelescos de primer orden, tan ingeniosos unos como otros. Así, es difícil inclinarse por un episodio en particular, igual que lo sería elegir favorito entre don Quijote y Sancho (quizás optásemos por el idealismo y la bizarría del caballero andante, pero al hacer a un lado a Sancho disminuiríamos sin duda la figura del otro). Un recorrido rápido nos ofrece el escrutinio que hicieron el cura y el barbero, la aventura de los molinos de viento y la ya dicha de los batanes, la batalla con los cueros de vino, el descenso a la cueva de Montesinos, el episodio de los leones, el desaguisado de las Cortes de la Muerte y el otro con los disciplinantes, el viaje a lomo de Clavileño, la aventura de los rebaños, la historieta del mono adivino, el encuentro con Roque Guinart y sus bandoleros camino de Barcelona, en fin.<br><br>
      Yo me quedo con lo acontecido a Sancho en la ínsula Barataria, asunto que Cervantes resuelve alternando sus capítulos con los que incumben a don Quijote en el castillo de los duques. Mi elección tiene que ver a la vez con los aspectos humorísticos del tramo escogido y con cierta intención social y satírica expresada en el hecho de que un gañán sin instrucción gobierne y administre justicia con tanta sagacidad y sapiencia como el más capaz de los letrados.<br>
      En el territorio de lo cómico, la hora de comer, por obra del doctor Pedro Recio de Agüero, que no le permite a Sancho probar siquiera las espléndidas viandas que le sirven, se convierte en tortura para el pobre gobernador y en motivo de gran regocijo para los que se encargan de la burla. Mas a la hora de gobernar, dice Cervantes, &ldquo;ordenó cosas tan buenas, que hasta hoy se guardan en aquel lugar y se nombran <em>Las constituciones del gran gobernador Sancho Panza</em>&rdquo;. Lo más sonado, sin embargo, son las resoluciones y sentencias del escudero llegada la hora de juzgar. Varios son los casos que le presentan y en cada uno dictamina con acierto, de modo que sus falsos súbditos &ldquo;quedaron todos admirados, y tuvieron a su gobernador por un nuevo Salomón&rdquo;.<br><br>
      El de mayor dificultad se le plantea al final de su gobierno y es, de todo el <em>Quijote</em>, el episodio que más me satisface. Cuenta que había un puente sobre un río y más allá del puente, una horca. El dueño del río y del puente había puesto una ley que estipulaba que quien quisiera pasar el puente tendría primero que jurar adónde y a qué iba, y si decía verdad, podría pasar, pero si decía mentira, moriría en la horca. Sucedió que le tomaron declaración a un hombre y juró que se dirigía a morir en la horca que allí estaba. Y reflexionaron los jueces: &ldquo;Si a este hombre le dejamos pasar libremente, mintió en su juramento, y, conforme a la ley, debe morir; y si le ahorcamos, él juró que iba a morir en aquella horca, y, habiendo jurado verdad, por la misma ley debe ser libre&rdquo;.<br><br>
      El problema, que parece insoluble, lo resuelve Sancho de manera magistral. Puesto que tan válidas son las razones para condenar al hombre como para absolverlo, sentencia &ldquo;que le dejen pasar libremente, pues siempre es alabado más el hacer bien que mal&rdquo;. Y para acrecentar su mérito, aunque parezca menoscabarlo ante el de su señor, indica que no ha pensado tal solución por sí mismo, sino que le vino a la memoria un precepto que le dio don Quijote la noche antes de que partiese a gobernar la ínsula, &ldquo;que fue que cuando la justicia estuviese en duda, me decantase y acogiese a la misericordia&rdquo;.<br><br>
    Y esto, en los tiempos que corren, no es cosa irrisoria.</p>
<p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Gerardo de la Torre es escritor, narrador y crítico literario. Nació en Oaxaca, Oaxaca, en 1938. Estudió teatro con Carlos Ancira y Rodolfo Valencia. Formó parte del taller literario de Juan José Arreola. De 1953 a 1972 trabajó como mecánico de refinería. Fue un miembro del Partido Comunista Mexicano. Ha colaborado en Revista Mexicana de Cultura, Unomásuno, El Universal, El Nacional, Novedades y Excélsior. Desde 1994 pertenece al Sistema Nacional de Creadores. Entre sus libros se cuentan <em>Ensayo general</em> (1970), <em>Relatos de la vida obrera</em> (1988), <em>Tobalá y otros mezcales oaxaqueños</em>(1998), <em>Nieve sobre Oaxaca</em> (2010) y <em>La muerte me pertenece</em> (2015).
</div>
</section>

<?php include 'footer.php' ?>

