<?php include 'header.php' ?>
<section class="titulo">
	<article class="">
		<h3>Número 72</h3>
		<h1>Cuando el sentido deja de hacer mundo*
</h1>
<h4 style="color:#ccc; font-weight:100; font-size:16px;">Entrevista con Michaël Foessel,
Olivier Monguin y Jean-Luc Thébaud
</h4>
		<h2>Jean Luc Nancy</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
<span></span>
<p><em>Como pensador de la deconstrucción, junto con Jacques Derrida y Philippe Lacoue-Labarthe, Jean-Luc Nancy nunca ha abandonado la cuestión del sentido. Durante los años sesenta, exploró en las columnas de la revista </em>Esprit <em>el resquebrajamiento de las categorías tradicionales del pensamiento, sin renunciar no obstante a involucrarse. Desde esa época, en la que colaboró regularmente en la revista, Jean-Luc Nancy aborda el sentido confrontándolo con aquello que lo cuestiona profundamente. Y desde ese momento, se cruza con el nihilismo en la figura de su mayor profeta.</em> <br><br>
  <em>Si bien se aleja del cristianismo, el filósofo no deja de interrogar los actos y las significaciones que abarcan lo religioso. Jean-Luc Nancy no le teme a las palabras, incluso cuando éstas tienen una historia amplia, meditando por ejemplo sobre lo &ldquo;común&rdquo;, la &ldquo;comunidad&rdquo; y sobre el &ldquo;comunismo del pensamiento&rdquo;. Pasa lo mismo con la palabra &ldquo;sentido&rdquo;, que con frecuencia es reducida al vestigio de una metafísica imprecisa o bien a un elemento lógico.</em><br><br>
  <em>Durante sus años de docencia en la Universidad de Estrasburgo (1968-2004), Jean-Luc Nancy situó una pregunta en su trabajo de manera insistente: ¿cómo abordar el sentido de manera que resulte algo que viene, y no como algo que advino? El sentido desbarata nuestras expectativas en lugar de satisfacerlas, por lo que es preciso no renunciar a su clausura. Es decir, el sentido se acerca al mundo como horizonte abierto a los acontecimientos que ningún saber permite anticipar.</em></p>
<p><em>En la presente entrevista volvemos sobre esta articulación del sentido y el mundo, tal vez perdida para nosotros, y sobre el vínculo conflictivo entre el pensamiento del desobramiento [désoeuvrement] y el nihilismo.</em></p>
<p>Esprit:<em> En los diagnósticos hechos sobre el periodo contemporáneo e incluso sobre la modernidad, ¿le parece necesario distinguir entre decadencia, declive y nihilismo? ¿Existe una plusvalía del término nihilismo en relación con todos los discursos de lamentación? ¿Y en relación con qué idea del &ldquo;orden&rdquo; y del &ldquo;sentido&rdquo; se posiciona el nihilismo?</em></p>
<p>Jean-Luc Nancy: El nihilismo ciertamente posee un carácter positivo en relación con las ideas de decadencia o degradación. Éstas presuponen un estado anterior mejor. Ahora bien, la añoranza del estado anterior es tan antigua como Occidente. La Edad de Oro es una invención griega. Sólo entre los judíos no existe la Edad de Oro, ya que el estado anterior fue el esclavismo. El retorno de la lamentación por lo anterior es una gran constante en nuestra historia. Ya se ha dicho demasiado, pero jamás se logra superar. Yo mismo, en forma totalmente involuntaria, tuve el sentimiento de que antes era mejor, pero estoy prácticamente obligado a trasladar dicho sentimiento hasta antes del siglo xix… Si admitimos esto es porque tal vez no se puede hablar ya ni siquiera de una decadencia. El nihilismo, una palabra del siglo xix precisamente, tiene la ventaja de no hablar de un antes, al parecer. Al mismo tiempo, este &ldquo;antes&rdquo; no desaparece del todo, ya que si decimos que no hay nada, se supone que pudo haber algo. Cuando en los siglos xvii y xviii se preguntaban &ldquo;¿por qué hay tal cosa en lugar de nada?&rdquo;, el nihilismo decía: &ldquo;no hay nada donde se sigue creyendo que debe haber algo&rdquo;, algo relacionado con los valores.</p>
<h4>El agotamiento del sentido</h4>
<p>En Nietzsche, el nihilismo, al que califica como el &ldquo;desmoronamiento de los valores supremos&rdquo;, está relacionado con la muerte de Dios, que significa la refutación del Dios moral, de un Dios como valor, garante de los valores y de su propia posibilidad. Yo incluso estaría tentado a reemplazar valores por &ldquo;sentido&rdquo;, ya que el sentido remite al valor por lo que vale en relación con aquel al que se lo comunica. Por eso en lingüística se habla del &ldquo;valor&rdquo; de una palabra.<br><br>
  La muerte de Dios es, por supuesto, también una referencia al &ldquo;antes&rdquo;. No se trata de un invento de Nietzsche, sino del resultado lógico del desarrollo de toda la filosofía moderna, cuando menos desde Duns Escoto y el nominalismo. En realidad, se puede decir que es lo que comienza con la gran escolástica y la asimilación de Dios al Ser supremo, es decir, la metafísica en el sentido de Nietzsche o de Heidegger. Ahora bien, la historia de toda la filosofía moderna no hace otra cosa que mostrar aquello que desemboca perfectamente en la crítica kantiana de la prueba ontológica. El Ser supremo se descompone él mismo muy conscienzudamente en Descartes, Spinoza, Leibniz, incluso en Malebranche. Kant, de alguna manera, termina el trabajo, y lo único que hace Nietzsche es ratificarlo.<br><br>
  La muerte de Dios es por tanto la destitución del Ser supremo, es decir, la destitución de algo representado como un ente o una persona en la cima del orden del mundo —lo cual supone un orden del mundo—. Así pues, resulta lógico que la destitución de ese Ser acompañe el movimiento más global del cuestionamiento de los órdenes posibles del mundo. El mundo de la Antigüedad, el mundo en el que aparecieron los griegos y los romanos, era un mundo que surgía a partir de la desaparición de los grandes órdenes cósmicos religiosos. Lo que se denomina filosofía se inscribe sobre todo en esta ausencia de orden.<br><br>
  El agotamiento del sentido es por tanto de cierta manera la actualización de aquello de lo que es su sentido, de aquello que le hemos hecho a partir del momento en que lo que era un mundo ordenado o susceptible de serlo, se estremeció. Pero este agotamiento no sucedió una sola vez, sino que empezó desde la historia de la Antigüedad. Con frecuencia se piensa la Antigüedad como un todo no histórico. Ahora bien, el milagro griego, si tuvo lugar, fue muy rápido. La democracia ateniense nunca gozó de buena salud. Una vez que terminaron las Guerras Médicas, las cuales dieron la impresión de que Grecia era un conjunto consolidado, las cosas empezaron rápidamente a dispersarse. En el siglo ii a. C., el estoicismo y el epicureísmo manifestaron el deterioro y el fracaso de dicho &ldquo;milagro&rdquo;, de lo cual Nietzsche será, más adelante, un testigo vehemente.<br><br>
  Roma, por el contrario, logra algo que jamás se repitió: la instauración completamente humana y totalmente religiosa del orden. Pero se trata de una religiosidad que es cívica, el único ejemplo por otra parte de religión civil que haya tenido lugar verdaderamente. Sin embargo, ésta también vacila en un momento dado. Es ahí donde, tal vez, el nihilismo tiene sus raíces. Todo sucede como si Roma no hubiera tenido la energía para resistir, lo cual es comprensible si consideramos que Roma es la primera modalidad de un mundo. Es decir, es a la vez un Estado y un pueblo que necesita fabricar su propia historia para mantenerse a flote. Eso funciona de tal manera que Roma &ldquo;hace mundo&rdquo; como ningún imperio lo había hecho antes. Los egipcios, los sirios, los hititas nunca fueron contemporáneos de los alcances técnicos de los que se beneficiaron los romanos, herederos de las grandes revoluciones técnicas, de la escritura, del hierro y de los medios de navegación. Es lo que comprendí leyendo <em>Antonio y Cleopatra</em> de Shakespeare. Cuando Cleopatra le dice a Marco Antonio &ldquo;eres el amo del mundo&rdquo;, es sin duda alguna la primera vez que se le dice eso a alguien en la historia de la humanidad.<br><br>
  Un mundo se creó y ese mundo —que es a la vez mundialidad y mundanidad— provoca una especie de baja de tensión. Como dice un historiador alemán citado por Freud en su Moisés, a partir del siglo ii a. de C., &ldquo;parece que una gran tristeza se apoderó de todos los pueblos del Mediterráneo&rdquo;. Es una frase extraña, viniendo de un historiador, pero es difícil no compartir dicha afirmación, ya que corresponde al periodo del estoicismo, el epicureísmo, el cinismo y al de las búsquedas religiosas más frenéticas (Isis, Orfeo…).</p>
<p><em>En el siglo xix, Nietzsche hablará también, a propósito del nihilismo, de la tristeza europea, de una &ldquo;gran fatiga&rdquo;. Como si se tratara nuevamente de una forma de decadencia del Imperio Romano. Nietzsche nunca perdonó al cristianismo por haber deshecho Roma. En cierta manera, retoma el ataque contra el cristianismo que ya se le había hecho a san Agustín: el cristianismo fue el que disolvió los vínculos de la religión cívica. Pero volvamos a la fórmu­la &ldquo;amo del mundo&rdquo;. ¿Usted la entiende como &ldquo;amo del sentido&rdquo;? Usted escribe, en</em> Le sens du monde, &ldquo;<em>ya no hay sentido del mundo&rdquo;. ¿Cuándo se perdió ese sentido? ¿Tiene relación con la idea del cosmos instituida por los hombres en Roma?</em></p>
<p>El mundo romano, al hacer mundo, produjo algo que jamás había tenido lugar, precisamente la equivalencia entre sentido y mundo. El mundo es la totalidad organizada por los hombres, es decir, Roma, su poder, su derecho. El derecho es muy importante porque el derecho romano representa el sentido como articulación, esa articulación que parece bastarse a sí misma, que es el orgullo de Roma y que se mantiene gracias a cierto número de sustentos religiosos. Porque el derecho romano es religioso de origen, en esa medida es un avatar de la religión entendida como proveedora de sentido. Pero ahí donde la religión provee dicho sentido en relación con un aspecto oculto del mundo, el derecho no tiene ya ningún aspecto oculto. ¿En nombre de qué existe el derecho? Aldo Schiavone muestra perfectamente las fisuras que se producen cuando la pérdida de la referencia religiosa se vuelve cada vez más clara. Se observa lo mismo en el dominio del saber, que entre los romanos es primero que nada un saber técnico, desprovisto de todo misterio.<br><br>
  El cristianismo aparece entonces necesariamente como un producto de la insatisfacción de ese mundo que sabe cómo hacer (el derecho, las fortalezas, los caminos), pero que carece de un aspecto oculto. Así, la muerte se vuelve un problema y la influencia del judaísmo se hace sentir. Puesto que el judaísmo es otro tronco, otro germen dedicado a deshacerse de los órdenes del mundo, se trata de un gran intento por sustraerse de la dominación humana, sobre todo mediante la ruptura con el sacrificio.<br><br>
  A diferencia de lo que dice René Girard, yo no creo que el sacrificio pertenezca exclusivamente al orden de la violencia, de la purificación mediante el chivo expiatorio. El sacrificio establece un vínculo, establece lo sagrado. Dicho vínculo se construye con el aspecto oculto, con la muerte: se mata a un ser vivo para estar en relación con el mundo de los muertos.<br><br>
  En ocasiones he pensado hacer una tipología de las culturas y de las civilizaciones en función de su relación con los muertos (y no con &ldquo;la&rdquo; muerte). Para las culturas llamadas &ldquo;primitivas&rdquo;, los muertos están en alguna parte, están ahí, en la naturaleza, están presentes; tienen su altar, hay que apaciguarlos, ofrecerles sacrificios. En la Antigüedad, los muertos eran sombras errantes, desgraciadas, inconsistentes, a las que no se sabía situar.<br><br>
  Así, en un mundo en el que los muertos se han vuelto no se sabe qué, al mismo tiempo sombras y figuras ancestrales adoradas, la tristeza aparece también en relación con esos muertos con los que no se sabe bien qué hacer (ni tampoco hoy en día…). El cristianismo se anuncia y habla de otra vida, de una resurrección que descansa en realidad en una idea proveniente del judaísmo, que es la del fin de la preocupación, creado por la Alianza. En efecto, creo que la Alianza es más importante que la Ley, ya que no está amenazada por la muerte de Dios. La Alianza significa lo que llegará a ser, en el cristianismo, el perdón de los pecados. Ahora bien, el pecado es algo absolutamente inédito, completamente solidario con la subjetividad, ella misma solidaria con la ruptura completa del orden del que hablamos. Puesto que ya no hay ningún orden, tengo un yo. Agustín fue realmente necesario después de Juan y Pablo para crear el cristianismo. Porque él dice que el hombre se ha vuelto un sujeto que tiene en sí, por sí mismo, una relación con algo infinitamente más grande y distinto que él.</p>
<h4>¿Por qué triunfó el cristianismo?</h4>
<p><em>Usted dice que la única experiencia en la que el sentido hizo mundo y el mundo hizo al sentido de forma cerrada fue Roma. El cristianismo deshizo esta identidad, en detrimento del mundo y en beneficio del sentido. La frase &ldquo;ya no hay sentido&rdquo; aún no ha sido pronunciada, podría decirse en cambio &ldquo;el sentido estuvo aquí&rdquo; (por la Encarnación) y &ldquo;está por venir&rdquo; (por el retorno de Jesucristo). Pero ¿no se podría pensar que la nada que se abate sobre el mundo es ya la obra del cristianismo? ¿El nihilismo no tiene relación con esta desmundanización del sentido?</em></p>
<p>Sí y no. En <em>El Anticristo</em>, Nietzsche recuerda que el cristianismo es el perdón de los pecados, es decir, el fin de la condición de pecador, de la condición de aquel que no reconoce el orden y que es remitido a la subjetividad, ya que está en posición de poder juzgar. Ser salvado es ser redimido de los pecados, es precisamente no querer ya instaurar el mundo por sí mismo y a su medida. En el fondo, lo más importante es decirse que nunca nadie pensó, en sentido estricto, que el hombre fuera la medida de todas las cosas. Ni los griegos, ni los judíos, ni los cristianos. Pero al mismo tiempo, todo ocurrió como si el hombre fuera, debiera ser y se fuera a convertir en la medida de todas las cosas, incluido él mismo. Devino su propio productor, como decía Marx.<br><br>
  Las dos cosas se produjeron casi juntas, pero no obstante, no fue el cristianismo el que hizo explotar ese mundo sino que ese mundo explotó &ldquo;en&rdquo; cristianismo porque no logró sostenerse. Esto se muestra bien en <em>Quand notre monde est devenu chrétien</em> de Paul Veyne. Ese libro me iluminó. Paul Veyne, que no es cristiano, es el primero que respondió a una pregunta que he formulado no sé cuántas veces: ¿por qué el cristianismo triunfó? Veyne dice que Constantino no utilizó en lo absoluto alguna estrategia de oportunismo político. Contaba con un entorno intelectual de gran calidad que le mostró que lo que decían los cristianos era sin duda alguna lo que era mejor para remediar la tristeza. Así pues, se trataba antes que nada, de un movimiento intelectual, espiritual, de comprensión.</p>
<p><em>Le hacía falta consolación a ese mundo que hacía sentido y que sin embargo ya estaba muerto. Tal es la contribución del cristianismo…</em></p>
<p>Fue la solución más poderosa, solución quizá demasiado poderosa. Es lo que precipitó, tal vez, el fin de Roma, pero también el devenir del imperio de la cristiandad. No se debe comprender como un nefasto accidente. Hay que señalar que, en esta historia del cristianismo, es decir, de la ruptura completa con la posibilidad de un orden dado del mundo, se abre también la posibilidad humana de producir un mundo. Es incluso la invención del hombre como ente en el centro del dispositivo. Eso ocurre al mismo tiempo que la apertura a otro régimen del sentido, el régimen del infinito. Todo se juega en esta enorme ambivalencia, y en determinado momento/al cabo de un tiempo, Pascal dirá que &ldquo;el hombre rebasa infinitamente al hombre&rdquo;.<br><br>
  Aquí es donde también interviene la tentación de rehacer el mundo por parte de la Iglesia, la cuestión del imperio, que se desdobla, ya que el cristianismo no puede convertirse directamente en un imperio; por eso están el papa y el emperador. La escisión entre lo que fue, dentro de un siglo en Roma, la unidad entre el sentido y la experiencia, sale victoriosa. Pero tampoco es por azar que la Iglesia católica sea romana. La idea del imperio permaneció como idea de civilización política de Carlomagno a Hitler. Pero en el fondo la Iglesia nunca llegó a tratarse a sí misma como hubiera debido. Se transformó una primera vez con la Reforma, pero para integrarse aún más al Estado. Y la Reforma tuvo otra consecuencia, la de iniciar el proceso de desmitologización, que condujo igualmente a la crisis del cristianismo.<br><br>
  El primer cristianismo no esperaba sino el fin del mundo. Durante el segundo, entre los siglos VI y el VIII, el sentido, que había sido enviado al otro mundo, se repliega sobre ese mundo, y se inventan cosas para mostrar que el paso al otro mundo se hace a través de este mundo: de ahí nace la idea del valle de lágrimas o la del triunfo del reino de Dios sobre la tierra.</p>
<p><em>Encontramos aquí la providencia, el progreso, la historia, lo que usted llama frecuentemente &ldquo;regímenes de significación&rdquo; que serían lo que está en crisis actualmente. El mundo contemporáneo no constituirá más, tal vez por fortuna, sentido. ¿Cómo distinguir entonces la infinitud, lo que usted piensa con el término del sentido y los constantes intentos de la historia por reconstituir regímenes de significación unívocos?</em></p>
<p>Por eso hay que regresar a Roma, el único momento en el que parecía que el mundo podía ser su propio sentido. Lo cual supone la siguiente pregunta: ¿cómo rehacer el imperio? Pero esta pregunta sólo es válida si se le añade: ¿cómo rehacer el imperio sin el cristianismo? Pues este último es el que de alguna manera ha precipitado el fin del mundo romano.<br><br>
  Por otro lado, no hay que subestimar lo que ocurre en el terreno del saber, que se transforma radicalmente en relación con lo que era en el tiempo de los romanos. En efecto, en el régimen romano el saber se convirtió en saber-hacer, un bloque técnico que se impuso y sobre el que el acontecimiento cristiano, que es también el acontecimiento de la subjetividad, hizo advenir la posibilidad de un saber infinito. No por azar se trata de una historia que llega hasta el cálculo infinitesimal y todas las teorías del infinito en las matemáticas modernas. A final de cuentas, se busca el motor…</p>
<p><em>Lo cual remite al nominalismo medieval…</em></p>
<p>Pero ¿de dónde viene el nominalismo? Se hace posible por toda la escolástica.</p>
<p>La tentación del control</p>
<p><em>La escolástica es un inmenso esfuerzo para cercar un sentido, Dios mismo, mediante una serie de definiciones, es decir, para controlar lo incontrolable. El nominalismo no hizo sino recordar ese no control y radicalizarlo.</em></p>
<p>Hay un intento de control, completamente paralelo al del imperio. En Roma, el hecho de &ldquo;decir&rdquo; el mundo, iba acompañado del control de ese mundo a través de todos los medios necesarios. El cristianismo apareció como respuesta a la tristeza que acompaña al control. Éste aportó algo que se debe comprender en términos de energía y que tuvo la fuerza de abrirse hacia un afuera que parecía haber desaparecido. Pero esta fuerza es temible. Tomás de Aquino, en su tratado de los nombres divinos, se esfuerza por dar sentido a &ldquo;deus&rdquo;, refiriéndose al mismo tiempo al tetragrama divino, pero también a Jesús, nombre humano. Deus se vuelve un nombre magnífico, pero Tomás no cree que sea un nombre mágico, un nombre sagrado.<br><br>
  Terminamos sirviéndonos de &ldquo;Dios&rdquo; de manera constante, y hoy mundializada. &ldquo;Dios&rdquo; en singular tiene un sentido y es una invención absolutamente occidental, primero platónica y después cristiana. La escolástica, en el fondo, devela el hecho de que se trata de operaciones del lenguaje. Encontramos el razonamiento hecho anteriormente en el caso del derecho. Es tal vez ahí que algo de la latinidad se filtró, ya que el derecho latino, a pesar de sus referencias religiosas, terminó por instalarse en su autoproducción (invención de la jurisprudencia, acopio de mandatos [ordonnances]), declarando de esta forma su propia dimensión formal. Ahora bien, el nominalismo dice que todo es formal. Esta actualización de la formalidad abre simultáneamente el infinito.</p>
<p><em>Pero también abre la nada, pues es el inicio de la cuestión de la teología negativa, que conducirá después al nihilismo.</em></p>
<p>La teología negativa ya había aparecido anteriormente, pero efectivamente va a tener cada vez mayor importancia, hasta la frase de Eckhart, &ldquo;roguemos a Dios para que nos deje en paz y libres de Dios&rdquo;.<br>
  Lo que dice Eckhart, y que considero aún válido, es que nunca se es completamente libre de Dios más que cuando uno logra rezar a Dios para serlo. ¿Qué quiere decir &ldquo;rezar a Dios&rdquo;, es decir, no hablar con nadie pero hablar verdaderamente, no obstante? Es algo que la poesía, la literatura en general sabe, o ha sabido…<br><br>
  Si acaso hemos dejado atrás la cuestión de Dios, por el contrario, estamos tal vez más que nunca en la cuestión del saber, o mejor dicho, de la investigación, una especie de &ldquo;mal infinito&rdquo; del saber. No dejamos de estar inundados por los &ldquo;descubrimientos&rdquo; de las ciencias cognitivas, que, al menos en su divulgación, dan la impresión de empujar cada vez más lejos la cuestión del sentido, de afirmar una especie de pensamiento tautológico: &ldquo;Así es porque así es&rdquo;.<br><br>
  La ciencia moderna fue posible a partir del momento en el que, como bien dijo Kant, construyó ella misma su propio objeto. Así es como se creó el antecedente de condiciones matemáticas, que son las condiciones de un lenguaje del infinito. Es lo que permite a Descartes decir, al inicio de <em>El mundo o el tratado de la luz</em>, a saber, que va a presentar al lector un mundo a la vez totalmente diferente y semejante al que conoce.<br><br>
  Esta ciencia moderna es indisociablemente técnica (la técnica no es simplemente una aplicación de la ciencia), sino que descansa sobre un postulado de control e incluso de control del infinito.</p>
<p><em>La ciencia descansa también sobre el postulado de que el mundo es algo que está &ldquo;por hacerse&rdquo;, que no está dado. Ahora bien, una serie de temáticas más o menos filosóficas en el debate intelectual del siglo xix regresan para plantear que el mundo no es nada, luego puedo hacer algo de él. Es una forma de nihilismo activo, hubiera dicho Nietzsche. ¿Qué se puede pensar de esta creencia según la cual el mundo está &ldquo;por hacerse&rdquo;? ¿No se trata del antecedente de un nihilismo técnico en particular?</em></p>
<p>No lo sé. En oposición a la propuesta de que &ldquo;el mundo no es nada, es lo que hago de él&rdquo;, me parece que lo que nos enseña la técnica es que el hombre es un producto puro de la naturaleza —uno de los logros de la ciencia moderna y en contra del cual se manifiesta cierto fanatismo. Que el hombre sea situado en la descendencia del mono es muy importante, ya que eso quiere decir que la naturaleza, la physis como dice Heidegger, tiene la capacidad de producir un ente que la desarticula por completo.<br><br>
  Si entendemos eso, no podemos seguir hablando de la naturaleza como de una especie de condición previa de la que tenemos necesidad, ya que se trata de otra cosa: estamos dentro de ella. Esto quiere decir que la pregunta acerca del sentido es la misma acerca de lo que hace este animal en la totalidad de lo que existe. El hombre es ese ente, ese viviente que hablando, es decir, manejando su sentido, deshace y rehace constantemente la totalidad del mundo. Pero no se puede decir que el mundo no sea sino lo que él produce. Se puede decir que el mundo se produce tanto a él mismo como a su propia transformación, en la medida en que el hombre es parte del mundo. Eso permite ir más allá del discurso que dice que tenemos que hacer un mundo nuevo. Marx decía que la historia del hombre devendrá en la historia natural y viceversa. En esta fórmula, no obstante, él muestra que la historia tiene el sentido de ambos, y el de su interdependencia. Se insiste mucho en la producción en Marx, pero cuando él dice eso, no olvida que la producción proviene de la naturaleza.<br><br>
  Respecto del saber como técnica, se está demasiado acostumbrado a dejar el campo abierto a las reflexiones sub-heideggerianas que consideran a la técnica como una explotación de la naturaleza en calidad de almacenamiento. Ahora bien, Heidegger no sólo dice eso… Nos hallamos frente a una situación en la que la técnica exige algo más que la apelación a la regulación (&ldquo;ciencia sin consciencia no es sino la ruina del alma&rdquo;, ya está un poco pasado de moda…), al buen uso de la técnica, igual como se dice del buen uso del capitalismo. Actualmente proliferan expresiones como &ldquo;técnica humana&rdquo;, &ldquo;técnica bajo vigilancia&rdquo; o &ldquo;capitalismo ético&rdquo;.</p>
<h4>Blanchot y la &ldquo;nada&rdquo;</h4>
<p><em>Usted mencionó el texto de Heidegger sobre la técnica, cuya primera frase es: &ldquo;La esencia de la técnica no es técnica&rdquo;. Ese gesto motiva también el uso del término &ldquo;nihilismo&rdquo;: la esencia de la crisis no es la economía. En nuestro presente hay configuraciones de sentido ajenas al discurso de los peritos, a los imperativos del problem solving. Ahora bien, esta cuestión del nihilismo está muy presente, después de la Segunda Guerra Mundial, en Blanchot, Bataille y también en Foucault por medio de Nietzsche y Heidegger. ¿Cómo explica usted, retrospectivamente, que esta noción surgiera en ese momento como elemento fundamental de la ruptura con cierto régimen del sentido? Y ¿qué papel ha jugado en su propia formación filosófica?</em></p>
<p>Esta problemática me llegó relativamente tarde, alrededor de 1968. Siempre me impresionó el hecho de que, como toda mi generación, nunca tuve en lo absoluto una consciencia del nihilismo durante mi juventud.<br>
  ¿Qué nos atraía? Primero que nada, los <em>Trente Glorieuses</em>. Pero también cierto clima positivo, de confianza, en el que de todas maneras había una flecha del tiempo que apuntaba en forma positiva. La historia avanzaba. Incluso cuando no se era marxista no cambiaba gran cosa: se creía, sin exagerar, en el progreso.<br><br>
  Me &ldquo;salí&rdquo; del cristianismo cuando me di cuenta de que éste participaba de ese mismo movimiento progresista. Pero después, me di cuenta de que todo lo que nos incitaba estaba relacionado con un estado del mundo heredado antes de la guerra, y respecto del cual nuestros padres habrían hecho lo imposible para recuperarlo, como si no fuese nada.<br><br>
  Viví de 1945 a 1951 en Alemania. Tenía entre 5 y 11 años, pero no tenía consciencia de la guerra. No me contaban nada. No fue sino después que las cosas sucedieron. Se pensaba que sólo se trataba de una gran torpeza que había que olvidar. Nos atraía sobre todo el elemento de dinamismo de la descolonización, que estaba también integrado al gran modelo del progreso. Esta liberación de los pueblos colonizados, en el fondo, era casi la coronación de la civilización occidental (habíamos fallado, pero lo enmendábamos). Una de las primeras desilusiones sucedió cuando me encontré por primera vez con la gente del Frente de Liberación Nacional (FLN), poco antes de los acuerdos de Évian. Se trataba de un curso de formación para los maestros de la futura Argelia independiente, realizada por los cuadros del FLN. Ese día tuve la impresión de que toda mi energía fue cortada desde la base. &ldquo;Si unos cabrones como éstos van a llegar al poder, ¿para qué combatimos?&rdquo;, pensé… Yo debía ocuparme del campo literario y me desaconsejaron ciertos libros…<br><br>
  En Argelia, en Egipto, un poco en toda África, el desenlace de la descolonización nos enfrió. En 1963, la primera vez que estuve en <em>Esprit</em>, invitado por Robert Fraisse, fue para un encuentro acerca del silencio de la joven generación. Hablé para decir que ésta no se reconocía en el discurso de los demás; teníamos una doble consciencia; creíamos en un gran impulso y al mismo tiempo ningún discurso (comunista, personalista) nos convencía completamente.</p>
<p><em>¿Cuál era entonces la influencia de autores que trataban la cuestión de la nada, del nihilismo? ¿Había una toma de consciencia de lo trágico así eludido tanto por el marxismo como por esa creencia generalizada en el progreso?</em></p>
<p>En este mismo periodo Jean-Marie Domenach publicó <em>Le retour du tragique</em>. La referencia a la &ldquo;nada&rdquo; llegó como una afortunada sorpresa. Como algo que vendría a llenar lo que se sentía como un vacío, pero sin pensamiento.<br><br>
  No dejo de hacerme esta pregunta por la &ldquo;nada&rdquo;, ya que siempre he dicho que el primer sentido de la palabra es positivo, es decir, lo que se encuentra todavía en la expresión &ldquo;basta con nada [il s&rsquo;en faut d&rsquo;un rien]&rdquo;. &ldquo;Nada&rdquo; es una cosa pequeñísima [un tout petit quelque chose]. Pero eso no funciona más que en francés. Sobre todo ahora pienso que toda esa constelación de la nada, de la ausencia, tuvo un papel considerable, pero lo que nos dejó fue la necesidad de acabar con la nada. Eso no quiere decir, sin embargo, poner algo o a alguien en el lugar de esa nada.<br><br>
  Voy a publicar próximamente una obra sobre <em>La communauté inavouable</em> de Blanchot. En efecto, me di cuenta de que nadie leyó nunca ese libro y de que es un libro extraño, complicado. Blanchot confiesa, de manera clara en el artículo &ldquo;<em>Les intellectuels en question&rdquo;</em> de 1984, que no renunció a sus convicciones previas a la guerra. En él afirma que los intelectuales, cuando se comprometen con la justicia y la democracia, hacen su deber pero no hacen su trabajo de intelectuales.<br><br>
  Ahora bien, en lo neutro de Blanchot hay un rechazo por pronunciarse, lo cual puede dar lugar a una &ldquo;neutralización de lo neutro&rdquo;; y también a no querer nombrar aquello que se sabe bien es heredado y que podríamos denominar algo así como el mito. En <em>La communauté inavouable</em>, Blanchot muestra que para él, la comunidad debe descansar sobre un mito y ese mito tiene una relación muy marcada con Jesucristo, con la Eucaristía.<br><br>
  Eso significa que Blanchot, es decir, el gran referente de &ldquo;la nada&rdquo;, logró impresionar con una maestría y una penetración extraordinarios, pero embriagándose de sí mismo olvidó que aún había algo por hacer. ¿De qué manera Blanchot llegó a embriagarse de sí mismo? Consagrando nuevamente, y como siempre, la palabra del escritor y de la literatura como la garantía de aquello que asegura la presencia mítica. Pero en Blanchot, tengo la impresión de que eso terminó por tomar el aspecto de una especie de autoridad profética y sagrada. En cierta manera, es &ldquo;después de mí, el diluvio&rdquo;. No me gustan los relatos de Blanchot, no en el sentido de que no sean de mi gusto, sino porque ellos exponen constantemente un rechazo del relato —gran cuestión blanchotiana—, porque el relato trata sobre algo contingente, algo accidental, sobre la transformación, mientras que el no-relato de Blanchot pretende mostrar una presencia plena.<br><br>
  Recientemente, descubrí el libro de Uri Eisenzweig, en el que habla acerca del rechazo al relato como una marca de los orígenes del fascismo en la literatura, a partir de Barrès. Se trata de un rechazo del relato, pero no del mito. Hasta aquí no había hecho la diferencia, porque no había reflexionado lo suficiente acerca de lo que significaba el rechazo al relato en Blanchot. ¿De qué mito se trata? No podría haber mito aquí, sin figuración. Pero en Blanchot, esta sería una pálida figura, casi borrada, desaparecida. De eso se trata <em>La communauté inavouable</em>: de la mujer que desaparece. Pues es la mujer la que carga con todo para Blanchot, inclusive el goce, que el hombre no conoce. Pero Blanchot, en el libro, se coloca en la posición de la mujer. Existe un reto verdadero en el relato, a contrario de lo que pensaba Blanchot. Hace poco leí dos novelas de Roberto Bolaño, <em>Los detectives salvajes</em> y <em>2666</em>, y pensé: &ldquo;Hay algo aquí que habla del mundo en el que estamos&rdquo;. Fue la misma sensación que tuve de joven leyendo a Balzac.</p>
<p><em>Es interesante que la exigencia de acabar con la nada remita al relato. Significa admitir uno de los rechazos fundamentales de Blanchot y del estructuralismo, a saber, la transitividad del relato, el hecho de que el relato habla del mundo. Es lo que dijo Ricœur, pero puesto en contradicción con la visión de lo literario como texto puro.</em></p>
<p>Hablar sobre el mundo quiere decir que el mundo existe, es decir, que hay una exterioridad densa, resistente. Tomemos el ejemplo del espíritu, ya que la &ldquo;debacle del espíritu&rdquo; ha sido una fórmula con frecuencia empleada para describir la decadencia, el nihilismo. Si hablamos del espíritu, hay que ser completamente capaz de pensar que el espíritu no es nada, no es una cosa. Se puede evocar a Agustín: el espíritu no tiene dimensión, está fuera del tiempo y el espacio. Lo que significa que los atraviesa. En cierto sentido, la ciencia penetra la materia. Hablar del mundo, sí, porque de cierta manera, no se puede hablar de otra cosa. Incluso si el mundo no hace mundo en el sentido de una posibilidad de sentido. No es sino hablando que se le da la posibilidad de devenir mundo.</p>
<p>La apelación a los valores</p>
<p><em>Hay una manera de decir que se ha puesto un fin a la nada, al nihilismo y a la decadencia, y esa manera es apelando a los valores. Los valores aparecen, cada vez con mayor frecuencia, como una referencia destinada a constituir un común, una comunidad. Pero hay que recordar la crítica radical de los valores en Heidegger, en el sentido de que éstos pertenecen al nihilismo. ¿Esta apelación a los valores participa de una forma de nada o hay en ella algo que, incluso de manera torpe y eminentemente discutible, manifiesta por el contrario una exigencia de no abandonarse a la nada?</em></p>
<p>Retomemos primero la palabra &ldquo;valor&rdquo;. Si el nihilismo es la devaluación de todos los valores, la devaluación no suprime el pensamiento que hay en la palabra &ldquo;valor&rdquo;. El valor manifiesta algo en nuestra historia, en toda nuestra tradición, aunque haya dificultades para reconocerlo. Y no son precisamente &ldquo;los valores&rdquo;. Los valores sólo pueden remitir a la idea del valor. Ahora bien &ldquo;el&rdquo; valor, el hecho de valer en sí, nos traslada, justo en medio de la historia del nacimiento del mundo moderno, a la palabra alemana de <em>Würde</em> (dignidad) que pertenece a la familia <em>Wert </em>(valor).<br><br>
  <em>Würde</em> es la palabra que Kant usa para designar aquello a lo que debe dirigirse el respeto del imperativo categórico. El imperativo categórico es la toma de conciencia y la verbalización por parte de toda una época de algo que está ahí, trabajando. Lo que dice Kant con la palabra <em>Würde</em>es que el imperativo moral, que está presente en la razón humana (no es el filósofo quien lo importa), consiste en respetar la dignidad de cada hombre. Se le puede extender a la dignidad de cada existente, pero ésa es otra cuestión.<br><br>
  ¿Qué significa esta dignidad como valor absoluto? Es exactamente lo que nos designan y nos esconden al mismo tiempo todos nuestros discursos sobre los valores y los derechos humanos. ¿Qué quiere decir este valor? Tal vez algo que no puede ser medido por ninguna unidad de medida. No se trata del valor en el sentido económico. Eso no tiene precio, pero vale. O en todo caso vale un precio infinito. En ese aspecto, la dignidad kantiana proviene directamente del judeo-cristianismo. Además, ésta es común a todas las grandes religiones monoteístas, en las que lo &ldquo;mono&rdquo; remite más a lo Uno que a la idea de &ldquo;cada uno&rdquo;. Ahora bien, ése es el gran asunto de la democracia. Se inventó la democracia creyendo que se inventaba un nuevo régimen de gobierno cuando en realidad se procedió a una gran mutación antropológica. Se dijo lo que el cristianismo decía desde el principio y lo que era uno de los grandes ejes de la Antigüedad: el fin de las diferencias constituyentes y jerárquicas entre amo y esclavo, hombre y mujer…</p>
<p><em>Es lo que decía Marx cuando escribía que la democracia realiza lo que el cristianismo nunca pudo realizar por sí mismo.</em></p>
<p>Sí, salvo que él aún creía en que esta realización era posible. Y los teóricos del comunismo, como Engels, hicieron con frecuencia un paralelismo entre los primeros cristianos y los comunistas. Siempre es la igualdad la que supone un problema. Hoy, la enseñanza democrática, por ejemplo, reposa de hecho sobre un desprecio total de la igualdad que supuestamente representa, ya que todo el mundo sabe muy bien que eso no funciona y que tal vez no puede funcionar. Lo que significaría que la igualdad democrática no consiste en la distribución de la misma cantidad de saber a todo el mundo.<br><br>
  El valor, finalmente, coincide con el sentido. El sentido es un &ldquo;valer para&rdquo; siempre para alguien más, en principio para todos.</p>
<p><em>Esta perspectiva borra ligeramente el aspecto &ldquo;moral&rdquo; del valor. Ahora bien, nos encontramos también en una época —lo hemos visto durante las marchas contra el matrimonio homosexual— en la que el tema del valor aparece revestido por una especie de aura casi mágica, ya que se supone que éste debería rehacer la comunidad ahí donde el individualismo o los comunitarismos religiosos habrían diseminado el sentido. ¿Cuál es su opinión acerca de esta referencia de lo colectivo por lo moral, por el valor, que tampoco es la norma kantiana?</em></p>
<p>A lo universal no podemos simplemente despedirlo o dejarlo de lado, pues es nuestro estandarte. Modularlo, tal vez, comprender mejor que este universal no debe ser abstracto, de acuerdo. Pero no podemos borrarlo.<br><br>
  La historia del matrimonio para todos ha sido muy interesante por esa razón. Todos se han referido a valores ya dados. Por un lado, la familia, la infancia, etc., por el otro, la igualdad y el derecho para todos. Me sorprendió, me dejó perplejo incluso, la cantidad de manifestantes que se opusieron al matrimonio homosexual; pero además, me desagradó porque los defensores del matrimonio homosexual no tenían otra cosa que alegar más que el &ldquo;derecho&rdquo;. Hubiera querido escribir algo para decir que no se trata de eso, sino del hecho de que las sociedades se transforman, evolucionan. La familia nuclear es una tradición no tan antigua y, en su práctica efectiva, es incluso muy reciente. Sin ser del campo, pertenezco a una familia que vio a mis abuelos vivir mucho tiempo con nosotros durante su vejez, lo que actualmente es inimaginable. Hace falta analizar por qué cambia eso. Esta idea de la familia conyugal con todas sus implicaciones patrimoniales, a la cual se suma curiosamente el carácter sagrado del matrimonio, invención cristiana y único sacramento cuyos actores son los esposos mismos. Todo eso se desplaza, es lo que hay que analizar. Cambiamos entonces a un plano de instrucción pública: ¿cómo hacer para aceptar esas mutaciones? Si la &ldquo;familia&rdquo; se desplaza, eso vuelve ciertas cuestiones todavía más puntillosas y más difíciles, como la de los hijos, la procreación, y todas aquellas cuestiones económicas que se desprenden de ello. Y todo eso desemboca aún más cerca del pensamiento de un valor absoluto, no solamente de una existencia individual, sino también de una relación.</p>
<p><em>¿No sería imposible disociar la creencia del valor? Son nociones que se tienden a asociar, aunque no necesariamente coinciden.</em></p>
<p>En efecto, son dos cosas muy diferentes. Cuando se dice &ldquo;creencia&rdquo;, pienso sobre todo en la creencia en un Dios. La creencia es una forma de saber débil. &ldquo;Creo que hará buen tiempo&rdquo;. Cuando se dice: &ldquo;Creo en Dios&rdquo;, ¿qué es lo que se dice? Hace poco le pregunté a una mujer en un coloquio en Italia. Me respondió que la creencia en Dios para ella no estaba asociada de ninguna manera a una representación, a una imagen, sino a una fuerza. Lo cual puedo comprender, ya que finalmente, el ateísmo ¿será realmente capaz de estructurar una sociedad?<br><br>
  Debo cuestionarme al respecto haciendo una pregunta: ¿acaso no todas las sociedades se estructuran alrededor de una diferencia entre los que creen y los que no creen? ¿No se ocultaron los intelectuales inevitablemente tras las representaciones? Las miran y las desmontan como representaciones, pero no pueden regresar a la perspectiva de la creencia. En nuestra sociedad que es una sociedad del saber, ¿acaso el ateísmo no es algo que sólo es bueno para los intelectuales?</p>
<p><em>Esto remite a lo que decía Philippe Lacoue-Labarthe: la locura es el premio del filósofo, precisamente porque ahí se ha liberado de esos mimetismos identificadores y ha pasado del otro lado. Está condenado a ser el bufón permanente de una identidad en la que ya no puede seguir creyendo.</em></p>
<p>Por otro lado, él mismo habló de su identificación con Hölderlin en una entrevista, y del peligro que representaba para él. Las locuras modernas son las de Hölderlin, Sade, Nerval, Schumann, Nietzsche, Artaud…</p>
<p><em>Pero antes de eso, estaban los grandes místicos, de los cuales Michel de Certeau habló bastante. Ahora bien, la mística converge con la cuestión del nihilismo.</em></p>
<p>Precisamente, la mística es un problema con el que Bataille estuvo confrontado; porque era considerada con frecuencia como una forma de acceso. La mística permite precisamente no estar loco, como la locura permite no ser místico.<br><br>
  Vuelvo a Eckhart: el hecho de no deberle nada a la idea de Dios, de estar libre de él, estar desencadenado. Si se toma el ejemplo de Lévinas, él se llama a sí mismo &ldquo;ateo&rdquo;, pero eso no le impide tener un recurso religioso. Para Lévinas, se trata de una religión de observancia, muy diferente a la que se menciona en sus <em>Lectures talmudiques</em>.<br>
  El primer texto de Blanchot, que se convirtió en la segunda parte de <em>La communauté inavouable</em>, estaba dirigido a Lévinas. En este texto, Blanchot le niega a Lévinas lo que él mismo profesa, es decir, la pasión, el goce de la mujer. Esto equivale a posicionarse en contra de Lévinas, con frecuencia acusado de volverse &ldquo;muy&rdquo; cristiano, a pesar de que en <em>Difficile liberté</em> plasma una ferocidad extrema en contra de la Iglesia. Pero era un cristiano en un sentido no institucional. Está por un lado la Iglesia, pero por el otro, si entramos en las sutilezas de la teología y, todavía más, de la espiritualidad mística, podemos ir más lejos.</p>
<h4>La experiencia del tocar</h4>
<p><em>Hablemos de la cuestión del tocar, que en particular trató en Noli me tangere. Es como Derrida calificó su trabajo: partir de una experiencia, el tocar, que remite al mundo a partir de un modo diferente al del discurso, al de la racionalidad, de la trascendencia en el sentido de Heidegger. Es como si el mundo o un aspecto del mundo nos fuera asible. Este tipo de experiencia, ya sea sensible, artística, erótica, ¿es la que de cierta manera lo ha llevado siempre a desconfiar de la idea del nihilismo, de la nada?</em></p>
<p>Seguramente. Para mí es un poco extraño, ya que este asunto del tocar fue Derrida quien lo descubrió. Para mí fue una de las pruebas más fuertes de su capacidad de lectura. Fue un tema disperso en numerosos textos pequeños. Pero ¿de dónde viene esta experiencia sensible sino de la Iglesia? Hay una cosa que un niño católico conoce como vinculada a la sacralidad y es una cierta sensibilidad, por no decir sensualidad. Hegel dice que la Madonna [Vierge à l&rsquo;Enfant] es el centro de la pintura. Philippe Lacoue-Labarthe estaba de acuerdo y decía que al menos el catolicismo tiene el gran mérito de tener una diosa mujer erótica. Ciertamente, detrás de todo eso hay algo como un sentido de lo sensible.</p>
<p><em>¿Pero cómo asociar la filosofía del tocar con el rechazo de la carne, ya que usted opone el cuerpo y la carne?</em></p>
<p>La carne es únicamente nominal, precisamente. La palabra &ldquo;carne&rdquo; es muy cristiana. Los fenomenólogos franceses tomaron la palabra porque Husserl la emplea. Para Husserl, Leib no tenía la resonancia que &ldquo;carne&rdquo; tiene en francés. Para mí, aceptar esa palabra de carne supone más bien remontarse al hebreo: cualquier carne es como la hierba. Ése es el pensamiento de la carne: el pensamiento de la creatura. Pero hay que remontar todo el sistema de la creación…<br><br>
  Por otro lado, prefiero el &ldquo;cuerpo&rdquo;, porque &ldquo;cuerpo&rdquo; tiene algo de individualizante, de discontinuo, mientras que la carne es continua. Todas las cosas son cuerpos. Pero hay una cosa que no es cuerpo y sin la cual el cuerpo no es tal, y eso es la relación. Creo que es ahí por donde pasa también la evaluación del valor.<br><br>
  Ahora bien, si hay algo que me parece capital, es que toda nuestra moda de pensamiento descansa inevitablemente en una especie de primado de lo &ldquo;uno&rdquo;. Incluso cualquier temática de lo otro supone lo uno. Hubiera querido decir que primero está la relación. Esto significa, en el sentido casi cosmogónico, que es precisa una tensión para tener dos partículas. Ahí hay pues, una relación. Y esa relación no es una cosa. Los escolásticos lo vieron bien al calificar la relación como una forma débil de ser. Es ahí cuando el sentido se produce.<br><br>
  A propósito de la producción de sentido, se está escenificando una profunda transformación en la representación que la ciencia tiene de sí misma. La ciencia está tratando de mostrarse a sí misma que fabrica ficciones. Es desde el interior de la ciencia que se producirá un desfase en relación a nuestro modelo de aprehensión de la realidad, incluso mediatizado por el kantismo de la construcción del objeto. Ese kantismo es importante, porque si se construye el objeto, mientras más complejo y sutil sea, y por lo tanto construido, más consciencia tenemos de él, y se hace menos posible volver al naturalismo.</p>
<p><em>¿Qué impide entonces que la ciencia devenga en una nueva mitología?</em></p>
<p>No anticipemos el próximo desastre… Supongamos que en cierto momento será claro que no estamos esperando la ecuación del universo. Las transformaciones más intelectuales, las más teóricas que existen, impregnan, incluso de manera lenta, la vida común. En la época de Descartes, casi nadie podía comprender lo que significaba ser &ldquo;como amo y poseedor de la naturaleza&rdquo;; actualmente, mucha gente lo comprende, incluso muchos lo lamentan. Tampoco podemos prever cómo se efectúan los desplazamientos. Esta es la dificultad más grande a la que nos hemos enfrentado: nuestra civilización es tal vez la primera que entra en una mutación sabiéndolo, además de saber que no hay nada qué saber acerca del porvenir. Derrida tenía una gran comprensión de ello. El futuro es un presente proyectado al futuro, mientras que el porvenir [avenir] está por-venir [à-venir] y entonces sólo hay que dejarlo advenir [le laisser advenir]. Hay un momento en el que eso pasa, en el que ocurre a través de alguien.</p>
<p align="right"><em>Traducción del francés: Yanga Villagómez Velázquez y<br>
  Hrindanaxi G. Villagómez Sánchez.</em></p>
<p align="right">Agradezco a los tres representantes de <em>Esprit</em> por sus preguntas y a Alice Béja por su atenta transcripción. Las insuficiencias, lagunas, puntos inacabados que salpican estas palabras son producto de un habla demasiado desatada.<br>
  <em>J.-L. N.</em></p>
<p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Jean-Luc Nancy es un filósofo francés nacido en Caudéran en 1940. Graduado en estudios de Filosofía en París, realizó después un doctorado sobre Immanuel Kant con Paul Ricœur. En 1968 se vuelve asistente en la Universidad Marc Bloch de Estrasburgo, donde actualmente detenta una cátedra. Sus estudios sobre política, metafísica, arte y comunidad en época de crisis suelen ser los más leídos, en especial <em>El absoluto literario</em> (1978, en colaboración con Philippe Lacoue-Labarthe), <em>Ego sum</em> (1979), <em>La comunidad desobrada</em> (1983), <em>Corpus</em> (1992), <em>Ser singular plural</em> (1996) o <em>La declosión</em> (2005).
<div> </div>
</div>
</section>
<?php include 'footer.php' ?>