<?php $title ='Agustín Ramos - ¿Leoncitos a mí? Sueños compartibles | Revista Fractal'; ?>

<?php include 'header.php' ?>


<section class="titulo">
	<article class="">
		<h3>Número 74</h3>
		<h1>¿Leoncitos a mí?<br>
Sueños compartibles</h1>
		<h2>Agustín Ramos</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
    <p align="right" style="font-size:13px; margin-bottom:40px;"><em>A la Sociedad Cooperativa </em><br>
      <em>Trabajadores de Pascual, </em><br>
      <em>S.C.L.</em></p>
    <h4>i </h4>
    <p>Desocupado lector: <br>
      Sales conmigo a la segunda parte de <em>El ingenioso hidalgo don Quijote de la Mancha</em> y llegas a mi episodio predilecto, el capítulo xvii, en el que ocurre la aventura de los leones.<br>
      Don Quijote viene en compañía de don Diego de Miranda, un hidalgo que por vestir gabán verde, llevar montera de terciopelo y montar yegua tordilla, merecerá en adelante el sobrenombre de Caballero del Verde Gabán.<br>
      Así pues, entre caballeros andamos. El Caballero de la Triste Figura viene de vencer al Caballero de los Espejos en duelo que prolonga la ficción y prepara el verdadero y único gran triunfo de don Quijote: el ya dicho desafío a los leones.<br><br>
      En palabras del propio Cervantes, este triunfo sobre fieras consti­tuye &ldquo;el último punto y extremo adonde llegó y pudo llegar el inaudito ánimo de don Quijote&rdquo;.<br><br>
      Mientras don Diego escucha con admiración el parecer de don Quijote con respecto al oficio de los poetas, éste avizora una cara­vana de carros empavesados con tremolantes gallardetes que lucen los colores del rey Felipe III.<br><br>
      Previendo aventura, don Quijote reclama el yelmo a Sancho, su escudero.<br><br>
      Éste, que anda fuera del camino agenciándose un requesón entre pastores, acude presto con su señor. Pero por las prisas pone la mercancía precisamente en el fondo de esa bacía que ha pasado a la historia como el yelmo de Mambrino.<br><br>
      Acelerado, don Quijote se lo calza y siente o que los sesos se le derriten o, peor aún, que está sudando de miedo.<br><br>
      Como el miedo es la última sensación que un andante caballero se puede permitir, da una probada a la viscosa materia que le escurre por las sienes y descubre el sabor del requesón.<br><br>
      Aclarado el punto conforme a la picardía de Sancho y a la lógica de su señor, éste averigua con el carretero que la caravana lleva una pareja de leones africanos, macho y hembra, los más grandes y hambrientos que jamás hayan pasado de África a la corte de España.<br><br>
      —¿Leoncitos a mí? ¿A mí leoncitos y a tales horas? —dice don Quijote con una sonrisa de medio lado. Y exige al leonero que abra las jaulas.<br><br>
      Pero antes de que esta y otras citadas aventuras ocurrieran, el lector pudo auscultar el soliloquio de Sancho cuando su señor lo mandó a la ciudad a rogarle a Dulcinea que se dignara bendecir a su rendido caballero. Y disfrutó, así mismo, la moderna salida tipo monólogo interior que el escudero encontró en tal atolladero:</p>
      
    <blockquote>Siendo, pues [don Quijote], loco, como lo es, y de locura que las más veces toma unas cosas por otras, y juzga lo blanco por negro y lo negro por blanco, como se pareció cuando dijo que los molinos de viento eran gigantes, y las mulas de los religiosos dromedarios, y las manadas de carneros ejércitos de enemigos, y otras muchas cosas a este tono, no será muy difícil hacerle creer que una labradora, la primera que me topare por aquí, es la señora Dulcinea…</blockquote>
    
    <p>Porque, más atrás todavía, Sancho hizo creer a don Quijote que había visto a Dulcinea. Y hasta se dio el lujo de describirla.<br><br>
      Los pormenores de esa descripción los saboreé de niño por la boca de mi madre.</p>
      
    <h4>ii </h4>
    <p>Pasé la infancia a fines de la década de 1950 en una ciudad de Hidalgo. Éste, el tercer estado más empobrecido de mi país, no registraba nada digno de recuerdo. Excepto, quizás, la consolidación de una sociedad cooperativa de trabajadores del cemento en un lugar de cuyo nombre era fácil no acordarse: la antigua hacienda de Jasso, en la región de Tula, otrora capital de los toltecas.<br><br>
      Debo de haber andado por los nueve años de edad cuando mi m­adre, al llegar del trabajo por las noches, nos leía <em>El ingenioso hidalgo don Quijote de la Mancha</em> a sus hijos y a mi prima la mayor, en una edición de filos rojos y guardas con estampado de coronas de espinas.<br><br>
      Vivíamos en la casa de mis abuelos maternos, en la pieza del fondo, al final de un corredor largo y estrecho. Más que ventanas, esa habi­tación tenía dos mirillas de un vidrio verde constelado de burbujas; tan altas eran éstas, que para ver nuestro corral o para fisgonear el huerto vecino necesitábamos subir a un armario o funambulear en el respaldo de una silla.<br><br>
      Ese huerto donde los manzanos, los nogales y los naranjos parecían cansarse de jugar a la ronda en torno de un cenador revestido de vitrales, pertenecía a una pareja de ancianos españoles refugiados.<br><br>
      Como mi prima la mayor y yo sabíamos que el muro del comedor de los abuelos, contiguo al huerto, no era de adobe sino de yeso, inflamados por la imaginería quijotesca rascamos con el cucharón de los frijoles el fondo de una alacena y dimos con el otro lado del tiempo.<br>
      La huerta estaba abandonada y los frutos se fermentaban en medio de una maleza de más de un metro de estatura. Alcahueteados por esa maraña pudimos trasegar senderos que confluían, todos, en el quiosco de nuestra ambición: un cenador de herrería con forma octagonal y emplomados de unicornios y dragones.<br><br>
      Y aunque más tardamos en entrar que en ser sorprendidos por los dueños, tuvimos tiempo suficiente para sentir entre nuestros dedos algún mantel luido, lagrimones de un candelero en desuso, piezas de incompletas vajillas Luis xv y alteros de monedas de cobre de uno y dos centavos salidas de circulación dos lustros atrás.<br><br>
      Tanto como aquél, mi recuerdo más vívido de entonces es la ocasión en que mi madre nos leyó el diálogo, perteneciente a la segunda parte, en el que don Quijote enmienda la descripción que Sancho hizo de Dulcinea. Palabras más, palabras menos, le dice: Me la pintaste mal, Sancho, porque dijiste que tiene ojos de perlas y supongo que los de Dulcinea deben ser de verde esmeralda, así que quita esas perlas de sus ojos y ponlas en sus dientes.<br><br>
      Tres décadas después, la vida me regaló el sueño de leer el <em>Quijote</em> a mi niña la grande cuando ésta tenía seis años. Sus pasajes favoritos eran la lucha con los molinos de viento, las especulaciones a causa del batán, el manteamiento de Sancho, el combate con los cueros de vino, aquella batalla de ovejas y carneros de la que don Quijote salió sin muelas y, como el más impactante para ella, la incineración de libros. Todo ello, sobra decirlo, corresponde a la primera parte; mientras que yo, por el contrario, siempre disfruté más la segunda parte.<br><br>
      Por su parte la cooperativa Cruz Azul, cumpliendo su propósito de invertir sus ganancias no en proyectos de enriquecimiento personal sino de expansión en zonas pobres del país, consolidó una planta en un estado equiparable a Hidalgo en atraso y miseria, Oaxaca. Para entonces el equipo Cruz Azul, insignia de aquella cooperativa de Jasso, había metido en sus vitrinas siete campeonatos de futbol de la primera división.</p>
      
    <h4>iii </h4>
    <p>Me empecé a considerar coautor del <em>Quijote</em> gracias a la lectura vicaria de mi madre.<br><br>
      Una lectura en bruto, apegada al texto, ajena a la faramalla del título y a las dolencias del autor original. Lectura que ella sólo interrumpía para explicarnos los pasajes de difícil intelección, porque jamás nos prejuició a favor de don Quijote ni pontificó sobre la vida de Cervantes; nada habló del Manco de Lepanto ni de la más alta ocasión que vieron los siglos, nada del Siglo de Oro ni de la obra cumbre de la literatura española y universal, origen de nuestro idioma, justificación humana ante Dios, etcétera.<br><br>
      Ya luego una curiosidad, que iba a resultar espontánea, me llevaría a rascar con cucharones adecuados el más acá de la vida de Cervantes. Además, los mejores maestros de la Facultad de Filosofía y Letras de la unam habrían de impulsar, orientar y enriquecer esos nuevos funambuleos. Sin embargo, en aquel primer momento, letras y lectura aparecieron ante mí como la primera de una serie de dualidades en esa perfecta arquitectura de espejos que constituye <em>El ingenioso hidalgo don Quijote de la Mancha</em>. <br><br>
      La propuesta de un novelista y tanto mi actitud receptiva inicial como mi aptitud alfabética posterior, gestaban el acto literario. Esta conclusión me llevó a creer que autor y lector, cualquier lector, debía considerarse autor, si bien en el origen de esta infinita nómina de autores que traspone tiempos y espacios hube de reconocer a un tal Miguel, que junto con don Quijote forman el dueto subsecuente de esta cadena de dualidades.<br><br>
      Padre e hijo, padrastro e hijastro, personas distintas, autónomas y hasta contrapuestas en algunos momentos de la siempre difícil relación filiopaterna, Cervantes y don Quijote se parecen en su inconformismo mas no son necesariamente inseparables. Al contrario.<br><br>
      Despachemos pues algunas diferencias entre el autor y el perso­naje. Aquél, desde luego, es mucho menos famoso y atendido que éste. ¿O tú crees que, <em>mutatis mutandis</em>, la conmemoración del aniversario cuatrocientos de Cervantes en 1947 guarda algún remoto paralelo con el fasto que en 2005 provocó el cuarto centenario de la aparición de la primera parte del <em>Quijote</em>?<br><br>
      
      Don Miguel fue hijo de un cirujano ambulante, llevó en sus venas sangre cordobesa y en su fama pública las sospechas de converso y de erasmista. Por lo que toca al entorno, anduvo a pie el mortecino tránsito del reinado de Felipe ii al de Felipe iii, lo que en el campo del arte se traducía como la transición del renacimiento al barroco y en el horizonte histórico se pintaba con las llamaradas de un crepúsculo imperial. El mundo entero había dado un giro: el dinero sustituía a la economía feudal, las artimañas de la política y de la diplomacia podían más que las leyes, la mentira resultaba un arma mucho más eficaz que la verdad en cualquier terreno, la necesidad tenía cara de hereje y los principios se podían ir mucho al averno.<br><br>
      
      En cuanto a su parcela personal, sinsabores íntimos dejaron en Cervantes el recuerdo agridulce de una huida de Sevilla a Roma cuando apenas superaba los veinte años de edad; también deben contarse tanto un posterior matrimonio que debió haber olido a aburrimiento como una hija natural de nombre Isabel.<br><br>
      
      Gestas militares lo baldaron de la mano izquierda. Una recomendación, aunada a la mala suerte, propició que su cautiverio en Argel se prolongara cinco años y sólo se redimiera mediante un oneroso rescate. A esas peripecias bélicas sucedieron amargas épocas de frustración laboral, desde la negativa del Consejo de Indias a concederle empleo público y traslado a América en recompensa por sus servicios a la Corona, hasta el encarcelamiento en Sevilla a causa de lo que aún resuena como intriga burocrática.<br><br>
      
      En síntesis, hasta antes de 1605, Cervantes no era más que un alma cargada de derrotas y un cuerpo tullido en un mundo de peste y decadencias. Y de Perico Perro no hubiera pasado, de no ser porque escribió <em>El ingenioso hidalgo don Quijote de la Mancha.</em> Y es que este libro superó a su autor original: resultó lo que hemos hecho de él, resultó nuestra lectura, nuestras lecturas, lecturas participativas que nos convierten en autores. Subsidiarios, sí, pero autores al fin.</p>
      
    <h4>iv </h4>
    <p>El extraordinario éxito de la primera parte multiplica las ediciones e impulsa al libro a brincarse las trancas españolas, como lo refiere en la segunda parte el mismo don Quijote en el preámbulo al pasaje de los leones, cuando resume su historia a don Diego de Miranda, el Caballero del Verde Gabán: </p>
    
    <blockquote>Salí de mi patria, empeñé mi hacienda, dejé mi regalo, y entreguéme en los brazos de la Fortuna, que me llevasen donde más fuese servida. Quise resucitar la ya muerta andante caballería, y ha muchos días que, tropezando aquí, cayendo allí, despeñándome acá y levantándome acullá, he cumplido gran parte de mi deseo, socorriendo viudas, amparando doncellas y favoreciendo casadas, huérfanos y pupilos, propio y natural oficio de los caballeros andantes; y así, por mis valerosas, muchas y cristianas hazañas he merecido andar ya en estampa en casi todas o las más naciones del mundo. Treinta mil volúmenes se han impreso de mi historia, y lleva camino de imprimirse treinta mil veces de millares, si el cielo no lo remedia.</blockquote>
    
    <p>Mas si la aparición de la primera parte del <em>Quijote</em> ocurre en un mundo en donde el protagonista cree actuar ya no concuerda con el mundo en el que en realidad actúa, para la siguiente este desfase se suspende, se relativiza e incluso desaparece a lo largo de capítulos completos. Porque ahí le siguen el juego a don Quijote no sólo los nobles ociosos y la clase media ilustrada sino también el otro extremo social, el de los bandoleros y el de los pícaros.<br><br>
    
      Sí, en muchos fragmentos de la segunda parte la realidad externa coincide con la realidad de don Quijote. Y así el personaje consigue aderezar al mundo ajeno con el vestuario del mundo que él ha confeccionado. En esta nueva etapa, sus acciones se engarzan en la realidad de todos, al punto de que algunos lectores de la primera aparecen en esta segunda parte, ahora interactuando con él. Como conse­cuencia, los lectores, cualesquiera lectores, nos hallamos potencialmente complicados en la trama, ¡pero ya no como lectores sino como actores potenciales!<br><br>
      
      Por lo menos así lo empecé a vivir yo en aquel cuarto de la casa de los abuelos, a mediados del siglo xx, en una ciudad de treinta mil habitantes, en esa región donde no parecía haber nada más interesante que las matinés de los domingos, la incursión en un huerto y las aventuras de don Quijote que mi madre nos leía cada noche. En aquel mundo en el que unos cooperativistas salían a la calle después de una dramática asamblea general gritando:<br><br>
      
      —¡Viva la cooperativa de La Cruz Azul! ¡Nosotros somos la utopía! <br><br>
      Al escuchar en voz de mi madre a Miguel de Cervantes, a Cide Hamete Benengeli y, a través de éstos, al propio don Quijote y a Sancho Panza, vivía convencido de que más adelante, en algunos de los capítulos siguientes, este famoso dueto, no menos entrañable para mí que Santo y Blue Demon y Laurel y Hardy, llegaría a mi pueblo. Y, de ser así, de esas páginas de filos rojos podrían surgir los centinelas del huerto vecino, que provenían de un lugar próximo a La Mancha. O bien podían aparecer los cooperativistas de La Cruz Azul y, quién quita, hasta yo…<br><br>
      
      Por desgracia la remisión y muerte de don Alonso Quijano ocurrió antes de que mis sueños cuajaran. Por lo demás, mis gentes no eran ni bandoleros ni duques, tampoco encantados ni galeotes llevados por la fuerza a las galeras del rey. Mis abuelos habían vivido la revolución de 1910, los vecinos habían sobrevivido a una guerra, mi madre a un divorcio y La Cruz Azul a un boicot de la empresa capitalista La Tolteca, instalada a seis kilómetros de Jasso.<br><br>
      
      Al parecer el mundo ya no requería el auxilio de don Quijote. Pero había seres a quienes ese mundo no les ajustaba. Como yo; entre otras cosas porque los propietarios del huerto, en acuerdo con mis mayores, tapiaron con ladrillo las alacenas de nuestro comedor. Y no sé qué me angustió más, si ese muro a la imaginación o el anuncio de que el mundo se acabaría debido a unos cohetes atómicos que otros constructores de muros querían instalar en Cuba.</p>
    <p>v </p>
    <p>En Argel, Cervantes el cautivo había sacado a flote su verdadero temple, no sólo para cultivar la paciencia sino, sobre todo, para rebelarse e intentar una fuga hasta en cuatro ocasiones. Empero la evasión culminante de este Steve McQueen barroco, el triunfal gran escape de su vida, fue la escritura de <em>El ingenioso hidalgo don Quijote de la Mancha</em>. Porque con esa obra y a través de su protagonista, además de rehusar y reelaborar una realidad material insatisfactoria también se contrapuso a un mundo de ideas, valores y actitudes.<br><br>
    
      Sin embargo, cuando me refiero al protagonista, ¿de qué personaje hablo? Todavía no de don Quijote de la Mancha sino de un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Hablo de don Alonso Quijano, hombre bondadoso, gran lector de libros de caballería: personaje descrito en un magistral primer pá­rrafo donde se despliegan en detalle su edad, su situación económica y social, su entorno familiar y hasta sus manías madrugadoras y su afición por la caza.<br>
      Cuando aún estaba cuerdo, cuando aún se llamaba y se conducía como Alonso Quijano, nuestro personaje no se resignaba a la estrechez de un lugar de La Mancha, enrevesaba su circunstancia y la sustituía con la lectura de libros y novelas de caballería. Después, esos productos del pasado, de la fantasía y de la imprenta, fueron reemplazando de manera imperceptible la realidad individual, familiar y social de aquel lector. Si en un principio él sustituyó momentos de su realidad con los libros, después los libros fueron desplazando más y más esa realidad.<br><br>
      
      Si el mundo de la caballería, inscrito en la literatura, resultaba preferible al mundo cotidiano, era deseable que continuara vigente; sin embargo esto sólo sería posible mediante la actuación de un caballero que viviera como tal y modificara aquello que no concordase con el principio de realidad caballeresco. Por tanto, Alonso Quijano asume su aspiración y sale a buscar aventuras propias de caballero; primero que nada busca enderezar el mundo. A partir de ahí, su realidad será otra y él amoldará su conducta a esa percepción. Adopta un nombre, adapta artefactos para armarse como conviene a su oficio; consigue un escudero, idea una dama a la cual encomendar su ventura, vela armas y comienza a cabalgar. Con una nueva personalidad concebida e inspirada por la letra, va ciñéndose a la horma rigurosa del pie de esa letra y sale a buscar aventuras en plan de caballero andante.<br><br>
      
      El problema es que sale a un mundo que ya no es el que este recién confeccionado personaje necesita ni puede comprender. Don Quijote no concuerda, no tiene acuerdo con la realidad. No está cuerdo: actúa en desacuerdo con esa razón que se conforma sobre una norma cimentada en convenciones. El anacrónico caballero andante pretende, bajo uno y más nombres de batalla, cambiar la realidad en lo que tiene de desagradable, de injusta, de chata, de chueca, de vulgar. Su deseo es inyectar altos ideales, fantasía y literatura a los campos de Castilla; emoción, hazañas y gloria a una edad que ya no es de oro, una edad en la que los adjetivos mío y tuyo han esfumado lo nuestro. Él no lo sabe. O si lo sabe se hace el loco. Le hace al loco.<br><br>
      
      A veces pareciera eso, que don Quijote nada más le hace al loco. Se ha dicho que hay demasiado provecho en su cordura y otro tanto de placer en sus desvaríos. Así lo han de advertir todos los que con don Quijote conversen. Porque este ingenioso hidalgo es lúcido en los razonamientos y en la palabra, aunque no siempre lo sea a la hora de actuar, como lo atestigua el Caballero del Verde Gabán en el capítulo xvii, al observar el temerario empeño de don Quijote para que liberen a los leones.<br>
      En dicho punto, don Diego de Miranda, el Caballero del Verde Gabán, se convence de que los requesones han ablandado los cascos y madurado los sesos de éste su recién conocido a quien en tan alta estima estaba teniendo. Así se lo comenta a Sancho diciéndole algo como: ¿Acaso está tan loco tu amo que temes y lo crees capaz de enfrentarse con animales tan feroces?<br><br>
      
      —No es loco —responde Sancho—, sino atrevido.<br><br>
      Tan atrevido que obliga al leonero a abrir las jaulas. Tan atrevido que actúa como si los molinos de viento y los cueros de vino fueran gigantes, y como si la venta fuera castillo y las ovejas ejércitos. Como si…<br><br>
      Pero los leones, vaya que sí son leones.<br><br>
      El leonero obedece, no sin antes poner a salvo sus mulas y pedir a los presentes que se retiren.</p>
    <p>&nbsp;</p>
    <h4>vi </h4>
    <p>La falta de concordia entre su deseo y la realidad hacen parecer loco a don Quijote. Pero como preguntaba un insolente Shakespeare contemporáneo de Cervantes, ¿cuál es la diferencia entre ser y parecer? <br><br>
    
      Y entre la consideración social de un ser marginal a la elaboración social de tal ser marginal no median más que grados; todo es cuestión de tiempo, de perspectiva, para que se empiece a sospechar anomalía y se acumulen datos en abono de esa sospecha, actos que se registren y resulten en la conclusión de que alguien está loco.<br><br>
      
      Ahora bien, hipócrita amigo, ¿qué le sucedería a cualquier lector actual (tú, por ejemplo) si se convenciera de que es viable y obligado llevar a la práctica todo aquello que postulan los códigos de ética, los libros de sabiduría, los principios humanistas, los ejemplos de compasión y las normas en fin de la más elemental justicia?, ¿qué, si leyendo obras de ficción o de no ficción que ilustran la bondad y el recto proceder, terminara actuando conforme a esos ideales?<br><br>
      
      En efecto, sólo se le abrirían las puertas del manicomio.<br><br>
      
      Un hospital psiquiátrico aguardaría con los brazos abiertos y con camisa de fuerza almidonada a quien creyera, ja, que no hay trecho entre el dicho y el hecho.<br><br>
      
      Pues igual le pasa a ese ser nacido de la convicción de don Alonso Quijano de que es posible imponer al presente los ideales de un pasado. Don Quijote, hijo legítimo de don Alonso Quijano el Bueno y, por ende, hijastro de don Miguel de Cervantes Saavedra, es producto de la conversión y de la convicción de un lector de libros y novelas de caballerías.<br><br>
      
      Inconforme por linaje, inconforme de abolengo, es además un anacrónico: quiere revivir un tiempo ido. Su método de evasión se erige sobre la voluntad de imponer los ideales de tal época.<br><br>
      
      Tal anacronía parece provenir de la nostalgia de una época de oro. No obstante, lejos de hacer de él un reaccionario, esa nostalgia lo catapulta al mañana; a un futuro que está por nacer pero que viene torcido, subyugado por perversos encantadores; a un futuro que se anuncia en imprentas y en una cabeza parlante predecesora de la radiotransmisión, así como en molinos de viento y de agua que amenazan con jubilar a Rocinante y al burro como fuerzas de tracción.<br><br>
      
      Por cierto, en el pasaje de unos batanes que también preludian el futuro, Sancho reacciona con miedo mientras don Quijote responde con delirios y anhelo de hazañas; por tanto cabe preguntar, ¿quién está más fuera de sus cabales y en menor consonancia con la realidad?, ¿un Quijote que transustancia en gigantes una maravilla tecnológica auditiva o un Sancho que, ateniéndose al sentido común y a lo ya visto, se deja ganar del cuerpo a causa de lo inaudito (lo nunca oído)?<br><br>
      
      En la realidad, en un mundo decadente donde las sopas del menú sólo eran la marginación para los más, el tedio para los menos y la grisura para todos, surgían personajes reales contrapuestos a don Quijote y complementarios a éste, tipos sociales que se trasvasaban a la literatura y llegaban a ser incluso material de testimonio: los pícaros. Estos marginados sociales respondían a la hostilidad del medio con no menos hostilidad; empero trataban de amoldarse a dicho medio.<br><br>
      
      El pícaro buscaba sincronizarse con el mundo que lo expulsaba. Se volvía acomodaticio y arribista, se conformaba, era trepador. Don Quijote, por el contrario, era inconforme y mostraba su rechazo regresando la vista atrás, hacia un mundo que quizá nunca había existido. El pícaro era realista; el caballero cervantino, idealista. Aquél se sincronizaba. Éste era anacrónico: antes que hacer prédica contra las malas costumbres se evadía para introducir ficciones que arreglaran la realidad. Y entre el pícaro y el caballero, un poco ambos, pero sin ser ninguno de ellos, estaba el aspirante a gobernar una isla (en efecto: en cierta dosis, sólo en cierta dosis, Sancho parece encarnar y de paso redimir de moralinas literarias al pícaro).<br><br>
      
      Creyendo o fingiendo creer, viviendo o representando cada escena que protagoniza, don Quijote se sitúa en un plano que ni la generalidad de la gente comparte ni las normas sociales admiten. Es un ser y un parecer anacrónico, se halla fuera del tiempo e insiste en su postura, una postura falsa para casi todos los otros pero en la que persevera, con la complicidad de Sancho y con el amparo del azar.<br><br>
      
      Uno de los remedios para reducir al loco es hacerse pasar por su igual. Enmascararse. Eso es lo que intentó, con buena fe y en sociedad, el ba­chiller Sansón Carrasco. No obstante, su fingimiento, su hacerse paralelo, par, pareja, resultó fallido. A fin de volver al redil a don Alonso Quijano, se disfrazó de caballero y lo retó a duelo para que, en condición de vencido, aceptara volver a su lugar de La Mancha. Pero el ardid, de entrada, no resultó. El Caballero de los Espejos fue derrotado y entonces tuvo que reencarnar, una dualidad más, en el Caballero de la Blanca Luna. Don Quijote venció al espejo pero caerá ante la advocación de la Luna, tal vez porque, aunque también espejo, la Luna no refleja un rastrero planeta sino lo más alto del cielo planetario: el Sol. </p>
      
    <h4>vii </h4>
    <p>Cervantes, como Quijano o Quijada o Quesada o Quejana, sufrió en carne propia la crisis y la extinción de los ideales caballerescos. Pero no sólo eso, también atestiguó la decadencia de las novelas de caballería. En este sentido su condena a ellas es sincera y su afán de satirizarlas es incuestionable. Aunque cabe subrayar que si en términos generales la voz narrativa siempre descalifica en masa a este género de literatura, a la hora de los recuentos —tanto en la voz de don Quijote como en las de otros personajes—, el autor no sólo salva sino hasta encomia ciertas obras en particular, de las cuales algunas siguen circulando por carriles de alta velocidad en nuestros días, como <em>Amadís de Gaula</em>, <em>Tristán de Leonís</em>, <em>Tirante el Blanco</em>, <em>Las sergas de Esplandián</em>, <em>Oliveros de Castilla</em>, <em>Palmerín de Inglaterra</em> y <em>Lanzarote del Lago</em>.<br><br>
    
      Y no es menos templada su defensa de lo que sí vale del género caballeresco: los ideales. De ahí que, al revés del pseudonominado Alonso Fernández de Avellaneda, autor de la segunda parte apócrifa del Quijote, Cervantes no le tire a ridiculizar a don Quijote ni a Sancho. Así, cuando llega al extremo de la caricatura, hace que Sancho contrapuntee un fuego con otro y consagre el exactísimo mote de Caballero de la Triste Figura, de modo tal que, asestándole un apodo que ni mandado a hacer, el escudero salva de la caricatura a su amo.<br><br>
      
      Ahora bien, en este filo entre la ridiculización y el homenaje, aparece la evidencia de otra dualidad. Porque no es lo mismo la novela caballeresca que el libro de caballería. La caballería, idealizada o no con el paso del tiempo, se ejerció en la realidad. Y encuentra tal vez su primer surtidor de temas en un Arturo más o menos histórico con sus caballeros de la mesa redonda, y en un Chrétien de Troyes que los recupera a fines del siglo xii. Ese toque de fantasía influyó en la realidad, al grado de que para el siglo xiv hubo quien como Eduardo iii de Inglaterra, el iniciador de la Guerra de los Cien Años contra Francia, pretendió modelar su vida y su política conforme a la literatura caballeresca. No le fue del todo bien en el modelaje a don Eduardo, pero su contexto aún era propicio. Así que todavía en el siglo xv el sueño era viable, sensato, alcanzable; había lo que Martín de Riquer llama &ldquo;vida caballeresca&rdquo;.<br><br>
      
      Los caballeros despertaban respeto y admiración con su halo de leyenda y sus currículos de tantos más combates singulares ganados, tantas honras y tantos puentes defendidos, tantas cartas de batalla sustentadas; lejos de atascarse en el incipiente mundo del poderoso caballero don Dinero o de quedar en los márgenes del olvido, los miembros del exclusivo club de la caballería andante equivalían a las actuales estrellas del deporte y la farándula. Pero su existencia poco a poco fue cediendo terreno a la ilusión; resbaló de reversa a lo ficticio, al entretenimiento antes que al pingüe negocio de la guerra. Se marchó, no sin legar una cuantiosa constancia de esas ejemplares vidas sobre cuya acción se habían elaborado códigos de honor, normatividades y protocolos: toda una cultura caballeresca codificada en libros de caballería, libros que más que narrar hazañas dictaban normas, ofrecían descripciones e imaginerías heráldicas, descifraban genealogías: hacían historia.<br><br>
      
      En suma, hubo caballeros de carne y hueso, inspirados en cantares de gesta. A su vez, estos caballeros inspiraron las novelas caballerescas de las que a principios del xvi el <em>Amadís de Gaula</em> y su correspondiente cauda vendrían a ser el principal venero. Alonso Quijano, pues, nace con un siglo de atraso, cuando ya la novedad caballeresca ha comenzado a oler chistoso, como diría Frank Zappa. El hacer caballeresco que había nacido de los libros retornó a ellos con más vuelo onírico, derivando en pura novelería de buena, mediana y mala calidad. El hacer caballeresco había dejado de ser oficio de nobles para derivar en recurso de desheredados, como Cortés, Valdivia, Pizarro y el resto de conquistadores del continente a donde Cervantes quiso ser destinado; conquistadores que si en algo no pensaron fue en el ideal de la justicia.<br><br>
      
      Si don Quijote, como esos perros de presa, sólo hubiera querido buscar aventuras y cubrirse de gloria, por amor a Dulcinea y a la fama o al dinero, no habría dejado de ser una figura cómica, muy cómica, divertidísima. Pero la cuestión va más allá de la comicidad y de la diversión. El discurso de don Quijote, repetido una y otra vez, se plasma en su deseo de enderezar lo torcido (dicho en su habla: desfacer tuertos), poner el mundo derecho, alinearlo, curarlo, sanar esas torceduras del esqueleto de la sociedad. En don Quijote hay un deseo justiciero, un sentimiento filantrópico. Eso propicia la lucidez de pensamiento tan alabada y reconocida por, entre otros, don Diego de Miranda el del verde gabán y por el hijo de éste, un poeta.<br><br>
      
      Ese discurso, equilibrado con las desorbitadas aventuras para eludir el rollo solemne que lo arrancaría de los brazos del lector de los siglos posteriores, confiere a don Quijote su calidad heroica, su esencia de loco raro, de loco tan gracioso como conmovedor, tan cómico como abismador, tan genial y contemporáneo como el serio Buster Keaton o como el vagabundo de las mejores cintas de Chaplin.<br><br>
      
      Sancho Panza le ruega a don Quijote que desista de enfrentar a los leones. Hace acopio de lógica y le discute que, comparada con ésta, las aventuras de los molinos de vientos y la pavura de los batanes resultarán pan comido. Pero don Quijote no cede. Contesta que es el miedo el que hace ver todo demasiado grande a Sancho, mas si acaso llegara a morir le encarga lo acordado: dar aviso y noticia a Dulcinea.<br><br>
      
      ¿Leoncitos a él? ¿A él leoncitos y a tales horas?<br><br>
      
      Mientras el leonero abría la puerta de la primera jaula, la del león macho, don Quijote todavía estaba decidiendo qué sería mejor, si combatir a pie o a caballo. Decidió hacerlo a pie, no fuera a ser que Rocinante se asustara. Así que se apeó, aventó la lanza, abrazó el escudo, echó mano a su arma y se acercó paso a paso al carro.<br><br>
      
      Sin embargo conviene preguntar a qué horas se refiere don Quijote al decir &ldquo;a tales horas&rdquo;. ¿A una hora del día, a una época, al momento de la novela en que ocurre esta acción? No lo sabemos con exactitud. También ignoramos en qué momento del día ocurre este episodio. Presumimos que hay buena luz, pues con esa claridad lo describe el narrador. Mañana o tarde. Pero, ¿y no podría ser que don Quijote se refiriera a lo que ahora llamaríamos momento histórico?<br><br>
      
      ¿O se refiere, antes que a cualquier horario astronómico, a su reloj existencial? Don Quijote ya no tiene espacio ni tiempo para dudas; no le cabe cobardía, no le cabe recular. Es la hora de la prueba, de la prueba personal. Ser o no ser, diría un antedicho contemporáneo. ¿Leoncitos a mí cuando ya soy parte de la historia, cuando ya logré pasar de la ficción a la realidad, cuando mis hazañas andan de boca en boca, de oído en oído y de ojo en ojo? ¿Leoncitos a mí cuando me están observando miríadas de pupilas, de lectores verdaderos y de un público atento que se reúne en las plazas de las villas o en un aposento familiar a escuchar la lectura de mis jamás antes pensadas osadías?</p>
      
    <h4>viii </h4>
    <p>En el cuarto del fondo de una casa de abuelos, un niño se pasmaba. Ese niño era, desde mi punto de vista, el lector más importante de los siglos pasados y por venir. Quizá esto de la importancia del ego resulte anacrónico. No lo sé. Pero no estamos hablando de un caso particular sino del anacronismo mayor.<br><br>
    
      La anacronía de don Quijote ya ha ocupado toda una primera parte y dieciséis capítulos de la segunda sin que haya habido algo más que locura, sincera o fingida; sin que haya habido otra cosa que cobardías mal argumentadas o poco convincentes; sin que haya habido, en fin, sino fingimiento y en último análisis ridículo o derrotas. Porque en todas las aventuras de don Quijote hay una suerte de derrota: los molinos lo derriban, la circunstancia lo vapulea, a él o a su escudero o a ambos. <em>Item</em> más: el valiente, el casto, el fiel, el consecuente, nunca comprueba a cabalidad tales virtudes; siempre flaquea, siempre enseña las costuras, no es del todo loco ni del todo se apega al ideal caballeresco. Para mi gusto, para el gusto que me han dejado todas mis lecturas del <em>Quijote</em>, hasta el capítulo diecisiete lo único que puedo concluir es que no hay loco que trague lumbre.<br><br>
      
      Hasta entonces, don Quijote parece no ser ni más ni menos que cualquier ser humano excéntrico. Revela grandeza pero también pequeñez. Prodigalidad pero también miseria. Espiritualidad y caos. Sin embargo he aquí que acaece la aventura de los leones. Y en ella no hay engaño. El león es de verdad, como bien se lo hacen ver Sancho, el Caballero del Verde Gabán y el leonero mismo.<br><br>
      
      En este episodio no hay mediaciones, no hay &ldquo;locura&rdquo; ni delirio; tampoco hay el recurso de una posible ensoñación, como cabe interpretar en el pasaje de la Cueva de Montesinos. El león es león, lo mismo que la leona, y ambos están hambrientos, y don Quijote, loco o no loco, sabe bien que se trata de fieras, y quiere luchar con ellas.<br><br>
      
      ¿Que qué hizo el león al ver a don Quijote?</p>
      
    <blockquote>Lo primero que hizo fue revolverse en la jaula, donde venía echado, y tender la garra, y desperezarse todo; abrió luego la boca y bostezó muy despacio, y con casi dos palmos de lengua que sacó fuera se despolvoreó los ojos y se lavó el rostro; hecho esto sacó la cabeza fuera de la jaula y miró a todas partes con los ojos hechos brasas, vista y ademán para poner espanto a la misma temeridad. Sólo don Quijote le miraba atentamente deseando que saltase ya del carro y viniese con él a las manos, entre las cuales pensaba hacerle pedazos.</blockquote>
    
    <p>Al ver que el león no ataca como lo haría cualquier fiera voraz que se respete, don Quijote insiste.<br><br>
    
      El león, Cervantes lo cuenta con divino donaire, no aceptó el desafío. Nuestro caballero pidió al leonero que provocara a la fiera hasta hacerla salir y con ello remacha su victoria, la única, la indispensable para que no perdiéramos la fe en los caballeros andantes.<br><br>
      
      Y eso fue todo. Como muy bien canta el autor, hasta este extremo llegó la locura de don Quijote.<br><br>
      Sólo gracias a este capítulo podemos decir que no todo le salió mal a don Quijote y que no siempre desencajó en la realidad. <br><br>
      
      La victoria de don Quijote, aquí, por fin, fue rotunda. Es decir redonda y a profundidad, como estocada de matador valiente. Cierto que mediaron el talante del retador, el temperamento del adversario y el azar, factores todos que intervienen en todo triunfo y en toda derrota desde que el mundo es mundo. Pero precisamente por eso, porque en esta aventura intervinieron todos y cada uno de los factores de cualquier circunstancia normal entre seres normales regidos por la naturaleza y la sociedad, te puedo decir sin temor a equivocarme, oh lector, que ésta fue la primera y única y grande y polar victoria de don Quijote: el momento supremo del conflicto de este individuo con su realidad.<br><br>
      
      Aquí sí que ensarta su hebra. Y de dos modos. El uno, cobrando fama, y ese es otro de los muchos méritos de la segunda parte: consagrar a don Quijote otorgándole la celebridad que buscaba, incrustándolo en la realidad. El otro, haciéndolo vencedor en esa competencia contra reloj que los leones significan: ser valiente resulta proeza grande en un mundo erigido por la cobardía y por la ruindad.<br><br>
      
      Sin este triunfo no se podría hablar sin sonrojo del gran triunfo de don Quijote y de Cervantes.</p>
      
    <h4>ix </h4>
    <p>El ideal de la justicia como empresa individual debió de ser uno de los principales ideales de la caballería. Pero, ¿hubo realmente justicia alguna vez? ¿Alguna vez se cumplió el ideal? Y si así fue, ¿por cuánto tiempo lo fue? ¿Perduró al menos un lapso digno como para tomarlo de modelo y referirse a él en términos de la época dorada de la justicia? ¿O sólo sucedió en ráfagas?<br>
      Con esas preguntas me sitúo en dirección de la Ucronía. No existió en ningún tiempo algo llamado justicia. Tan disparatados fueron los caballeros de la historia real como el anacrónico don Quijote de la historia ficticia. La justicia no ha sido todavía posible en el tiempo social. Y don Quijote mismo, al equipararse en su utopía justiciera con el caballero antiguo que le sirvió de modelo, deja de ser anacrónico, busca lo que su ancestro buscó: un sueño compartible, un tiempo fuera del tiempo, una ucronía.<br><br>
      Quien no se somete a la realidad es utópico y ucrónico, busca lo que no hay, pero al buscarlo empieza a hacerlo parte de la realidad, empieza a volverlo posible. ¿En qué medida? No desde luego para revivir lo que no existió jamás. Sí para devolverle brillo al sueño más querido; para recuperarlo y hacerlo compartible, afín a lo mejor de cada lector de cada tiempo y cada espacio.<br>
      Don Miguel de Cervantes Saavedra buscó evadir su realidad; don Quijote buscó lo mismo aunque en y hacia una dimensión superior: evadirse para transformar el mundo, para penetrarlo con las armas ideales de la andante caballería. Y lo consiguió. Don Quijote consiguió a plenitud lo que se había propuesto. No en la primera parte sino diez años después. Porque Cervantes, el medio, el<em> medium</em> de tal realización, había metido a su personaje literario en una realidad sin ideales.<br>
      Cuando, en la segunda parte, don Quijote regresa, cabalga y sorprende a quienes desde la tierra lo miran, comenta con exageración pero sin demencia que ya circula un libro sobre sus aventuras. La gente, los nobles y los forajidos, es decir los estamentos sociales cuyo tiempo es propicio, lo identifican y le acomodan escenarios para que él viva sus aventuras: crean un mundo a la medida de él y de Sancho.<br><br>
      ¡La caballería andante existe y nosotros somos muestra de ello! Ellos pueden gritar tal despropósito porque tienen la base para decirlo, tienen su existencia misma: existen, son vistos, admirados o tolerados, están ahí, habitan y ocupan un espacio aun siendo el no espacio, aun estando fuera del tiempo coinciden en el tiempo común, en los comunes y corrientes tiempos. Son lo que no se realiza en ningún tiempo: son.<br><br>
      Don Quijote comienza siendo anacrónico pero termina erigiéndose en una propuesta ucrónica. En un sueño compartible.<br><br>
      Volviendo al tiempo y al espacio que me tocó, en febrero de 2005, durante la fiesta del cumpleaños setenta y cinco de mi madre, la prima mayor me contó un sueño que había tenido de niña.<br>
      —Entrábamos tú y yo —dijo— en una especie de torreón con vitrales de colores donde había un baúl, un trono tapizado en terciopelo y una mesa con un objeto misterioso encima. Supimos que esto último era un candelero de piedras preciosas porque retiraste el mantel de lino que lo cubría para echarlo sobre los hombros, y aunque tenía manchas de betabel me sentí una diosa griega envuelta en una túnica inmaculada. Estábamos felices. Tú sacabas del baúl montones de monedas de oro que producían el sonido de tu risa. De pronto oímos gritos y salimos a un bosque tupido. Alguien muy viejo nos perseguía por un laberinto de andadores apenas visibles entre la maleza. En las cuarteadas baldosas había filigrana de musgo y restos de fruta picoteada por gorriones...<br><br>
      —No fue un sueño —la interrumpí.<br><br>
      Para convencerla introduje datos precisos: los nombres de la calle y de los propietarios del huerto, así como el color de la ropa que ella vestía. Pero lo único que pudimos suscribir, antes de ir juntos a abrazar a mi cinco veces quinceañera madre, fue el acuerdo de poseer un sueño compartible. Un sueño: no algo desfasado sino ajeno al tiempo. Ajeno al tiempo pero de nuestra propiedad. Una propiedad que ahora deja de ser exclusiva porque la comparto contigo, paciente lector, a propósito de ese sueño también ajeno al tiempo que podemos compartir con don Quijote.<br><br>
      Todos los lectores de <em>El ingenioso hidalgo don Quijote de la Mancha</em>, autores por contagio, se pueden arrogar el mérito de formar parte de la ucronía; pueden entrar fuera del tiempo para imprimirle posibilidades y para luchar no por lo que no pudo ser sino por lo que hace falta: para tender y defender el puente por donde se pasa de la nostalgia de una realidad inexistente al deseo de realidades imposibles pero necesarias.<a name="_GoBack"></a></p>

<p style="text-align:center;">
	<img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Agustín Ramos es un narrador y ensayista. Nació en Tulancingo, Hidalgo, en 1952. Hizo estudios de Lenguas hispánicas en la Facultad de Filosofía y Letras de la UNAM. Ha colaborado en diversas publicaciones como La Cultura en México, La Jornada Semanal, Letras Libres y El Financiero. Entre sus libros se cuentan <em>Al cielo por asalto</em> (1979), <em>La vida no vale nada</em>(1982), <em>Ahora que me acuerdo</em> (1985) y <em>Como la vida misma</em> (2005).</div>
</section>


<?php include 'footer.php' ?>
