<?php include 'header.php' ?>


<section class="titulo">
	<article class="">
		<h3>Número 74</h3>
		<h1>Para una teoría de la potencia destituyente</h1>
		<h2>Giorgio Agamben</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
<em></em>
<p><strong>1.</strong> La arqueología de la política que fue puesta en cuestión por el proyecto &ldquo;Homo sacer&rdquo; no tenía como propósito criticar o corregir este o aquel concepto, esta o aquella institución de la política occidental; de lo que se trataba, más bien, era de revocar en la cuestión el lugar mismo así como la estructura originaria de la política, intentando así traer a la luz el <em>arcanum imperii</em> que constituía de algún modo su fundamento y que había permanecido, a la vez, plenamente expuesto y tenazmente escondido dentro de ella.<br><br>
La identificación de la nuda vida como el referente principal de la política y de lo que con ella se pone en juego fue entonces el primer acto de la investigación. La estructura originaria de la política oc­cidental consiste en una <em>ex-ceptio</em>, en una exclusión inclusiva de la vida humana que toma la forma de la nuda vida. Obsérvese la particularidad de esta operación: la vida no es en sí misma política —por eso debe ser excluida de la ciudad— y sin embargo, es precisamente la <em>exceptio</em>, la exclusión-inclusión de este Impolítico, lo que funda el espacio de la política.<br><br>
Es importante no confundir la nuda vida con la vida natural. Es a través de la división y la captura en el dispositivo de la excepción que la vida asume la forma de la nuda vida, es decir, de una vida que ha sido escindida y separada de su forma. Es en este sentido como debe entenderse, al final de <em>Homo sacer i</em>, la tesis según la cual &ldquo;la prestación fundamental del poder soberano es la producción de la nuda vida como elemento político originario&rdquo;. Y es esta nuda vida (o vida &ldquo;sacra&rdquo;, si <em>sacer</em> designa en primer lugar una vida que puede ser asesinada sin cometer homicidio) lo que, en la máquina jurídico-política de Occidente, sirve como umbral de articulación entre <em>zoé</em> y <em>bios</em>, vida natural y vida políticamente cualificada. Y no será posible pensar otra dimensión de la política y de la vida si antes no logramos desactivar el dispositivo de la excepción de la nuda vida.</p>

<p><strong>2.</strong> Durante la investigación, sin embargo, la estructura de la excepción que había sido definida respecto a la nuda vida se reveló en general como constituyente de todos los aspectos de la estructura del <em>arché</em>, tanto en la tradición jurídico-política como en la ontología. De hecho, no es posible comprender la dialéctica del fundamento que desde Aristóteles define a la ontología occidental, si no se comprende que ésta funciona como una excepción en el sentido apenas expuesto. La estrategia es siempre la misma: algo es dividido, excluido y empujado hacia el fondo y, precisamente a través de esta exclusión, es incluido como <em>arché </em>o fundamento. Es así para la vida, que en palabras de Aristóteles &ldquo;se dice de muchas maneras&rdquo; —vida vegetativa, vida sensitiva, vita intelectiva, siendo la primera de ellas excluida de modo que pueda servir como fundamento para todas las demás—, pero es así también para el ser, que se dice igualmente de muchas maneras, siempre que una de ellas haya sido separada para fungir como fundamento.<br><br>

  Es posible, después de todo, que el mecanismo de la excepción se encuentre vinculado constitutivamente al acontecimiento del lenguaje que coincide con la antropogénesis. De acuerdo con la estructura de la presuposición que hemos reconstruido, el lenguaje, adviniendo, excluye y separa de sí lo no lingüístico y, con el mismo gesto, lo incluye y captura como aquello con lo que éste está siempre ya en relación. La <em>ex-ceptio</em>, la exclusión inclusiva de lo real del <em>logos</em> y en el <em>logos </em>es, entonces, la estructura original del acontecimiento de lenguaje.</p>
  
<p><strong>3.</strong> En <em>Estado de excepción</em>, la máquina jurídico-política de Occidente fue entonces descrita como una doble estructura formada por dos elementos heterogéneos y, sin embargo, íntimamente coordinados: uno normativo y jurídico en sentido estricto (la <em>potestas</em>) y uno anómico y extrajurídico (la <em>auctoritas</em>). El elemento jurídico-normativo<em>, </em>en el que parece residir el poder en su forma eficaz y efectiva, necesita, sin embargo, del elemento anómico para poder ser aplicado a la vida; por otro lado, la <em>auctoritas</em> sólo puede afirmarse y cobrar sentido si se encuentra en relación con la <em>potestas</em>. El estado de excepción es el dispositivo que debe, en última instancia, articular y mantener juntos los dos aspectos de la máquina jurídico-política, instituyendo un umbral de indecidibilidad entre anomia y <em>nomos</em>, entre vida y derecho, entre <em>auctoritas</em> y <em>potestas</em>. <br><br>
	
  Mientras los dos elementos permanezcan como correlatos, pero conceptual, temporal y personalmente diferenciados —como la contraposición entre senado y pueblo en la Roma republicana, o entre poder espiritual y poder temporal en la Europa medieval— su dialéctica puede en cierto sentido funcionar. Sin embargo, cuando los dos elementos tienden a coincidir en una sola persona, cuando el estado de excepción en el que ambos se indeterminan se vuelve la regla, entonces el sistema jurídico-político se transforma en una máquina letal.<br><br>

  En <em>El Reino y la Gloria</em>, una estructura análoga fue traída a la luz en la relación entre reino y gobierno y entre inoperosidad*<a href="#_ftn1" name="_ftnref1" title=""> </a>y gloria. La gloria aparecía aquí como un dispositivo que busca capturar en el interior de la máquina económico-gubernamental aquella inoperosidad de la vida humana y divina que nuestra cultura parece incapaz de pensar y que, sin embargo, no cesa de ser invocada como el misterio último de la divinidad y del poder. Esta inoperosidad es, para la máquina, tan esencial que tiene que ser capturada y mantenida a toda costa en su centro bajo la forma de la gloria y de las aclamaciones que, todavía hoy, no cesan de cumplir con su función doxológica a través de los <em>mass media</em>.<br><br>
  
  Del mismo modo, unos años antes, en <em>Lo abierto</em>, la máquina antropológica de Occidente fue definida a través de la división y la articulación, al interior del hombre, de lo humano y lo animal. Al final del libro, el proyecto para una desactivación de la máquina que gobierna nuestra concepción del hombre exigía no ya buscar nuevas articulaciones entre lo animal y lo humano, sino más bien la exposición del vacío central, del hiato que separa —dentro del hombre— al hombre y el animal. Aquello que —una vez más bajo la forma de la excepción— había sido separado y después articulado conjuntamente en la máquina, tenía que ser restituido a su división para que una vida inseparable, ni animal ni humana, pudiera eventualmente aparecer.</p>
  
<p>4. En todas estas figuras está operando un mismo mecanismo: el <em>arché </em>se constituye escindiendo la experiencia facticia*<a href="#_ftn2" name="_ftnref2" title=""> </a>y rechazando hacia el origen —es decir, excluyendo— una mitad de ella para después rearticularla con la otra, incluyéndola como fundamento. De este modo la ciudad se funda sobre la escisión de la vida en nuda vida y vida políticamente cualificada, lo humano se define a través de la exclusión-inclusión de lo animal, la ley a través de la <em>exceptio</em> de la anomia, el gobierno a través de la exclusión de la inoperosidad y de su captura en forma de gloria.<br><br>

  Si tal es la estructura del <em>arché</em> en nuestra cultura, entonces el pensamiento se encuentra aquí frente a una dura tarea. No se trata de pensar, como en general hasta ahora se ha hecho, nuevas y más eficaces articulaciones de los dos elementos, jugando las dos mitades de la máquina una contra la otra. Tampoco se trata de regresar arqueológicamente a un inicio más originario: la arqueología filosófica no alcanza otro inicio más que aquel que puede, eventualmente, resultar en la desactivación de la máquina (en este sentido la filosofía primera es siempre filosofía última).<br><br>
  
  El problema ontológico-político fundamental es hoy, no la obra, sino la inoperosidad, no la búsqueda afanosa e incesante de una nueva operatividad, sino la exhibición del vacío incesante que la máquina de la cultura occidental resguarda en su centro.</p>
  
<p>5. En el pensamiento de la modernidad, los cambios políticos radicales han sido pensados a través del concepto de un &ldquo;poder constituyente&rdquo;. Hoy en día poder constituido presupone en su origen a un poder constituyente que, a través de un proceso que tiene comúnmente la forma de una revolución, lo actualiza en el ser y lo garantiza. Si nuestra hipótesis sobre la estructura del <em>arché</em> es correcta y si hoy el problema ontológico fundamental no es la obra, sino la inoperosidad, y si ésta puede, sin embargo, atestiguarse sólo respecto a una obra, entonces el acceso a una figura diferente de la política no podrá tener la forma de un &ldquo;poder constituyente&rdquo;, sino más bien la de algo que podemos provisionalmente llamar &ldquo;potencia destituyente&rdquo;. Y si al poder constituyente corresponden revoluciones, motines y nuevas constituciones, es decir, una violencia que funda o constituye un nuevo derecho, para la potencia destituyente se deben pensar estrategias completamente diferentes, cuya definición es la tarea de la política que viene. Un poder que sólo ha sido derribado con una violencia constituyente resurgirá tomando otra forma, en la incesante, inconsignable, desolada dialéctica entre poder constituyente y poder constituido, violencia que funda el derecho y violencia que lo conserva.<br><br>

  La paradoja del poder constituyente es, precisamente, que sin importar lo mucho que los juristas subrayen en mayor o menor medida su heterogeneidad, éste permanece inseparable del poder constituido, con el que forma un sistema. Así, por un lado, se afirma que el poder constituyente se sitúa fuera del Estado, que existe sin él y que continúa permaneciendo externo respecto al Estado también después de su constitución, mientras que el poder constituido que emerge no existe más que en el Estado; pero, por el otro, este poder originario e ilimitado —que podría, como tal, amenazar la estabilidad del ordenamiento— termina necesariamente por ser confiscado y capturado en el poder constituido al que dio origen y en el cual no sobrevive más que como el poder de revisar la constitución. Incluso Sieyès, quizá el teórico más intransigente respecto a la trascendencia del poder constituyente, debe, al final, limitar drásticamente su omnipotencia, no dejándole mayor existencia que aquella sombría del <em>Jury constitutionnaire</em>, al que está asignada la tarea de modificar, según procedimientos rigurosamente establecidos, el texto de la constitución.<br>
  Aquí parecen repetirse, en su forma secularizada, las paradojas con las que los teólogos debían medirse cuando afrontaban el problema de la omnipotencia divina. Ésta implicaba de hecho que Dios habría podido hacer cualquier cosa, incluyendo destruir el mundo que había creado o anular o subvertir las leyes providenciales con las que habría querido dirigir a la humanidad hacia la salvación. Para contener estas consecuencias escandalosas de la omnipotencia divina, los teólogos distinguieron entre potencia absoluta y potencia ordenada: <em>de potentia absoluta</em>, Dios puede hacer cualquier cosa; pero <em>de potentia ordinata</em>, es decir, una vez que ha querido alguna cosa, por eso mismo también su potencia se encuentra limitada.<br><br>
  
  Así como la potencia absoluta no es, en realidad, otra cosa que lo que se presupone para la potencia ordenada, eso que necesita para garantizar su propia validez incondicional, de igual modo puede decirse que el poder constituyente es aquello que el poder constituido debe presuponer para darse un fundamento y legitimarse. De acuerdo con el esquema que hemos descrito tantas veces, constituyente es aquella figura del poder en la que una potencia destituyente es capturada y neutralizada, asegurando así que ésta no pueda dirigirse contra el poder o el orden jurídico como tal, sino sólo contra una determinada figura histórica suya.</p>
  
<p>6. Por eso el capítulo tres de la primera parte de <em>Homo sacer i</em> afirmaba que la relación entre poder constituyente y poder constituido es igual de compleja que aquella que Aristóteles instituye entre potencia y acto y que intentaba esclarecer la relación entre los dos términos como una relación de bando o abandono. El problema del poder constituyente muestra aquí sus irreductibles implicaciones ontológicas. Potencia y acto no son más que los dos aspectos del proceso de autoconstitución soberana del ser, en el que el acto se presupone como potencia y ésta se mantiene en relación con aquél a través de su propia suspensión, su propio poder no pasar al acto y, por otra parte, el acto no es más que una conservación y una &ldquo;salvación&rdquo; (<em>soteria</em>) —en otras palabras, una <em>Aufhebung</em>— de la potencia.</p>

<p>A la estructura de la potencia, que se mantiene en relación con el acto precisamente a través de su poder no ser, corresponde la del bando soberano, que se aplica a la excepción desaplicándose. La potencia (en su doble aspecto de potencia y potencia de no) es el modo a través del cual el ser se funda soberanamente, es decir, sin nada que lo preceda ni determine que no sea, precisamente, su propio poder no ser. Y soberano es aquel acto que se realiza simplemente eliminando su propia potencia de no ser, dejándola ser, donándose a sí misma. (Agamben, p. 54).<br><br>

  De ahí la dificultad para pensar una potencia puramente destituyente, es decir, íntegramente separada de la relación soberana de bando que la vincula al poder constituido. El bando aparece aquí como la forma-límite de la relación, en la que el ser se funda manteniéndose en relación con un inconexo, que no es, en realidad, más que una presuposición de sí mismo. Y si el ser no es más que el ser &ldquo;a-bandono&rdquo; —es decir, el abandonado a sí mismo— de lo ente, entonces también categorías como la de &ldquo;dejar-ser&rdquo;, a través de la cual Heidegger intentó salir de la diferencia ontológica, permanecen internas a la relación de bando.<br><br>
  
  Por eso el capítulo sólo podía cerrarse enunciando el proyecto para una ontología y una política libradas de toda figura de la relación, incluso la figura de la forma-límite de la relación que supone el bando soberano:</p>

<blockquote>Sería necesario pensar la existencia de la potencia sin ninguna relación con el ser en acto —ni siquiera en la forma extrema del bando y de la potencia de no ser— y el acto ya no como cumplimiento y manifestación de la potencia; ni siquiera en la forma del don de sí y del dejar ser. Esto implicaría, sin embargo, nada menos que pensar la ontología y la política más allá de toda figura de la relación, aunque ésta sea la de la relación-límite del bando soberano. (<em>Ibid.</em>, p. 55).</blockquote>

<p>Sólo en este contexto sería posible pensar una potencia puramente destituyente, es decir, que no se resuelva nunca en un poder constituido.</p>
<p>א <em>Es la secreta solidaridad entre la violencia que funda el derecho y la violencia que lo conserva lo que Benjamin pensaba en su ensayo </em>Para una crítica de la violencia, <em>intentando definir una forma de violencia que escapara a esta dialéctica: &ldquo;Sobre una interrupción de este ciclo que se desarrolla en el ámbito de las formas míticas del derecho, sobre la destitución [</em>Entsetzung<em>] del derecho junto con aquellos poderes sobre los cuales se apoya (como éstos sobre aquél), y de manera definitiva, sobre la destitución de la violencia estatal, se funda una nueva época histórica&rdquo; (Benjamin, p. 202). Sólo es neutralizado </em>íntegramente<em> un poder que ha sido vuelto inoperoso y que ha sido depuesto a través de una violencia que no mira a fundar un nuevo derecho. Benjamin identificaba esta violencia —o, según el doble significado del término alemán </em>Gewalt<em>, este &ldquo;poder destituyente&rdquo;— con la huelga general proletaria, que Sorel oponía a la huelga simplemente política. Mientras la suspensión del trabajo en la huelga política es violenta, &ldquo;porque provoca [</em>veranlasst, <em>&ldquo;ocasiona&rdquo;, &ldquo;induce&rdquo;] sólo una modificación extrínseca de las condiciones de trabajo, la otra, como medio puro, está exenta de violencia&rdquo; (</em>ibid.<em>, p. 194). Ella, de hecho, no implica el retorno al trabajo &ldquo;luego de concesiones exteriores y algunas modificaciones de las condiciones laborales&rdquo;, sino la decisión de reanudar el trabajo sólo si éste ha sido </em>íntegramente<em> transformado y no es impuesto por el Estado, es decir, implica una &ldquo;alteración que este tipo de huelga no provoca [</em>veranlasst<em>], sino que más bien realiza [</em>vollzieht<em>]&rdquo; (</em>idem<em>.). En la diferencia entre </em>veranlassen<em>, &ldquo;inducir, provocar&rdquo;, y </em>vollziehn<em>, &ldquo;cumplir, realizar&rdquo;, se expresa la oposición entre el poder constituyente, que destruye y recrea siempre nuevas formas de derecho, sin jamás destituirlo definitivamente, y la violencia destituyente, que, en la medida en que depone de una vez por todas el derecho, inaugura inmediatamente una nueva realidad. &ldquo;De ahí que la primera de estas operaciones da existencia a un derecho, mientras que la segunda, en cambio, es anárquica&rdquo; (</em>idem.).<br><br>

  <em>Al inicio del ensayo, Benjamin define la violencia pura a través de una crítica de la relación que se da por hecho existe entre medios y fines. Mientras la violencia jurídica es siempre medio </em>—<em>legítimo o ilegítimo</em>—<em> respecto a un fin </em>—<em>justo o injusto</em>—<em>, el criterio de la violencia pura o divina no hay que buscarlo en su relación con un fin, sino en &ldquo;una distinción en la esfera de los medios, sin tener en cuenta los fines que </em>éstos persiguen&rdquo; (p. 179). <em>El problema de la violencia no es aquel, tantas veces perseguido, de identificar unos fines justos, sino el de &ldquo;individuar una violencia de otro tipo… que no se refiera en general a ellos como medio, sino de alguna otra manera&rdquo; (p. 196).</em> <br>
  <em>El problema aquí es la idea misma de instrumentalidad, que, a partir del concepto escolástico de &ldquo;causa instrumental&rdquo;, hemos visto caracterizar la concepción moderna del uso y la esfera de la técnica. Mientras éstas eran definidas por un instrumento que aparece como tal sólo en la medida en que es incorporado en la finalidad del agente principal, Benjamin tiene aquí en mente un &ldquo;medio puro&rdquo;, es decir, un medio que se muestra como tal, sólo en la medida en que se emancipa de toda relación con un fin. La violencia como medio puro no es nunca medio respecto a un fin: ella se testimonia sólo como exposición y destitución de la relación entre violencia y derecho, entre medio y fin.</em></p>
  
<p>7. Una crítica del concepto de relación ha sido sugerida en el capítulo 2.8 de la segunda parte de la presente investigación, a propósito del teorema agustiniano: &ldquo;toda esencia que se dice en modo relativo, es también algo exceptuando lo relativo&rdquo; (<em>omnis essentia quae relative dicitur, est etiam aliquid excepto relativo</em>). Se trataba, para Agustín, de pensar la relación entre unidad y trinidad en Dios, es decir, de salvar la unidad de la esencia divina sin negar su articulación en tres personas. Hemos mostrado que Agustín resuelve este problema excluyendo y al mismo tiempo incluyendo la relación en el ser y el ser en la relación. La fórmula <em>excepto relativo</em> ha de leerse aquí de acuerdo con la lógica de la excepción: lo relativo es al mismo tiempo excluido e incluido en el ser, es decir que la trinidad de las personas es capturada en la esencia-potencia de Dios, de modo tal que ésta se mantiene pero es diferente de aquélla. En palabras de Agustín, la esencia, que es y se dice en la relación, es algo que está fuera de la relación. Pero esto significa, de acuerdo con la estructura de la excepción soberana que hemos definido, que el ser es un presupuesto de la relación.<br><br>

  Podemos entonces definir la relación como aquello que constituye sus elementos presuponiéndolos, juntos, como separados. Así la relación deja de ser una categoría entre las otras y adquiere un rango ontológico especial. Tanto en el dispositivo aristotélico potencia-acto, como en la esencia-existencia de la teología trinitaria, la relación es inherente al ser según una ambigüedad constitutiva: el ser precede a la relación y existe fuera de ella, pero se encuentra siempre ya constituido a través de la relación e incluso en ella como su presupuesto.</p>
  
<p>8. Es en la doctrina escotiana del ser formal donde el rango ontológico de la relación encuentra su más coherente expresión. Por una parte, él retoma el axioma agustiniano y lo precisa en la forma <em>omne enim quod dicitur ad aliquid est aliquid praeter relationem</em> (&ldquo;aquello que se dice respecto a algo es algo fuera de la relación&rdquo; — <em>Op. Ox.</em>, i, d. 5, q. i, n. 18; <em>cf. </em>Beckmann, p. 206). La corrección muestra que lo que está en juego para Escoto es el problema de la relación como tal: si, como él escribe, &ldquo;la relación no está incluida en el concepto de absoluto&rdquo; (<em>ibid</em>.), lo que consigue es que el absoluto esté siempre ya incluido en el concepto de relación. Con una aparente inversión del teorema agustiniano, que trae a la luz la implicación que permanecía escondida, él puede por lo tanto escribir que <em>omne relativum est aliquid excepta relatione</em> (&ldquo;todo relativo es algo exceptuada la relación&rdquo; — <em>ibid.</em>, i, d. 26, q. i, n. 33).<br>
  Lo decisivo, en cualquier caso, es que para Escoto la relación implique una ontología, o sea una forma particular del ser, que él define con una fórmula que encontrará fortuna en el pensamiento medieval, como <em>ens debilissimum</em>: &ldquo;entre todos los entes la relación es un ser debilísimo, porque es solamente el modo de ser de dos entes uno respecto a otro&rdquo; (<em>relatio inter omnia entia est ens debilissimum, cum sit sola habitudo duorum</em> — <em>Super praed</em>., q. 25, n. 10). Pero esta forma ínfima del ser —que, en cuanto tal, es difícil de conocer (<em>ita minime cognoscibile in se</em> — <em>idem</em>.)— desem­peña, en realidad, en el pensamiento de Escoto —y, a partir de él, en la historia de la filosofía hasta llegar a Kant— una función constitutiva, porque ella coincide con la prestación específica de su genio filosófico, la definición de la distinción formal y del estatuto de lo trascendental.<br>
  Con la distinción formal Escoto ha pensado el ser del lenguaje, que no puede ser <em>realiter</em> diferente de la cosa que nombra, de otro modo no podría manifestarla y darla a conocer, pero debe tener alguna consistencia propia, de otro modo se confundiría con la cosa. Eso que se distingue de la cosa no <em>realiter</em>, sino <em>formaliter</em>, es su tener nombre: lo trascendental es el lenguaje.</p>
  
<p>9. Si a la relación corresponde un estatuto ontológico privilegiado, es porque en ella se expresa la misma estructura presuponente del lenguaje. Lo que afirma el teorema de Agustín es, de hecho, que &ldquo;todo aquello que se dice entra en una relación y, por lo tanto, es también otra cosa antes y afuera de la relación (es decir, es un inconexo que ha sido presupuesto)&rdquo;. La relación fundamental —la relación onto-lógica— pasa entre lo ente y el lenguaje, entre el ser y su ser dicho o nombrado. El <em>logos</em> es esta relación, en la que lo ente y su ser dicho son al mismo tiempo idénticos y diferentes, remotos e indistinguibles.<br><br>

  En este sentido, pensar una potencia puramente destituyente significa interrogar y revocar en la cuestión el estatuto mismo de la relación, manteniéndose abiertos a la posibilidad de que la relación ontológica no sea, en verdad, una relación. Esto significa confrontarse en un cuerpo a cuerpo decisivo con aquel ser debilísimo que es el lenguaje. Pero precisamente porque su estatuto ontológico es débil, el lenguaje, como Escoto había intuido, es dificilísimo de conocer y de aferrar. La fuerza casi invencible del lenguaje está en su debilidad, en su permanecer impensado y no-dicho en aquello que dice y en aquello de lo cual se dice.<br><br>
  
  Por eso la filosofía nace en Platón precisamente como un intento de ir al fondo de los <em>logoi</em>, y como tal, la filosofía tiene inmediatamente y desde el principio un carácter político. También por eso, con Kant, cuando lo trascendental cesa de ser aquello de lo que el pensamiento va al fondo y se vuelve, en cambio, la fortaleza en la cual el pensar se atrinchera, entonces la filosofía extravía definitivamente su relación con el ser y la política entra en una crisis decisiva. Una nueva dimensión para la política solamente se abrirá cuando los hombres —los seres que tienen el <em>logos</em> en la misma medida en la que son poseídos por él— vayan al fondo de esta debilísima potencia que los determina y que los implica tenazmente en un errar —la historia— que parece interminable. Sólo entonces —pero este &ldquo;entonces&rdquo; no es futuro sino que está siempre en curso— será posible pensar la política fuera de toda figura de la relación.</p>
  
<p>10. Así como la tradición de la metafísica siempre ha pensado lo humano en la forma de una articulación entre dos elementos (naturaleza y <em>logos</em>, cuerpo y alma, animalidad y humanidad), del mismo modo la filosofía política occidental siempre ha pensado lo político en la figura de la relación entre dos figuras que se trataba de mantener unidas: la nuda viday el poder, la casa y la ciudad, la violencia y el orden instituido, la anomia (la anarquía) y la ley, la multitud y el pueblo. Desde la perspectiva de nuestra investigación, tenemos en cambio que intentar pensar lo humano y lo político como aquello que resulta de la desconexión de estos elementos e investigar no el misterio metafísico de su conjunción, sino el misterio práctico y político de su disyunción.<br><br>

  Tenemos la definición de la relación como aquello que constituye a sus elementos presuponiéndolos, juntos, como separados. Así, por ejemplo, en las parejas viviente/lenguaje, poder constituyente/poder constituido, nuda vida/derecho, es evidente que los dos elementos se definen y se constituyen en todas las ocasiones mutuamente a través de su relación opositiva y, en cuanto tales, no pueden preexistir a ella; y, sin embargo, la relación que los une los presupone como separados. Lo que durante esta investigación hemos definido como bando es el vínculo, al mismo tiempo atractivo y repulsivo, que liga los dos polos de la excepción soberana.<br><br>
  
  Llamamos destituyente a una potencia capaz de deponer en cada ocasión las relaciones ontológico-políticas para hacer aparecer entre sus elementos un contacto (en el sentido de Colli, pp. 301-302). El contacto no es un punto de tangencia ni un <em>quid</em> o una sustancia en la cual los dos elementos se comunican: éste es definido solamente por una ausencia de representación, sólo por una cesura. Donde una relación es destituida e interrumpida, sus elementos estarán en este sentido en contacto, porque se exhibe entre ambos la ausencia de toda relación. Así, en el punto en el que una po­tencia destituyente exhibe la nulidad del vínculo que pretendía mantenerlos juntos, nuda viday poder soberano, anomia y <em>nomos</em>, poder constituyente y poder constituido se muestran en contacto sin ninguna relación; pero, por eso mismo, aquello que había sido separado de sí y capturado en la excepción —la vida, la anomia, la potencia anárquica— aparece ahora en su forma libre, íntegra y sin libaciones.</p>
  
<p>11. La proximidad entre la potencia destituyente y aquello que, durante esta investigación, hemos nombrado con el término &ldquo;inoperosidad&rdquo; se muestra aquí claramente. En ambas está en juego la capacidad de desactivar y volver inoperante algo —un poder, una función, una operación humana— sin simplemente destruirlo, sino más bien liberando las potencialidades que en él habían quedado inactuales y permitiendo así un uso diferente.<br>

  Un ejemplo de una estrategia destituyente y no destructiva ni constituyente es la de Pablo ante la ley. Pablo expresa la relación entre el mesías y la ley con el verbo <em>katargein</em>, que significa &ldquo;volver inoperante&rdquo; (<em>argos</em>), &ldquo;desactivar&rdquo; (el <em>Thesaurus</em> de Estienne lo explica como <em>reddo aergon et inefficacem, facio cessare ab opere suo, tollo, aboleo</em>). Así Pablo puede escribir que el mesías &ldquo;volverá inoperante [<em>katargese</em>] todo poder, toda autoridad y toda potencia&rdquo; (<em>i</em><em> Cor</em>., 15, 24) y, al mismo tiempo, que &ldquo;el mesías es el <em>telos</em> [es decir, fin y cumplimiento] de la ley&rdquo; (<em>Rom</em>., 10, 4): inoperatividad y cumplimiento aquí coinciden perfectamente. En otro pasaje dice de los creyentes que ellos han sido &ldquo;vueltos inoperosos [<em>katargethemen</em>] respecto a la ley&rdquo; (<em>Rom</em>., 7, 6). Las traducciones frecuentes de este verbo como &ldquo;destruir, anular&rdquo; no son correctas (la Vulgata lo traduce más cautelosamente como <em>evacuari</em>), tanto así que Pablo en un pasaje famoso afirma querer &ldquo;mantener la ley&rdquo; (<em>nomon istanomen </em>— <em>ibid.</em>, 3, 31). Lutero, con una intuición cuyo alcance no debió de escapársele a Hegel, traduce <em>katargein</em> con <em>aufheben</em>, es decir, con un verbo que significa tanto &ldquo;abolir&rdquo; como &ldquo;conservar&rdquo;.<br><br>
  
  En cualquier caso, es seguro que para Pablo no se trata de destruir la ley, que es &ldquo;santa y justa&rdquo;, sino de desactivar su acción respecto al pecado, porque es a través de la ley como los hombres conocen el pecado y el deseo: &ldquo;no habría conocido el deseo si la ley no hubiera dicho: &lsquo;no desear&rsquo;; tomando impulso del mandamiento, el pecado ha vuelto operante [<em>kateirgasato</em>, &ldquo;ha activado&rdquo;] en mí todo deseo&rdquo; (<em>ibid.</em>, 7, 8).<br><br>
  
  Es esta operatividad de la ley lo que la fe mesiánica neutraliza y vuelve inoperante, sin por ello abolir la ley. La ley que es &ldquo;mantenida&rdquo; es una ley destituida de su poder de mando, es, pues, una ley no ya de los mandatos y de las obras (<em>nomos ton entolon</em> — <em>Ef</em>., 2, 15; <em>ton ergon</em> — <em>Rom</em>., 3, 27), sino de la fe (<em>nomos pisteos</em> — <em>idem</em>.). Y la fe es esencialmente no una obra, sino una experiencia de la palabra (&ldquo;la fe desde la escucha y la escucha a través de la palabra&rdquo; — <em>ibid.</em>, 10, 17).<br><br>
  
  En otras palabras, el mesías funciona en Pablo como una potencia destituyente de las <em>mitzvot</em> que definen la identidad judía, sin por ello constituir otra identidad. Lo mesiánico (Pablo no conoce el término &ldquo;cristiano&rdquo;) no representa una nueva y más universal identidad, sino una cesura que pasa a través de toda identidad; tanto la del judío como la del gentil. El &ldquo;judío según el espíritu&rdquo; y el &ldquo;gentil según la carne&rdquo; no definen una identidad ulterior, sino solamente la imposibilidad para toda identidad de coincidir consigo misma; es decir, su destitución en cuanto identidad: judío como no judío, gentil como no gentil. (De acuerdo con un paradigma de este tipo, es verosímil que podría pensarse una destitución del dispositivo de la ciudadanía).<br><br>
  
  Coherentemente con estas premisas, Pablo, en un pasaje decisivo de <em>i</em><em> Cor</em>., 7, define la forma de vida del cristiano a través de la fórmula <em>hos me</em> (&ldquo;como no&rdquo;):</p>
  
<blockquote>Esto luego digo, hermanos, el tiempo se ha contraído: lo que resta es para que los que tienen una mujer sean como no teniéndola y los que lloran como no llorando y los que tengan alegría como no teniéndola y aquellos que compran como no poseyendo y los que usan el mundo como no abusándolo. Así pasa la figura de este mundo.</blockquote>

<p>El &ldquo;como no&rdquo; es una deposición sin abdicación. Vivir en la forma del &ldquo;como no&rdquo; significa destituir toda propiedad jurídica y social, sin que esta deposición funde una nueva identidad. Una forma-de-vida es, en este sentido, aquella que incesantemente depone las condiciones sociales en las que se encuentra viviendo, sin negarlas, sino simplemente usándolas. Si, escribe Pablo, en el momento de la llamada te encontrabas en la condición de esclavo, no te preocupes: pero si además quieres volverte libre, más bien haz uso (<em>chresai</em>) de tu condición de esclavo (<em>ibid.</em>, 7, 21). &ldquo;Hacer uso&rdquo; nombra aquí el poder deponente de la forma de vida del cristiano, que destituye &ldquo;la figura de este mundo&rdquo; (<em>to schema tou kosmou toutou</em>).</p>

<p>12. Es éste el poder destituyente que tanto la tradición anárquica como el pensamiento del siglo xx intentaron definir sin nunca verdaderamente lograrlo. La destrucción de la tradición en Heidegger, la deconstrucción del <em>arché </em>y la fractura de las hegemonías en Schürmann, aquello que, tras las huellas de Foucault, he llamado &ldquo;arqueología filosófica&rdquo;, son todos intentos pertinentes, pero insuficientes, de regresar a un <em>a priori</em> histórico para destituirlo. Pero también buena parte de la práctica de las vanguardias artísticas y de los movimientos políticos de nuestro tiempo puede ser vista como el intento —tantas veces miserablemente fallido— de actuar una destitución de la obra, que en cambio ha terminado por recrear en todas partes los dispositivos museales y los poderes que pretendía deponer y que ahora parecen mucho más oprimentes en la medida en que carecen de toda legitimidad.<br><br>

  Benjamin escribió una vez que no hay nada más anárquico que el orden burgués. En el mismo sentido, Pasolini pone en boca de uno de los jerarcas de Saló que la verdadera anarquía es la del poder. Si esto es verdad, se comprende entonces por qué el pensamiento que intenta pensar la anarquía —como negación de &ldquo;origen&rdquo; y &ldquo;mando&rdquo;, <em>principium</em> y <em>princeps</em>— permanezca prisionero en aporías y contradicciones sin fin. Dado que el poder se constituye a través de la exclusión inclusiva (la <em>ex-ceptio</em>) de la anarquía, la única posibilidad de pensar una verdadera anarquía coincide con la lúcida exposición de la anarquía interna al poder. La anarquía es aquello que se vuelve pensable sólo en el punto en el que aferramos y destituimos la anarquía del poder. Lo mismo vale para todo intento de pensar la anomia: ésta se vuelve accesible sólo a través de la exposición y la deposición de la anomia que el derecho ha capturado dentro de sí en el estado de excepción. Esto es verdad también para el pensamiento que intenta pensar lo irrepresentable —el <em>demos</em>— que ha sido capturado en el dispositivo representativo de las democracias modernas: sólo la exposición de la <em>a-demia</em> interna a la democracia permite hacer aparecer el pueblo ausente que aquél pretende representar.<br>
  En todos estos casos, la destitución coincide sin residuos con la constitución, la posición no tiene otra consistencia que en la deposición.</p>
  
<p>א <em>El término </em>arché <em>significa en griego tanto &ldquo;origen&rdquo; como &ldquo;mando&rdquo;. A este doble significado del término corresponde el hecho de que, tanto en nuestra tradición filosófica como en la religiosa, el origen, aquello que da inicio y da existencia, no es solamente un exordio, que desaparece y cesa de actuar en aquello a lo que ha dado vida, sino que es también aquello que comanda y gobierna el crecimiento, el desarrollo, la circulación y la transmisión; en una palabra, la historia.</em><br><br>

  <em>En un libro importante, </em>El principio de anarquía<em> (1982), Reiner Schürmann ha intentado deconstruir este dispositivo a partir de una interpretación del pensamiento de Heidegger. Así, él distingue en el último Heidegger el ser como puro venir a la presencia y el ser como principio de las economías histórico-epocales. A diferencia de Proudhon y de Bakunin, que no han hecho más que &ldquo;desplazar el origen&rdquo;, sustituyendo el principio de autoridad con un principio racional, Heidegger habría pensado un principio anárquico, en el cual el origen como venir a la presencia se emancipa de la máquina de las economías epocales y no gobierna ya el devenir histórico. El límite de la interpretación de Schürmann se muestra con evidencia en el mismo sintagma, voluntariamente paradójico, que da título al libro: el &ldquo;principio de anarquía&rdquo;. No basta con separar origen y mando, </em>principium <em>y</em> princeps<em>: como hemos mostrado en </em>El Reino y la Gloria<em>, un Rey que reina pero no gobierna no es uno de los dos polos del dispositivo gubernamental y jugar un polo contra el otro no es suficiente para detener su funcionamiento. La anarquía jamás puede estar en la posición de principio: ella sólo puede liberarse como un contacto, ahí donde tanto el </em>arché<em> en calidad de origen como el </em>arché<em> en calidad de mando son expuestos en su no-relación y neutralizados.</em></p>
<p>13. En el dispositivo potencia/acto, Aristóteles ha trabado juntos en una relación a dos elementos incompatibles: lo contingente (que puede ser y no ser) y lo necesario (que no puede no ser). De acuerdo con el mecanismo de la relación que hemos definido, él piensa la potencia como existente en sí, en la forma de una potencia de no o impotencia (<em>adynamia</em>) y el acto como ontológicamente superior y precedente a la potencia. La paradoja —y, al mismo tiempo, la fuerza— del dispositivo es que, si se le toma al pie de la letra, la potencia nunca puede traspasar en el acto y el acto anticipa ya siempre su propia posibilidad. Por eso Aristóteles debe pensar la potencia como una <em>hexis</em>, un &ldquo;habito&rdquo;, algo que se &ldquo;tiene&rdquo; y el paso al acto como un acto de voluntad.<br><br>

  La desactivación del dispositivo es mucho más compleja. Aquello que desactiva la operosidad es ciertamente una experiencia de la potencia, pero de una potencia que, en la medida en que mantiene su propia impotencia o potencia de no, se expone en su no-relación con el acto. Poeta no es aquel que posee una potencia de hacer y, en cierto momento, decide ponerla en acto. Tener una potencia significa en realidad: estar a merced de la propia impotencia. En esta experiencia poética, potencia y acto ya no se encuentran en relación, sino inmediatamente en contacto. Dante expresa esta especial proximidad de potencia y acto cuando escribe, en <em>De monarchia</em>, que toda la potencia de la multitud está <em>sub actu</em>, &ldquo;de otra forma se daría una potencia separada, lo cual es imposible&rdquo;. <em>Sub actu</em> significa aquí, de acuerdo con uno de los posibles significados de la preposición <em>sub</em>, la coincidencia inmediata en el tiempo y en el espacio (como en <em>sub manu</em>, inmediatamente al alcance de la mano<em>, </em>o <em>sub die</em>, en seguida, en el mismo día).<br><br>
  En el punto en el que el dispositivo queda de esta forma desactivado, la potencia deviene una forma-de-vida y una forma-de-vida es constitutivamente destituyente.</p>
  
<p>א <em>Los gramáticos latinos llamaban deponentes (</em>depositiva<em> o, también, </em>absolutiva<em> o</em> supina<em>) a aquellos verbos que, parecidos a los verbos medios (que, tras las huellas de Benveniste, hemos analizado para buscar en ellos el paradigma de una ontología diferente) no puede decirse propiamente que sean ni activos ni pasivos: </em>sedeo, sudo, dormio, iaceo, algeo, sitio, esurio, gaudeo.<em> ¿Qué es lo que &ldquo;deponen&rdquo; los verbos medios o deponentes? Éstos no expresan una operación, más bien la deponen, la neutralizan y la vuelven inoperosa y, de esta forma, la exponen. El sujeto no es, en palabras de Benveniste, simplemente interno al proceso, sino que, habiendo depuesto su acción, se ha expuesto junto con ella. En la forma-de-vida, actividad y pasividad coinciden. Así, en el tema iconográfico de la deposición </em>—<em>por ejemplo en la deposición de Tiziano que está en el Museo del Louvre</em>— <em>Cristo ha depuesto completamente la gloria y la realeza que, de alguna manera, aún le correspondían estando en la cruz, y sin embargo, precisamente y sólo de este modo, cuando él se encuentra ya más allá de la pasión y de la acción, la destitución completa de su realeza inaugura la nueva edad de la humanidad redimida.</em></p>

<p>14. Todos los seres vivientes son en una forma de vida, pero no todos son (o no siempre son) una forma-de-vida. En el punto en el que la forma-de-vida se constituye, ella destituye y vuelve inoperosas todas las formas de vida singulares. Es solamente viviendo una vida que se constituye una forma-de-vida como la inoperosidad inmanente en cada vida. Es decir, la constitución de una forma-de-vida coincide íntegramente con la destitución de las condiciones sociales y biológicas en las que ella se encuentra arrojada. La forma-de-vida es, en este sentido, la revocación de todas las vocaciones facticias, que depone y pone en tensión desde su interior con el mismo gesto en el que se mantiene y demora en ellas. No se trata de pensar una forma de vida mejor o más auténtica, un principio superior u otro lugar, que sobreviene a las formas de vida y a las vocaciones artificiales para revocarlas y volverlas inoperosas. La inoperosidad no es otra obra que sobreviene a las obras para desactivarlas y deponerlas: ella coincide íntegra y constitutivamente con su destitución, con el vivir una vida.<br><br>
  Se comprende entonces la función esencial que la tradición filosófica occidental ha asignado a la vida contemplativa y a la inoperosidad: la forma-de-vida, la vida propiamente humana es aquella que, volviendo inoperosas las obras y las funciones específicas del viviente, las hace, por así decirlo, girar en el vacío, y de esta forma las abre a sus posibilidades. Contemplación e inoperosidad son, en este sentido, los operadores metafísicos de la antropogénesis, que, liberando al hombre viviente de todo destino biológico o social y de toda tarea predeterminada, lo vuelven disponible para esa particular ausencia de obra que nos hemos acostumbrado a llamar &ldquo;política&rdquo; y &ldquo;arte&rdquo;. Política y arte no son tareas ni simplemente &ldquo;obras&rdquo;: ellas nombran, más bien, la dimensión en la cual las operaciones lingüísticas y corpóreas, materiales e inmateriales, biológicas y sociales, son desactivadas y contempladas como tales para liberar la inoperosidad que ha permanecido prisionera en ellas. Es en esto en lo que consiste el máximo bien que, según el filósofo, el hombre puede esperar: &ldquo;una alegría nacida del hecho de que el hombre se contempla a sí mismo y su potencia de actuar&rdquo;.</p>
  
<p align="right"><em>Traducción del italiano:</em><br>
  <em>Vicens Alba Osante y Alan Cruz Barrera</em></p>
<p>&nbsp;</p>

<h4>Bibliografía</h4>
<p>Giorgio Agamben, <em>Homo sacer. Il potere sovrano e la nuda vita</em>, Turín, Einaudi, 1995.<br>
  Jan Peter Beckmann, <em>Die Relationen der Identität und Gleichheit nach Johannes Duns Scotus</em>, Bonn, H. Bouvier, 1967.<br>
  Walter Benjamin, <em>Gesammelte Schriften</em>, Bd. ii, i, Fráncfort del Meno, Suhrkamp, 1977.<br>
  Giorgio Colli, <em>La ragione errabonda</em>, Milán, Adelphi, 1982.</p>

<h4>Notas</h4>

    <p><a href="#_ftnref1" name="_ftn1" title=""> </a>*Tradujimos literalmente el concepto de &ldquo;<em>inoperosità</em>&rdquo; usando el neologismo &ldquo;inoperosidad&rdquo;, frente a otras traducciones como &ldquo;inoperatividad&rdquo; o &ldquo;inoperancia&rdquo;, por dos motivos fundamentales: en primer lugar, para subrayar la distinción entre operación y obra (<em>opera</em>, <em>ergon</em>), es decir, para dejar abierto el camino para pensar una operación que no obstante permanece sin obra (nótese que el término &ldquo;<em>inoperatività</em>&rdquo; también existe en italiano); en segundo lugar, para evitar cancelar su carácter dinámico que está más acá del activo y del pasivo; un rasgo del concepto que en el término &ldquo;inoperancia&rdquo;, a nuestro aviso, adquiere un tono más bien estático o de pura pasividad. [N. de los TT.]. </p>
    <p><a href="#_ftnref2" name="_ftn2" title=""> </a>* El término <em>fattizia</em> está asociado a traducciones italianas de Heidegger (por ejemplo para <em>facktische Leben</em>), y en italiano tiene la particularidad de acentuar el carácter artefacto o ficticio sobre el factual. Quizá &ldquo;experiencia arte-fáctica&rdquo; sería otra posible traducción. [N. de los TT.].
    </p>

</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Giorgio Agamben es un filósofo italiano nacido en 1942. Además de ser reconocido por su larga investigación de casi veinte años llamada Homo sacer, Agamben es conocido por sus estudios de mesianismo y biopolítica, así como de autores como Walter Benjamin, Martin Heidegger, Michel Foucault o Carl Schmitt. Entre sus obras más leídas se encuentran La comunidad que viene (1990), <em>El tiempo que resta (2000)</em>, <em>Estado de excepción (2003)</em>, y <em>El Reino y la Gloria (2010)</em>.
<br><br>
<h5>Traducción del Italiano</h5>
Vicens Alba Osante y Alan Cruz Barrera
</div>
</section>

<?php include 'footer.php' ?>
