<?php include 'header.php' ?>
<section class="titulo">
	<article class="">
		<h3>Número 56</h3>
		<h1>Caída épica<br>
El laberinto sin centro de Bolaño

</h1>

		<h2>Giles Harvey</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
<span></span>
<p>He aquí un juego de salón que inventé mientras comparaba ansiosamente mis propias impresiones de <em>2666</em> con las de todas las otras personas que reseñaron este libro. El objetivo es el de hacer coincidir las siguientes gemas anti-sagacidad con las obras maestras que describen y que habían sido recién publicadas en ese entonces: <br>
  <br>
a) &ldquo;Un amasijo de suciedad estúpida&rdquo;.<br>
b) &ldquo;Calma, resuelta, imperturbable babeante idiotez&rdquo;. <br>
c) &ldquo;La obra de un universitario mareado rascándose los granos&rdquo;. <br>
d) &ldquo;Como yacer dentro del agua sucia del baño de otra persona&rdquo;. <br>
e) &ldquo;Está midiendo, al mismo tiempo, nuestra candidez y paciencia&rdquo;. <br>
<br>
a) <em>En busca del tiempo perdido</em><br>
b) <em>Endymion</em> <br>
c) <em>Ulises</em> <br>
d) <em>Moby-Dick</em> <br>
e) <em>Hojas de hierba</em></p>
<p><em>2666</em> es una novela que de forma explícita invita a la comparación con tales obras maestras −con las que ésta llama, haciendo un poco de proselitismo en beneficio propio, &ldquo;las grandes , imperfectas, obras torrenciales, libros que señalan caminos hacia lo desconocido&rdquo;−. No obstante, al contrario de los libros arriba enumerados, <em>2666</em> ha sido acogida con un clamor casi unánime, con expresiones como: &ldquo;No sólo es la gran novela de la lengua española de esta década, sino una de las piedras angulares que definen una literatura entera&rdquo;. Y: &ldquo;Bolaño se ha unido a los inmortales.&rdquo; <br><br>
  Desde luego, fue Virgina Wolf quien de manera célebre describió al <em>Ulises</em> como &ldquo;la obra de un universitario mareado rascándose los granos&rdquo;. La grosería de tal juicio puede atribuirse, al menos en parte, a envidia estética; además, fue confinada a su diario. Ya en publicación fue más generosa, llamando al libro simplemente &ldquo;una catástrofe memorable, sumida en osadía, tremenda en desastre&rdquo;. La inmensa, agotadora, desordenada y no corregida última novela de Bolaño me impresiona como otra osada, pero finalmente catastrófica obra maestra. Como el Ulises, es una anti-novela. Como el Ulises, busca contener (y confundir) al universo. Como el Ulises, agota la paciencia del lector, su buena voluntad y su caridad −y entonces, prosigue durante otras cuatrocientas páginas−. Habiéndola leído y habiéndome sometido a ella, espero no volver a leerla nunca: ars longa, vita brevis. <br><br>
  Bolaño, un chileno que pasó su vida en un exilio nómada, murió en 2003, a la edad de 50 años, después de producir en su última década una cantidad de libros equivalente a la obra de toda una vida. Tal como recientemente comentó n+1, pocos escritores han sido canonizados con tan hábil procacidad. De repente, ahí está él al final de esas listas que Harold Bloom parece estar desplegando siempre: Joyce, Proust, Kafka, Faulkner, Borges, Bolaño. En general, la adulación recibida a su trabajo parece más que garantizada. Sin embargo, esta adulación se ha petrificado en una estúpida piedad, una de las actitudes que Bolaño invariablemente se ocupa en vapulear. Él parece capaz de no inferir ningún mal, ni un gran mal. Como el formidable Sam Sacks escribió en una de las mejores y hasta donde yo se, única reseña negativa de <em>2666</em> hasta la fecha: &ldquo;De alguna forma se había vuelto axiomático que esta novela fuese una obra maestra antes de siquiera haber llegado a las librerías&rdquo;[1]. (Ciertamente, cuando la frase &ldquo;Llevar consigo la <em>2666</em> de Bolaño, es como manejar un Porsche convertible&rdquo; puede ser perpetrada a plena luz periodística, el tiempo está maduro para una pequeña dosis de revisionismo. Le hacemos un perjuicio a un gran hombre si no lo hacemos responsable de sus errores). </p>
<h4>***</h4>
<p>Sin embargo, antes de empezar a objetar 2666, por lo menos parece pertinente ocupar algún tiempo tocando las múltiples riquezas que encierran los libros anteriores de Bolaño. Sin embargo, la primera cosa que uno nota acerca de este autor es que su escritura, al menos su superficie, es más bien mediocre. Él no sobresale en absoluto (o por lo menos elige no sobresalir) en la clase de fina prosa adornada con brillantes pormenores visuales, vueltas de tuerca sorprendentes y lenguaje figurativo vital que es la especialidad de muchos novelistas contemporáneos. Samuel Jonhson dijo: &ldquo;Relee tus composiciones y cuando encuentres un pasaje sobre el cual pienses que es singular o superior, táchalo&rdquo;. Es poco probable que Bolaño haya tenido jamás que sufrir tal molestia. Sus libros se leen como si haberlos escrito fuera la tercera cosa más importante que tenía que hacer ese día: &ldquo;Por 5 segundos, su cabello se mantuvo erizado&rdquo;; &ldquo;una nube oscura parecía cernirse sobre nosotros noche y día&rdquo;; &ldquo;Los corazones de los críticos brincaban ante sus palabras&rdquo; (Los detectives salvajes). Bolaño escribe como si Flaubert nunca hubiera padecido su pasión por el estilo; su registro característico es casi premoderno −relajado, inconexo, lleno de digresiones, sofocado con redundancia y solecismo y siempre listo para decir el mot juste, la palabra adecuada, exactamente lo que piensa de ello−. <br><br>
  Este antagonismo hacia la literatura −o al menos hacia lo que Bolaño consideraba como jactancioso y afectado perfeccionismo literario− es más evidente tal vez en Nocturno de Chile, el monólogo del Padre Sebastían Urrutia Lacroix en su lecho de muerte. La mayoría de los personajes de Bolaño son juglares improductivos, anónimos, que se aferran con celo a lo que a ellos les gusta pensar es su integridad. Lacroix, un sacerdote chileno y crítico literiario, es atípico puesto que su carrera de escritor ha sido un &ldquo;éxito&rdquo;. Al menos en el sentido en que ha publicado y es bien conocido. Moralmente, es una catástrofe, asistiendo a un salón literario en una casa cuyo sótano es usado como cámara de tortura. Entre su estética y su conservadurismo político, su melodramática vida espiritual y su vanidosa percepción de que su trabajo ayuda a sostener el edificio completo de la civilización (cuando de hecho todo lo que sostiene es su propia imagen exaltada), Lacroix da la impresión de ser una especie de parodia de Norman Podhoretz. Pero la muerte se acerca, la exaltada imagen de sí mismo comienza a desarrollarse: los muchos momentos de cobardía, de traición, evasión y engaño de Lacroix caen sobre las 130 bruscas páginas del libro hasta que, como Bolaño lo dice en su propia voz franca justo al final, &ldquo;se desata la tormenta de mierda&rdquo;. <br><br>
  En muchos aspectos, Nocturno de Chile es poco característica de Bolaño, al menos en cuanto a estilo. Ninguno de sus otros trabajos emplea nada cercano a la prosa rica y empalagosa de Lacroix. En una ocasión Lacroix efectúa un viaje a Europa en donde se entera de que para proteger a las iglesias del excremento de las palomas, los sacerdotes habían entrenado halcones para matar a los pájaros más pequeños bautizándolos con nombres como Otelo, Turk, Antonia y Jenofonte. En Avignon Ta Gueule (&ldquo;cierra el pico&rdquo;, en francés) se ocupa de la matanza: <br><br>
  
  Ta Gueule volvía a aparecer como un rayo o como la abstracción mental de un rayo para caer sobre las enormes bandadas de estorninos que aparecían por el oeste como enjambres de moscas, ennegreciendo el cielo con su revolotear errático y al cabo de pocos minutos el revolotear de los estorninos se ensangrentaba, se fragmentaba y se ensangrentaba y entonces el atardecer de las afueras de Avignon se teñía de rojo intenso, como el rojo de los crepúsculos que uno ve desde las ventanillas de un avión, o el rojo de los amaneceres, cuando uno despierta suavemente con el ruido de los motores silbando en los oídos y corre la cortinilla del avión y en el horizonte distingue una línea roja como una vena, la femoral del planeta, la aorta del planeta que poco a poco se va hinchando, esa vena de sangre fue la que vi en los cielos de Avignon, el vuelo ensangrentado de los estorninos, los movimientos como de paleta de pintor expresionista abstracto de Ta gueule (91). </p>
<p>Todo es un poco excesivo y su demasía−la extravagante estetización que compara la sangre con la pintura, las pequeñas y petulantes auto-correcciones y las auto-explicaciones (&ldquo;como un rayo o como la abstracción de un rayo&rdquo;, &ldquo;la femoral del planeta, la aorta del planeta&rdquo;)− es precisamente lo que muestra la ambigüedad moral del narrador. Bolaño mismo, en oposición a Lacroix, nunca hubiera escrito de esta manera. En su obra, es siempre el sapo moralista quien se expresa a sí mismo como un príncipe.<br><br>
  La voz más característica de Bolaño viene a través de la figura del joven de 17 años Juan García Madero, cuyo diario para el final de 1975 y principios de 1976, abre y cierra Los detectives salvajes. Inocente, sensual, vagamente izquierdista y totalmente sincero, Madero es lo contrario de Lacroix. En cierto punto, el viejo sacerdote habla sobre la crítica literaria como un &ldquo;en un esfuerzo civilizador, en un esfuerzo de tono comedido y conciliador, como un humilde faro en la costa de la muerte&rdquo; (Nocturno de Chile). Uno se pregunta lo que haría Lacroix con lo que Madero escribe en su diario en la fecha del 8 de noviembre, poco después de descubrir un &ldquo;asombroso&rdquo; poema sumamente erótico, &ldquo;El Vampiro&rdquo;:</p>
<p>La primera vez que lo leí (hace unas horas) no pude evitar encerrarme con llave en mi cuarto y proceder a masturbarme mientras lo recitaba una, dos, tres, hasta diez o quince veces, imaginando a Rosario, la camarera, a cuatro patas encima de mí, pidiéndome que le escribiera un poema para ese ser querido y añorado o rogándome que la clavara sobre la cama con mi verga ardiente.<br><br>
  Ya aliviado, he tenido ocasión de reflexionar sobre el poema. El «raudal crespo y sombrío» no ofrece, creo, ninguna duda de interpretación. No sucede lo mismo con el primer verso de la segunda cuarteta: «en tanto que descojo los espesos anillos&quot;, que bien pudiera referirse al «raudal crespo y sombrío» uno a uno estirado o desenredado, pero en donde el verbo «descojer» tal vez oculte un significado distinto. «Los espesos anillos» tampoco están muy claros. ¿Son los rizos del vello púbico, los rizos de la cabellera del vampiro o son diferentes entradas al cuerpo humano? En una palabra, ¿la está sodomizando? Creo que la lectura de Pierre Louys aún gravita en mi ánimo (Los detectives salvajes, 22)</p>
<p>¡Ojalá que todos los lectores reaccionaran tan intensamente al verso! He aquí un pasaje que podría ser demasiado; o mejor, muy poco; podría obtener su kilometraje de la reacción visceral inicial de Madero al poema y dejarlo así. Pero, la lectura, maravillosamente honrada y cuidadosa, pisándole los talones a la fantasía onanista es el verdadero toque del genio. Ésta es la prosa de Bolaño al máximo: pero completamente natural y sin pretensiones, harapienta y, sin embargo, robusta; parecería tanto copiar como burlarse de un registro literario que nunca alcanza. En ningún lugar es tan ligero el toque de Bolaño como en la frase final: &ldquo;Creo que la lectura de Pierre Louys aún gravita en mi ánimo&rdquo; en donde la agotadora y brillante auto-reflección adolescente desentona con el torrente de ardor totalmente carente de afectación que lo precede. </p>
<h4>***</h4>
<p>Nunca nos enteramos exactamente lo que le pasa a Madero, pero Los detectives salvajes, con su interminable llamado a casting de literatos fallidos, nos proporciona suficiente margen de maniobra para conjeturar que sus grandes ambiciones poéticas quedan insatisfechas. El fracaso yace en el centro del sentido de la literatura de Bolaño y la vida literaria. En este sentido tiene una clara deuda con Borges, a quien leía incesantemente y cuya concepción de la tardanza literaria heredó. Borges, desde luego, fue capaz de transformar este sentido de haber llegado demasiado tarde en una fuerza estética. En el prólogo a El jardín de los senderos que se bifurcan, por ejemplo, establece su posición con típica y recatada humildad: &ldquo;Es una ardua locura y una que empobrece, la locura de escribir libros extensos estableciendo en quinientas páginas una idea que podría perfectamente ser relatada en cinco minutos. La mejor manera de proceder en consecuencia es fingir que esos libros ya existen y ofrecer un resumen, un comentario acerca de ellos&rdquo;. <br><br>
  ¿Hacia dónde va uno desde este punto de insoportable contracción, después de que Borges ha tomado lo que parece ser una salida definitiva? La respuesta de Bolaño al acertijo está inspirada en su osadía, su flirteo con una suerte de suprema irrelevancia: escribe, largamente, acerca de escritores menores que fracasan para producir cualquier cosa, o al menos algo de importancia real. Sus obras completas pueden ser leídas como un deprimente gran himno a la nobleza del fracaso.<br><br>
  Sin embargo, para Bolaño, el fracaso no es solamente un tema, es un modus operandi. A este respecto, 2666 es la culminación de la carrera de Bolaño, tal como lo han aclamado tantos. No sólo no &ldquo;trasciende&rdquo; la forma de novela tanto como negarla o rechazarla. Personalidades formadas, incidentes, descripción evocativa: Bolaño parece no tener necesidad de ellas. Samuel Beckett, el graduado original en fracaso, necesitaba solamente unas cuantas páginas de diálogo o prosa para sugerir una infinidad de enloquecedor aburrimiento; Bolaño decide someternos a ese aburrimiento durante 900 páginas. Este minimalismo épico es una empresa dudosa. Un resultado es que el libro corre el riesgo de ser aburrido, informe y horrible; un riesgo que en mi mente no redondeó por completo. No es que haya odiado 2666, pero a menudo tuve la sensación de que 2666 no me quería tanto a mí.<br><br>
  En la primera de sus cinco partes, &ldquo;La parte de los críticos&rdquo;, un cuarteto de académicos europeos tres hombres y una mujer se reúnen por su mutua devoción a un solitario novelista alemán, Benno von Archimboldi. Bolaño siempre escribe de manera obsesiva acerca de artistas y estetas, mientras elimina con astucia la pregunta de si acaso sus búsquedas de altos vuelos se tratan en realidad de algo más que de un fanático engreimiento. Así ocurre con los cuatro archimboldeanos. Muy temprano los críticos se dan cuenta de que la búsqueda de Archimboldi no puede llenar sus vidas: &ldquo;Podían leerlo, podían estudiarlo, podían desmenuzarlo, pero no podían morirse de risa con él ni deprimirse con él, en parte porque Archimboldi siempre estaba lejos, en parte porque su obra, a medida que uno se internaba en ella, devoraba a sus exploradores&rdquo; (2666). No obstante, cuando escuchan un rumor de que Archimboldi ha sido visto en Santa Teresa, una ciudad en el norte de México, cerca de la frontera con Arizona, los críticos empacan sus maletas y parten. Desde luego, el novelista no es hallado en ninguna parte. Descorazonados, los críticos se entretienen por un rato, releen las novelas de Archimboldi al lado de la piscina del hotel, absorben la desoladora atmósfera del desierto; luego, abruptamente, la parte termina. Los críticos desaparecen y nunca se vuelve a saber de ellos. <br><br>
  La desaparición parece ser el destino de la mayoría de las personas en la novela. Y conforme seguimos leyendo, la cantidad y la velocidad de estos secuestros narrativos no hace más que aumentar. La segunda parte, &ldquo;La parte de Amalfitano&rdquo;, tiene que ver con un profesor de literatura en la Universidad de Santa Teresa cuya esposa los abandona a él y a la hija de ambos para visitar a un poeta institucionalizado con quien se acostó una vez en una fiesta en Barcelona. Después de siete años (los cuales transcurren en unas cuantas páginas), ella regresa por un corto período y luego parte de nuevo. Después se nos cuenta acerca de la muerte del padre de Archimboldi, un veterano mutilado cuyo último deseo, mientras huía de los rusos con su familia, es el de ser sepultado en su tierra con honores militares. Su esposa y su hija le dicen &ldquo;que ellas se asegurarían que eso ocurriera, sí, sí, lo prometemos&rdquo; (2666), pero su cuerpo es arrojado inmediatamente en una fosa común. Podrían darse decenas de ejemplos parecidos. Una y otra vez Bolaño monta historias y las deja en movimiento solamente para eliminarlas unas cuantas páginas más adelante. (&ldquo;La parte acerca de los crímenes&rdquo; es el cementerio más grande en el libro, pero regresaré a él más tarde). <br><br>
  El efecto acumulativo de todas estas desapariciones, preguntas sin respuesta e historias que no terminan sino que simplemente se detienen, es el de investir a 2666 de una humildad epistemológica. Más allá de los hechos básicos (ellos huyen, les disparan en la nuca) Bolaño no presume saber lo que le ocurrió a estas personas; es más, parece dudar de si la gente es cognosible en absoluto. En lugar de mostrarnos, o de intentar mostrarnos, las vidas interiores de sus personajes, él nos desaira con un caparazón de exterioridad. Sus interminables micro-narraciones no son solamente breves; son también totalmente opacas. El efecto, debe decirse, no es el mismo como lo que ocurre en la asombrosa parte media de Los detectives salvajes, en donde docenas de personajes diferentes, dispersos en tiempo y lugar, dicen cada uno a su vez lo que saben (normalmente no mucho) acerca de los poetas peregrinos Belano y Lima. Aún cuando no surge casi ninguna impresión palpable o coherente de cualesquiera de los poetas y el carácter narrativo es usurpado continuamente por los varios interlocutores, quienes a menudo revelan más acerca de sí mismos que de los héroes putativos del libro. Al final sentimos que hemos sido empapados de personalidad, aún cuando el enigma esencial de Belano y de Lima es resguardado. Ellos representan el espacio negativo que permanece en un paisaje denso y bullicioso.<br><br>
  En contraste, 2666 es un desierto de espacio negativo cubierto con borrones y garabatos caóticos. Lo que los críticos llegan a saber acerca de Archimboldi en la Primera Parte (que él &ldquo;Archimboldi siempre estaba lejos&rdquo; y que &ldquo;a medida que uno se internaba en ella, devoraba a sus exploradores&rdquo;) es evidente acerca de todo personaje en el libro. Los personajes están bosquejados brusca, impacientemente, con pocos, si acaso, detalles reveladores, como si Bolaño estuviera simplemente apartando del camino una formalidad. Después de todo…¿para qué perder tiempo y esfuerzo en una persona que seguramente desaparecerá dentro de unas cuantas páginas? Esto, al menos, es a menudo lo que se siente al leer el libro: que Bolaño está llevando a cabo un experimento de cuánto puede quitar de lo que comúnmente se considera el placer principal de la ficción (llegar a conocer a personajes imaginarios) sin ahuyentarnos.<br><br>
  Lo mismo vale para la prosa, la cual es consistentemente aburrida. Aún concediendo que Bolaño está escribiendo mal a propósito –que su prosa insulsa, imprecisa, sin matices, es una censura deliberada de la presunta aprobación al embellecimiento artificial de un estilo literario más convencional y debe ser visto, por lo tanto, como otra faceta más de su escepticismo general acerca de la aptitud del arte para abarcar y para reproducir fielmente el mundo en lenguaje– no obstante, 900 páginas del mismo pueden ser adormecedoras. &ldquo;En literatura,&rdquo; dijo Henry James, &ldquo;nos movemos a través de un mundo bendito en el cual no sabemos nada salvo por el estilo, pero en el cual todo se salva por él.&rdquo; Lo que James bendice, Bolaños lo maldice: su estilo asegura que sepamos poco más allá de nuestra propia ignorancia, que sus lugareños carecen de toda densidad plausible, que todo parece siempre lejano. Una y otra vez parece que está sucediendo poco, tanto en la superficie como en la escritura, en la textura de la prosa y &ldquo;detrás&rdquo; de la escritura, en las mentes de los personajes. <br><br>
  Bolaño está jugando aquí un apuesta seria y hay algo valiente acerca de la manera en que ha perseguido su visión –que tan poca literatura puede conocer y hacer– a tales extremos. Sin embargo, somos condescendientes con un escritor si consideramos tan sólo sus intenciones. Una obra de arte, si sirve para engancharnos a un nivel conceptual –para hacernos reflexionar en lo que creemos saber–, tiene primero que satisfacer la obligación de gustar. De otra manera se convierte en una lección, una mera demostración. El Ulises es una anti-novela: en su segunda mitad deconstruye, ante nuestros ojos, los mecanismos de ficción realista. Aún así, la razón por la que esta deconstrucción es tan poderosa es que Joyce ha empleado la primera mitad mostrándonos todo lo que la ficción realista puede lograr. En 2666 sentimos que la dialéctica está torcida, que no se le ha dado una justa oportunidad para mostrar todo lo que puede hacer. Como resultado, su escepticismo se percibe ingrávido, tendencioso, inmerecido. <br><br>
  Al principio, parece que &ldquo;La parte de Archimboldi&rdquo; será la excepción a esta regla. La parte final presenta un relato de la historia de la vida del autor, desde su niñez en el Norte de Alemania, hasta su heroico servicio en el Frente Este en la Segunda Guerra Mundial y su subsecuente carrera literaria. Sabemos acerca de su feliz, apasionado matrimonio con Ingeborg, una inculta pero vivaz personalidad a lo Nora Barnacle; de la muerte de Ingeborg de una enfermedad debilitante no especificada; y de los años de solitario vagabundeo de Archimboldi alrededor de Europa. Sin embargo, la narrativa es una no-revelación continua. A pesar de que sabemos mucho más acerca de Archimboldi (cuyo nombre real es Hans Reiter) que de cualquier otro personaje del libro, él nunca llega a estar bien enfocado. Bolaño reserva sus secretos de nosotros. <br><br>
  He aquí un pasaje característico. Cuando niño Reiter, por algunas razones, desarrolla una obsesión con las algas marinas, un hecho que aparentemente garantiza lo siguiente: <br>
  <br>
  Por esa época comenzó a dibujar en un cuaderno todo tipo de algas. Dibujó la Chorda filum, que es un alga compuesta por largos cordones delgados que pueden, sin embargo, llegar a alcanzar los ocho metros de longitud. Carecen de ramas y su apariencia es delicada, pero en realidad son muy fuertes. Crecen por debajo de la marca de la marea baja. Dibujó también la Leathesia difformis, que es un alga compuesta por bulbos redondeados de color marrón oliváceo, que crece en las rocas y sobre otras algas. Su aspecto es extraño. Nunca vio ninguna, pero soñó muchas veces con ellas. Dibujó la Ascophyllum nodosum, que es un alga parda de patrón desordenado que presenta unas ampollas ovoides a lo largo de sus ramas. Existen, entre las Ascophyllum nodosum, algas diferenciadas macho y hembra que producen unas estructuras frutales similares a pasas. En el macho son amarillas. En la hembra de un color verdusco (2666).</p>
<p>Y así prosigue por otra media página. A todo lo cual el lector está tentado de responder: &quot;Sí… ¿y qué?&quot; La narrativa evoluciona de continuo hacia esta lista interminablemente extensible cuyo tono compuesto y cauteloso (&ldquo;Una planta de apariencia rara&rdquo;, &ldquo;crecimientos frutales parecidos a pasas&rdquo;) parecen diseñados para frustrar. La lista, nos damos cuenta, es narrativa reducida a su forma más cruda, desordenada y carente de arte: una cosa después de otra. No es sencillamente que Bolaño lance una lista tan a menudo como para entorpecer la, de otra manera ordenada y completamente absorbente experiencia, de leer su libro, porque no hay orden que entorpecer: el libro es en sí mismo una lista. Desarticulación, oblicuidad, frustración: éstos se han convertido en los procedimientos convencionales de la novela, de la cual ansiamos algún respiro, alguna variación. <br><br>
  La calidad tipo lista de 2666 es más evidente en &ldquo;La parte de los crímenes&rdquo;, el corazón negro de la novela en el cual, como toda la Cristiandad está seguramente alerta por ahora, el lector está sometido a ojos abiertos a un inventario de cientos de cuerpos femeninos, las víctimas de un femicidio epidémico que ha estado afectando a Santa Teresa desde los tempranos años noventa (un recuento de semi-ficción sobre la onda de asesinatos ocurrida en el mismo periodo en Ciudad Juárez). La parte consiste en casi 300 páginas y empieza de forma muy similar a como prosigue: &ldquo;La muerta apareció en un pequeño descampado en la colonia Las Flores. Vestía camiseta blanca de manga larga y falda de color amarillo hasta las rodillas, de una talla superior&rdquo; Y así en este tono neutro, sin adornos, la horripilante evidencia se va amasando: &ldquo;A mediados de febrero, en un callejón del centro de Santa Teresa, unos basureros encontraron a otra mujer muerta. Tenía alrededor de treinta años y vestía una falda negra y una blusa blanca, escotada. Había sido asesinada a cuchilladas, aunque en el rostro y el abdomen se apreciaron las contusiones de numerosos golpes&rdquo;. </p>
<p>La muerta apareció en un pequeño descampado en la colonia Las Flores. Vestía camiseta blanca de manga larga y falda de color amarillo hasta las rodillas, de una talla superior&rdquo;. &ldquo;En octubre el cuerpo de otra mujer fue encontrado en el desierto, al sur de Santa Teresa, entre dos caminos vecinales. El cuerpo estaba en estado de descomposición y los forenses dijeron que tardarían días en determinar la causa de la muerte. La víctima tenía las uñas pintadas de rojo, lo que hizo pensar a los primeros oficiales que llegaron a la escena, que se trataba de una puta (2666). <br>
  <br>
  En los intervalos entre los asesinatos unas cuantas tramas secundarias luchan para emerger con poca suerte: en este libro nada se sostiene, a parte de la guadaña segadora de Bolaño. Policías, detectives y periodistas empiezan a investigar los crímenes y por un momento parece como si el libro fuera a tomar la dimensión reconocible de una novela de intriga y misterio; pero sus investigaciones prueban ser todas infructuosas y son rápidamente barridas a un lado por la turbadora, monótona enumeración de cadáveres. La forma es negada; la lista prevalece.<br><br>
  Bolaño parece estar echándose las manos a la cabeza ante de los horrores que describe: ya no puede darles más sentido que los personajes en su libro. Desde luego, toda la novela es una suerte de admisión de derrota artística. Kafka dijo: &ldquo;Hay un punto más allá del cual no hay retorno. Ese es el punto que debe alcanzarse.&rdquo; En 2666 ese punto está muy atrás de nosotros: es una partícula en el espejo retrovisor. El libro es una monstruosidad, una inmensa negación de todo lo que esperamos que la literatura nos dé: forma, perspicacia, redención, felicidad. Parece querer imponérsenos. He sugerido que el libro es un fracaso. Sin embargo, llamar a 2666 un fracaso parece de alguna manera tautológico: la imaginación de Bolaño fue suscrita por la idea de que todo impulso humano es, en última instancia, cancelado y destruido. <br><br>
  En su cuento &ldquo;El Inmortal&rdquo;, Borges cuenta acerca de un oficial romano que atraviesa el desierto en búsqueda de la legendaria Ciudad de los Inmortales. Cuando al fin llega queda horrorizado por lo que le espera. Describe el palacio situado en el corazón de la ciudad como sigue: </p>
<p>Estaba lleno de corredores sin salida, altas ventanas inalcanzables, puertas portentosas que daban a una celda o a un pozo, escaleras increíblemente invertidas cuyos escalones y balaustradas colgaban hacia abajo. Otras escaleras, colgando ligeras al lado de un muro monumental morían sin llevar a ninguna parte, después de dar dos o tres vueltas en la oscura elevación de las cúpulas. No se si todos los ejemplos que he enumerado son literales; lo que se es que por muchos años infestaron mis pesadillas; ya no soy capaz de saber si tal o cual detalle es una transcripción de la realidad o las formas que trastornaron mis noches. </p>
<p>El lector, que ha atravesado y vuelto a cruzar el laberinto sin centro de Bolaño, simpatizará con el juicio del narrador de &ldquo;El Inmortal&rdquo;: </p>
<p>Esta ciudad… es tan horrible que su mera existencia y permanencia, aún en medio de un desierto secreto, contamina el pasado y el futuro y en alguna manera hasta pone en entredicho a las estrellas. Mientras dure, nadie en el mundo puede ser fuerte o feliz. </p>
<p align="right"><em>Traducción del inglés de María R. Pimentel</em></p>
<p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Giles Harvey ha realizado una maestría en Bellas Artes en la Universidad de Nueva York. Forma parte del comité editorial de <em>The New York Review</em>. Sus ensayos y reseñas han aparecido en <em>TLS</em>, <em>The Guardian</em>, <em>The Believer</em>, <em>The Village Voice</em>, <em>n+1</em>, entre otros.
<div> </div>
</div>
</section>
<?php include 'footer.php' ?>