<?php include 'header.php' ?>

<section class="titulo">
	<article class="">
		<h3>Número 74</h3>
		<h1>Carta para excusarme <br>de participar en un homenaje al Quijote</h1>
		<h2>Julio Hubard</h2>
		<div class="raya"></div>

	</article>
</section>
<section class="texto container-fluid">
<div class="col-sm-9">
    <p>Querido Carlos:<del>*</del></p>
    <p>No tengo un &ldquo;capítulo favorito&rdquo; del <em>Quijote</em>. A veces ha sido la cueva de Montesinos y, a veces, los galeotes, con su absurdo discurso justiciero. Probablemente toda la secuencia con los malvados duques sea mi favorita, pero son varios capítulos. El gobierno de Sancho; la noche en que los duques maquinan a Dulcinea; el diálogo de Sansón Carrasco y Antonio Moreno, con la serie de engaños de don Antonio (cabeza incluida) y los desengaños, uno fallido, el otro no (y que cada quien elija cuál falla y cuál acierta), de Sansón Carrasco en sus dos distintas armaduras, la de los espejos y la de la blanca luna. O, aunque demasiado breve, el modo de hablar del vizcaíno. O, de plano, la descripción que hace el labrador negociante ante el gobernador Sancho, que es una página absolutamente cruel y marciana:<br><br>
      —Digo, pues —dijo el labrador—, que este mi hijo que ha de ser bachiller se enamoró en el mesmo pueblo de una doncella llamada Clara Perlerina, hija de Andrés Perlerino, labrador riquísimo; y este nombre de Perlerines no les viene de abolengo ni otra alcurnia, sino porque todos los deste linaje son perláticos [paralíticos], y por mejorar el nombre los llaman Perlerines; aunque, si va decir la verdad, la doncella es como una perla oriental, y, mirada por el lado derecho, parece una flor del campo; por el izquierdo no tanto, porque le falta aquel ojo, que se le saltó de viruelas; y, aunque los hoyos del rostro son muchos y grandes, dicen los que la quieren bien que aquéllos no son hoyos, sino sepulturas donde se sepultan las almas de sus amantes. Es tan limpia que, por no ensuciar la cara, trae las narices, como dicen, arremangadas, que no parece sino que van huyendo de la boca; y, con todo esto, parece bien por estremo, porque tiene la boca grande, y, a no faltarle diez o doce dientes y muelas, pudiera pasar y echar raya entre las más bien formadas. De los labios no tengo qué decir, porque son tan sutiles y delicados que, si se usaran aspar labios, pudieran hacer dellos una madeja; pero, como tienen diferente color de la que en los labios se usa comúnmente, parecen milagrosos, porque son jaspeados de azul y verde y aberenjenado; y perdóneme el señor gobernador si por tan menudo voy pintando las partes de la que al fin al fin ha de ser mi hija, que la quiero bien y no me parece mal.<br><br>
      —Pintad lo que quisiéredes —dijo Sancho—, que yo me voy recreando en la pintura, y si hubiera comido, no hubiera mejor postre para mí que vuestro retrato.<br><br>
      —Eso tengo yo por servir —respondió el labrador—, pero tiempo vendrá en que seamos, si ahora no somos. Y digo, señor, que si pudiera pintar su gentileza y la altura de su cuerpo, fuera cosa de admiración; pero no puede ser, a causa de que ella está agobiada y encogida, y tiene las rodillas con la boca, y, con todo eso, se echa bien de ver que si se pudiera levantar, diera con la cabeza en el techo; y ya ella hubiera dado la mano de esposa a mi bachiller, sino que no la puede estender, que está añudada; y, con todo, en las uñas largas y acanaladas se muestra su bondad y buena hechura.</p>
    <p>Y a esta descripción le sigue la del angelical bachiller, que no sale mejor parado. Pero es, con todo, poca cosa y vulgar. Esperpento. Y, para mí, <em>a guilty pleasure</em>. Teratología literaria y plástica a la que España fue peculiarmente adicta y afecta. De modo que tampoco califica como capítulo favorito.<br><br>
      También me ha sucedido, y no con poca frecuencia, que el Quijote, el personaje del Quijote, me cae mal. Defecto de mi imaginación, sin duda, pero hay temporadas en que no puedo dejar de pensar que ese señor no era buena noticia de toparse. Le bastaba una mala frase, una idea simple, por ejemplo, con la que no estuviera de acuerdo, y a los puños o la espada. Y perdía, porque tundirlo era cosa de adelantar mano, palo o piedra. Con eso tenía. Pero ese malestar se acaba conforme avanza la segunda parte.<br><br>
      Si no hallo mi capítulo favorito, sí tengo, en cambio, una parte abominada: toda la novelita del <em>Curioso impertinente</em> me resulta pesada, sin gracia, aburrida, y prometo saltármela cada vez que lea el <em>Quijote</em>. También me resultan abominables casi toda la iconografía y las estatuas y las dos obras musicales que conozco sobre el <em>Quijote</em>. <em>Fausto</em> ha dado buena música; <em>Don Juan</em>, la mejor. Pero el <em>Quijote</em> no ha podido pasar bien. La opereta de Broadway me saca ronchas. La ópera de Massenet es menos simple, pero está hecha con una idea torcida: canta el <em>Quijote</em> y todo es luz, belleza, proporción; los demás son españoles y, según Massenet, tontos, castañuelas, cazuelas, ruido y pendencias tabernarias de borrachos. Además, me hace pensar algo que sospecho muy común: que no leyó el libro. Eso, o que su idea de España llevaba un insuperable desprecio por ese pedazo africano insertado en Europa. Ambas cosas son significativas y, lo peor, ni siquiera privativas de franceses o ingleses; o hasta rusos. El desprecio por todo lo español, excepto el <em>Quijote</em>, también ha sido ensayado por el mundo de la lengua española.<br><br>
      El resto de las lenguas de las grandes civilizaciones occidentales tiene autores: Dante es la <em>Comedia</em>, pero también es la <em>Vida nueva</em> y el discurso de la lengua vulgar. Francia es una pléyade y luego varios más; Inglaterra, Shakespeare, que ya es casi todo, y muchos más; Pushkin, Dostoievski, Tolstoi son Rusia; Alemania es Goethe, y Goethe es muchas obras. En esta lengua es un libro, porque del <em>Persiles</em>, nada y nada de las <em>ejemplares</em>. Sólo en Guanajuato creen que Cervantes era un gran dramaturgo. En fin. El caso es que Lope tenía razón cuando decía que Cervantes era el peor poeta de la lengua, y también Quevedo cuando dice que es el mejor prosista (y tampoco, porque el mejor prosista era él, Quevedo; y no lo digo porque Borges lo haya dicho sino porque Borges tenía razón). Detesto ese fervor lingüístico y moralino a un Quijote menos que demediado, el de sus puras golpizas de la primera parte, el pendenciero. Si eso fuera el Quijote, el único libro de la lengua española sería un desastre. Prefiero <em>El licenciado Vidriera</em>, para el caso, con todo y su débil final. Quedarse a la mitad del libro produce esa idea de Massenet: San Quijote contra la estupidez. La verdad es que incluso Sancho comienza como cosa mostrenca y termina en un ser maravilloso. Pero eso ya lo dijo bien Unamuno: Sancho se va quijotizando conforme el Quijote se va sanchopanzando. Si no fuera así, la novela hubiera acabado con las mismas taras que atoran incluso a los gigantes: a Calderón o a Gracián. Para no meterme en honduras, gloso por la puerta lateral. Ambos carecen de eso que recomienda Lope en su <em>Arte nuevo de hacer comedias</em>:</p>
      
    <blockquote>los soliloquios pinte de manera<br>
      que se transforme todo el recitante,<br>
      y con mudarse a sí, mude al oyente.</blockquote>
    <p>Pongamos diálogos donde dice soliloquios y lector en vez de oyente. Ya está. Porque no puede ser amigo, ni ejemplo, ni nada, un sujeto que no se muda; que, oyendo, no entiende. Ni sujeto, ni cristiano, ni persona. Ni novela. El primer esbozo del Quijote es el de un ser que no se sospecha a sí mismo: &ldquo;No por culpa mía, sino de mi caballo, estoy aquí tendido&rdquo;. No tiene dudas, no le preocupa la opinión de otros porque encuentra dentro de sí todo el repertorio que necesita para convalidar su alucinación. La suficiencia en el saber lo con­vierte en un viejo insoportable, no para el lector, para todos los demás personajes que se va topando en la novela. No soporta la disensión y no está dispuesto a escuchar. Hasta que aparece la magia y lo pone en su lugar. Es magia de verdadero prodigio, porque sucede donde debe: entre las dos orejas. No sé si sea desde la cueva de Montesinos, o desde el truco de la cabeza encantada, pero en cuanto comienza a escuchar a alguien más, alguien además de él mismo, hablar de su historia, el Quijote se va volviendo prójimo. Su real hazaña es h­aber aprendido a dudar de sí mismo. Hasta Sancho lo sabe, porque, de regreso a su pueblo, dice: &ldquo;Abre los brazos y recibe también a tu hijo don Quijote, que si viene vencido de los brazos ajenos, viene vencedor de sí mismo&rdquo;. En eso difiere de casi todos los personajes de Calderón, que pueden dudar de cosas, de los demás, pero jamás de sí mismos porque no tienen emociones ni pasiones que los trabajen en contra de su propia voluntad. Están concebidos como seres no contradictorios. Baste Segismundo: su naturaleza es tal que no permite ni el deseo de venganza ni las irrupciones de lo indeseable de uno mismo. Segismundo, igual que el hipotético sujeto cartesiano, es capaz de partir de sí sin el miedo de ser, él mismo, la sustancia alucinada. La vida es sueño, pero es un sueño que no está compuesto por los deseos sino por la incertidumbre de lo real. Es un sueño de la parte empírica, de los sentidos frente al mundo. Sueños buenos, sin la sombra del propio ser. Y sin su asombro. Algo se perdió en el camino. Todavía Lope (&ldquo;que con venir de mí mismo, no puedo venir más lejos&rdquo;) como Quevedo (&ldquo;y he quedado presentes sucesiones de difunto&rdquo;) encontraban su inconsecuencia y sus contradicciones en el tiempo. Y entendámonos: si se comparan los dos monólogos (los dos primeros) de Segismundo, con los dos de Hamlet (el del cráneo de Yorick y el famoso de &ldquo;<em>to be, or not to be..</em>.&rdquo;) probablemente hallemos más talento literario en Calderón que en Shakespeare. Pero mientras Hamlet es un semejante, Segismundo no es sino un icono, incapaz de ser tocado por su propio mal... Segismundo tiene las manos limpias. Es la víctima magnánima que debiéramos ser todos... ¿o no?<br><br>
      Sé que no quiero escoger como favorito ninguno de los episodios de la primera parte. Pensé mucho en el discurso a los cabreros: &ldquo;dichosa edad y siglos dichosos...&rdquo;. Pero, en realidad, su interés me viene de contexto y no por la lectura directa. Explico un poco: pensé en contrastar el discurso del Quijote sobre la Edad de Oro con aquel otro de Gonzalo en <em>La tempestad</em> de Shakespeare: &ldquo;<em>Had I plantation of this Isle...</em>&rdquo;, que es como decir: &ldquo;si yo colonizara aquesta isla&rdquo;. Es la misma idea, pero dicha a dos distintos públicos. Al Quijote lo callan con música; a Gonzalo, con burlas. No son lo mismo unos cabreros que los sofisticados nobles milaneses, y la idea de la Edad de Oro parece ir en sentidos contrarios. El Quijote dice, tal cual como Ovidio, que &ldquo;aún no se había atrevido la pesada reja del corvo arado a abrir ni visitar las entrañas piadosas de nuestra primera madre&rdquo;, mientras que Gonzalo habla de armas —puñales, espadas, pistolas—, de &ldquo;máquinas&rdquo;, y dice que no le servirían en su gobierno. El Quijote apunta a una sociedad anterior a todo Estado (cuando no existían las palabras &ldquo;tuyo&rdquo; y &ldquo;mío&rdquo;); Gonzalo, a un gobierno ideal y posible. Es interesante porque coincide con el estado de las dos naciones: España inicia una decadencia llena de reproches y prohibiciones de moral pública e Inglaterra inicia su proceso de crecimiento y consolidación, en particular, sobre las máquinas del ingenio. De aquí salen varias cosas curiosas.<br><br>
      Por ejemplo, la deriva vocabularia. En lengua española, la palabra máquina comenzó con dos sentidos, el de &ldquo;fábrica grande e inge­niosa&rdquo; (Covarrubias) y el de ingenio, aunque ya indica que se trata de maldades: &ldquo;fabricar uno en su entendimiento trazas para hacer mal a otro&rdquo;. La implicación moral no aparece todavía en Juan de Mena o en Montemayor, por ejemplo. En el <em>Quijote</em>, siempre se trata de malas cuentas: lo vapulean las máquinas y las maquinaciones. De todas todas, se engancha con los engaños mecánicos más simples y les halla auténticos prodigios mágicos. Pero nunca sabe qué hacer con ellos. Jamás pudo imaginar que la magia fuera en su favor o que la produjera él mismo. En eso es españolísimo. Frente a los segundos molinos, los de agua, las aceñas, el Quijote vuelve a perder: &ldquo;Dios lo remedie, que todo este mundo es máquinas y trazas, contrarias unas de otras. Yo no puedo más&rdquo;. (Por fortuna, después de rendirse, aparecen los malvados duques y la novela se endereza a su mejor parte.)<br><br>
      Los ingenios y maquinaciones de Próspero y Ariel son completamente lo contrario. Para Inglaterra, la salvación está en la máquina ingeniosa. No importa si por las magias de John Dee, por el ensueño de Bacon —que transforma la magia natural en filosofía empírica y desarrollo tecnológico— o simplemente por la invención industrial de las partes intercambiables: porque los cañones de la Armada Invencible eran todos artesanales, enormes, pesados, mientras que los de la flota de Drake eran producidos en serie, ligeros, y todos tenían el mismo calibre de disparo.<br><br>
      Y otro malestar. Byron califica al <em>Quijote</em> como &ldquo;un gran libro que mató a un gran pueblo&rdquo;. Recuerdo haber leído que Maeztu andaba por allá mismo. Hablaba de la <em>Ilíada</em> y la <em>Odisea</em> como inicio de la civilización griega, de la <em>Eneida</em> al origen de Roma. La <em>Comedia,</em> para Italia, igual. Creo que se saltaba a Shakespeare, pero también es verdad que Inglaterra es enorme después, no antes, de Shakespeare. En cambio, después del <em>Quijote</em>, la civilización española no hizo sino ir cayendo. Mejor pensar que son coincidencias y accidentes. La historia, aunque se explique de otro modo, no deja de estar marcada por estas piedras negras del monumento al desengaño. El desengaño fue el gran tema filosófico y literario de los siglos de oro, hasta que España dejó de engañarse. Y dejó de engañarse cuando perdió la imaginación. Coinciden el desengaño del <em>Quijote</em> y la anemia de la imaginación en esta lengua. Un letargo que no se acaba todavía, pero del que ya nos vamos apercibiendo desde, digamos, 1898.<br><br>
      Hay un diálogo epistolar entre Unamuno y Ganivet, ejemplar en muchos sentidos. Ambos reciben las noticias de la guerra con los Estados Unidos como Sancho sus &ldquo;cien mamonas en el rostro&rdquo;. Ganivet se queja amargamente de que no había modo de enfrentar el desarrollo tecnológico (esa forma de la magia) del mundo anglosajón. &ldquo;La invención del vapor fue un golpe mortal para nuestro poder. Hasta hace poco no sabíamos construir un buque de guerra, y hasta hace poquísimo nuestros maquinistas eran extranjeros&rdquo;. Exactamente: maquinistas. Y Unamuno le responde, después de llevar y traer a don Quijote para todo, con el recurso de siempre: no es por asuntos materiales que luchamos, sino espirituales: &ldquo;de la perfecta cristianización de nuestro pueblo es de lo que se trata&rdquo;.<br><br>
      Unos años después, en &ldquo;Mecanópolis&rdquo;, lo dice redondo: &ldquo;¡Que inventen ellos!&rdquo;, es decir, los anglosajones, inventores de esa &ldquo;nueva barbarie&rdquo; tecnológica. Al fin que nosotros, los civilizados, tenemos el espíritu de don Quijote.<br><br>
      Exactamente por eso es que detesto ese Quijote: es la confir­mación de que no somos, los de esta lengua, sino unos pobres diablos, indignos de la imaginación. Pero, evidentemente, no puedo decir eso de don Quijote, sino del quijotismo que venimos padeciendo: que inventen ellos, los que carecen de espíritu. Esa malhadada idea se viene a juntar con una pose moral, malcristianada que consiste en que sólo puede ser bueno el derrotado. El ganador, el victorioso, es malo porque obtiene un beneficio exclusivamente material y, como sabe Unamuno, el beneficio material excluye al espíritu. Mal rayo parta esa bondad equívoca de Unamuno y a todo ese quijotismo. Es una torcedura que consiste en suponer que la bondad es enemiga del acto en el mundo; es una bondad de manitas limpias, que cree que la confirmación de uno mismo es preferible y superior al cambio y a la transformación. Y &ldquo;Dios lo remedie, que todo este mundo es máquinas y trazas, contrarias unas de otras. Yo no puedo más&rdquo;.<br><br>
      Por eso, querido Carlos, mejor me excusas de participar en un homenaje quijotista.<br><br>
      Recibe un saludo de tu amigo.</p>
      
        <p><span style="font-size:12px;"><del>*</del>Carlos Miranda es el coordinador de este proyecto.</span></p>
        <p style="text-align:center;">
  <img src="../assets/images/icon.png" style="width:50px" alt="">
</p>
    </div>
</div>
<div class="col-sm-3 bio">
<h5>Sobre el autor</h5>
Julio Hubard es un poeta, ensayista, editor y traductor nacido en 1962 en la Ciudad de México. Estudio Filosofía en la Facultad de Filosofía y Letras de la UNAM. Ha participado en los consejos de redacción de La Gaceta del FCE, Textual, Letras Libres y Vuelta. Forma parte del Sistema Nacional de Creadores de Arte desde 1999. Ha publicado los libros <em>Sangre. Notas para la historia de una idea</em> (2006) y <em>Hacéldama</em> (2009).
</div>
</section>
	
<?php include 'footer.php' ?>
